examples/IB/implicit/ex2/input3d.cylinder
src/IB/IBStandardForceGen.cpp

IB examples explicit/ex0, explicit/ex1, explicit/ex2, explicit/ex5, implicit/ex0, implicit/ex1, and implicit/ex2 quit with error:
"attempt to subscript container with out-of-bounds index 0, but container only holds 0 elements."
I added an additional return statement if the number of springs/beams/target points were zero when forces were calculated in IBStandardForceGen
Additionally, IB examples implicit/ex2 failed when ran with input file input3d.cylinder with error:
P=00000:ERROR MESSAGE: 
P=00000:CartSideRobinPhysBdryOp::setPhysicalBoundaryConditions():
P=00000:  patch data index 6 does not correspond to a side-centered double precision variable.
The example did run with input file input3d.sphere. I changed options in the Cartesian Geometry to fix this. I am not sure if the example …

Fixed IB examples ran in debugging mode

---

include/ibamr/StaggeredStokesBlockFactorizationPreconditioner.h
src/navier_stokes/StaggeredStokesBlockFactorizationPreconditioner.cpp

The original implementation of the "block factorization" Stokes preconditioner implemented the lower-triangular preconditioner described in [this paper](http://cims.nyu.edu/~donev/CFD/StokesPreconditioners.pdf).
As requested by @adonev  and @fbusabiaga, this PR adds support for the upper-triangular and diagonal preconditioners also described in that paper, along with a symmetric non-diagonal preconditioner.

Additional block factorization preconditioners

---

ibtk/include/ibtk/IndexUtilities.h
ibtk/include/ibtk/private/IndexUtilities-inl.h
ibtk/src/lagrangian/FEDataManager.cpp
ibtk/src/lagrangian/LDataManager.cpp
ibtk/src/lagrangian/LEInteractor.cpp
ibtk/src/math/PETScMatUtilities.cpp
ibtk/src/refine_ops/LMarkerRefine.cpp
ibtk/src/utilities/LMarkerUtilities.cpp
include/ibamr/IBStandardInitializer.h
src/IB/IBFEMethod.cpp
src/IB/IBInstrumentPanel.cpp
src/IB/IBMethod.cpp
src/IB/IBStandardInitializer.cpp
src/IB/IMPInitializer.cpp
src/IB/IMPMethod.cpp

Add support for globalized indexing in IndexUtilities. It makes IndexUtilities a lightweight object that has an associated GridGeometry object that is used to compute unique Index values for a given position.
This PR replaces #38. It differs from that PR in that it avoids static global variables. This PR fixes #25.

Change implementation of IndexUtilities to guarantee consistent indexing

---

configure
examples/IBFE/explicit/ex0/main.cpp
examples/IBFE/explicit/ex1/convergence_tester.cpp
examples/IBFE/explicit/ex1/main.cpp
examples/IBFE/explicit/ex2/main.cpp
examples/IBFE/explicit/ex3/convergence_tester.cpp
examples/IBFE/explicit/ex3/main.cpp
examples/IBFE/explicit/ex4/convergence_tester.cpp
examples/IBFE/explicit/ex4/main.cpp
examples/IBFE/explicit/ex5/main.cpp
examples/IBFE/explicit/ex6/main.cpp
examples/IBFE/explicit/ex7/main.cpp
examples/IBFE/explicit/ex8/main.cpp
examples/IMP/explicit/ex0/main.cpp
ibtk/configure
ibtk/include/ibtk/PETScKrylovLinearSolver.h
ibtk/include/ibtk/private/PETScSAMRAIVectorReal-inl.h
ibtk/m4/configure_hdf5.m4
ibtk/m4/configure_hypre.m4
ibtk/m4/configure_libmesh.m4
ibtk/m4/configure_petsc.m4
ibtk/src/solvers/impls/PETScKrylovLinearSolver.cpp
ibtk/src/solvers/impls/PETScLevelSolver.cpp
ibtk/src/solvers/impls/PETScMultiVec.cpp
m4/configure_hdf5.m4
m4/configure_hypre.m4
m4/configure_libmesh.m4
m4/configure_petsc.m4
src/IB/IBFEPatchRecoveryPostProcessor.cpp
src/navier_stokes/StaggeredStokesBoxRelaxationFACOperator.cpp

* add support for PETSc 3.6
* use new libMesh constructors in examples
* remove support for PETSc 3.5
* remove support for libMesh 0.9.4 (which requires PETSc 3.5)

update to PETSc 3.6

---

ibtk/include/ibtk/FACPreconditioner.h
ibtk/src/solvers/impls/FACPreconditioner.cpp
include/ibamr/IBImplicitStaggeredHierarchyIntegrator.h
include/ibamr/StaggeredStokesFACPreconditionerStrategy.h
include/ibamr/StaggeredStokesIBBoxRelaxationFACOperator.h
include/ibamr/StaggeredStokesIBLevelRelaxationFACOperator.h
src/IB/IBImplicitStaggeredHierarchyIntegrator.cpp
src/IB/StaggeredStokesIBBoxRelaxationFACOperator.cpp
src/IB/StaggeredStokesIBLevelRelaxationFACOperator.cpp
src/navier_stokes/StaggeredStokesFACPreconditionerStrategy.cpp
tests/Stokes-IB/test0/main.cpp

* add getFACPreconditionerStrategy() to class FACPreconditioner
* setup Stokes+IB FAC operators to use the StaggeredStokesFACPreconditionerStrategy base class
* simplifying BC setup in IBImplicitStaggeredHierarchyIntegrator

fixing BC handling in implicit IB solver

---

src/IB/StaggeredStokesIBBoxRelaxationFACOperator.cpp
src/IB/StaggeredStokesIBLevelRelaxationFACOperator.cpp

Updates the Stokes+IB FAC operator residual calculation to use the matrix-free
implementation provided by the parent StaggeredStokesFACPreconditionerStrategy
base class along with the matrix-based representation of the Eulerian elasticity operator (S*A*J).
This avoids relying on the level solvers to compute the residuals.

updating Stokes+IB FAC operator residual calculation

---

src/IB/StaggeredStokesIBBoxRelaxationFACOperator.cpp

This fixes a regression that I introduced when refactoring the Stokes-IB smoothers.

fix coarse-grid operator extraction in Stokes-IB box relaxation operator

---

ibtk/src/math/HierarchyMathOps.cpp

Somehow the levels were never being set in any of the HierarchyXXXXDataOpsReal objects managed by HierarchyMathOps.

resetting HierarchyDataOps level range in HierarchyMathOps

---

ibtk/include/ibtk/LNode.h
ibtk/include/ibtk/LNodeIndex.h
ibtk/include/ibtk/private/LNode-inl.h
ibtk/include/ibtk/private/LNodeIndex-inl.h
src/IB/IBStandardInitializer.cpp
src/IB/IMPInitializer.cpp

This PR adds the feature to get initial periodic shifts and displacements for LNodes. This can be useful for certain cases of periodic boundary conditions where the initial unshifted position X0 is required.

Initial periodic shifts

---

ibtk/src/lagrangian/FEDataManager.cpp
ibtk/src/lagrangian/LDataManager.cpp
ibtk/src/refine_ops/CartCellDoubleBoundsPreservingConservativeLinearRefine.cpp
src/IB/IBFEMethod.cpp

Currently LDataManager does not know what to do if an IB point happens to "leave" the computational domain via a non-periodic boundary. This PR attempts to ensure that points cannot accidentally "slip through" such boundaries due to floating point effects.

ensure that IB points do not "leave" the computational domain

---

src/IB/CIBMethod.cpp

The center of mass (orientation) of the rigid bodies is updated with d_trans_vel_new in the midpoint method for steady Stokes flows (rho==0).

midpoint integrator fixed, for steady Stokes is just forward Euler.

---

include/ibamr/ibamr_enums.h
src/IB/DirectMobilitySolver.cpp

FILE is a standard C type, there should not be an enum or type name with the same name.

prevent namespace collision with standard C FILE type name

---

src/IB/ConstraintIBMethod.cpp

Compute the CellIndex from global domain geometry rather than from patch geometry for more robust volume computation

Global CellIndex computation in ConstraintIBMethod

---

examples/CIB/ex0/main.cpp
examples/CIB/ex1/main.cpp
examples/CIB/ex2/input2d.plate.amr
examples/CIB/ex2/main.cpp
ibtk/include/ibtk/PoissonFACPreconditionerStrategy.h
ibtk/src/solvers/impls/PoissonFACPreconditionerStrategy.cpp
ibtk/src/solvers/impls/SCPoissonPointRelaxationFACOperator.cpp

@boyceg: This PR requires SCPoissonPointRelaxationFACOperator to have ghost cell width for scratch idx variables equal to that of chosen delta function. I used input file to change this, but probably one should send the ghost cell width information to constructor of such solvers (currently missing in PossonManager classes)

Fixing AMR for CIBMethod and updating CIB examples

---

scripts/check_formatting.sh

Users have to re-run ./scripts/setup_clang_format_precommit_hook.sh in IBAMR root to get the updated file.
To run "git clang-format" only on C/C++ files, you can do "git clang-format --extensions=C,c,cpp,h".

set provided pre-commit hook only to check C/C++ files

---

include/ibamr/IBHierarchyIntegrator.h
include/ibamr/IBImplicitStrategy.h
include/ibamr/IBStrategy.h
src/IB/IBExplicitHierarchyIntegrator.cpp
src/IB/IBImplicitStaggeredHierarchyIntegrator.cpp
src/IB/IBMethod.cpp
src/IB/IBStrategy.cpp

Pure forward Euler IB time stepping appears to be rather unstable, requiring extremely small time step sizes for stability --- much smaller than the explicit midpoint and trapezoidal rules. This PR changes explicit Euler time stepping to use a combination of forward Euler and explicit backward Euler. Essentially we do an explicit predictor:
X~(n+1) = X(n) + dt*U(n) = X(n) + dt*J[X(n)] u(n)
followed by an explicit "corrector":
X(n+1) = X(n) + dt*U~(n+1) = X(n) + dt*J[X~(n)] u(n+1).
Simply using forward Euler, so that X(n+1) = X(n) + dt*U(n), appears to be unstable.
All structural forces are computed using the X(n) configuration:
f = S[X(n)] F[X(n)]
I haven't experimented with all possible combinations, but it appears that using:
f = S[X~(n+1)] F[X~(n+1)]
is unstable. …

update first-order explicit IB time stepping to use explicit forward/backward Euler

---

ibtk/include/ibtk/IndexUtilities.h
ibtk/include/ibtk/PETScMatUtilities.h
ibtk/include/ibtk/private/IndexUtilities-inl.h
ibtk/src/math/PETScMatUtilities.cpp
ibtk/src/math/PETScVecUtilities.cpp
ibtk/src/solvers/impls/PETScLevelSolver.cpp
include/ibamr/StaggeredStokesIBLevelRelaxationFACOperator.h
src/IB/StaggeredStokesIBLevelRelaxationFACOperator.cpp
src/navier_stokes/StaggeredStokesPETScMatUtilities.cpp
src/navier_stokes/StaggeredStokesPETScVecUtilities.cpp

@boyceg: Please review. It took a lot of time. The input file needs to specify U_petsc_prolongation_method = "LINEAR"
1) The bug with periodic domain is coming from AO returning negative index. This is caught here for RT0 op:
https://github.com/IBAMR/IBAMR/blob/amneetb/bi-tri-linear-prolongation/ibtk/src/math/PETScMatUtilities.cpp#L1147
and here for LINEAR op
https://github.com/IBAMR/IBAMR/blob/amneetb/bi-tri-linear-prolongation/ibtk/src/math/PETScMatUtilities.cpp#L1512
Not sure why the index (0,0) is not getting mapped (Try Stokes-IB/test1 with input2d.shell having periodic boundary(ies))

Adding bi/trilinear matrix based prolongation operator.

---

.jenkins_fulltest
.jenkins_quicktest

Once this is merged Jenkins will use ccache with the C/C++ compilers and the configure script should run faster.

update .jenkins* files to use ccache with compilers and --config-cache

---

ibtk/include/ibtk/LDataManager.h
ibtk/src/lagrangian/LDataManager.cpp
include/ibamr/IBMethod.h
include/ibamr/IMPMethod.h
src/IB/IBMethod.cpp
src/IB/IMPMethod.cpp

This is optional (off by default) and only applies to non-periodic boundaries.

add option to emit an error message if any IB points "escape" from the computational domain

---

ibtk/include/ibtk/PETScSAMRAIVectorReal.h
ibtk/include/ibtk/private/PETScSAMRAIVectorReal-inl.h
ibtk/src/solvers/impls/PETScKrylovLinearSolver.cpp
ibtk/src/solvers/impls/PETScLevelSolver.cpp
ibtk/src/solvers/impls/PETScMFFDJacobianOperator.cpp
ibtk/src/solvers/impls/PETScNewtonKrylovSolver.cpp
ibtk/src/solvers/wrappers/PETScSAMRAIVectorReal.cpp
ibtk/src/solvers/wrappers/PETScSNESJacobianJOWrapper.cpp
src/IB/CIBSaddlePointSolver.cpp
src/IB/CIBStaggeredStokesOperator.cpp
src/IB/DirectMobilitySolver.cpp
src/IB/IBImplicitStaggeredHierarchyIntegrator.cpp
src/IB/IBMethod.cpp
src/IB/KrylovFreeBodyMobilitySolver.cpp
src/IB/KrylovMobilitySolver.cpp

This PR should remove the need to increase the "state" of PETSc vectors in library code outside of the PETScSAMRAIVectorReal implementation.

changing PETScSAMRAIVectorReal API for getting/restoring SAMRAI vectors

---

ibtk/include/ibtk/PETScLevelSolver.h
ibtk/src/math/PETScVecUtilities.cpp
ibtk/src/solvers/impls/PETScLevelSolver.cpp
include/ibamr/StaggeredStokesIBLevelRelaxationFACOperator.h
include/ibamr/StaggeredStokesPETScMatUtilities.h
include/ibamr/StaggeredStokesPETScVecUtilities.h
src/IB/StaggeredStokesIBLevelRelaxationFACOperator.cpp
src/navier_stokes/StaggeredStokesPETScLevelSolver.cpp
src/navier_stokes/StaggeredStokesPETScMatUtilities.cpp
src/navier_stokes/StaggeredStokesPETScVecUtilities.cpp
tests/Stokes-IB/test1/input2d.shell

This is a revision of PR #120 that cleans up the API.

add Galerkin coarse-grid operators for Stokes-IB

---

.jenkins_fulltest
.jenkins_quicktest

@boyceg 
I changed compiler flags to just "-Wall" and replaced the samrai path with "$SAMRAI_DIR" to allow for optimized builds. All the jenkins jobs have $SAMRAI_DIR defined, so hopefully this should work.
I still have yet to get the optimized build of SAMRAI built on the VM, but this will make it possible to get it running once it is in place.

Update .jenkins* files

---

ibtk/Makefile.in
include/ibamr/INSStaggeredStabilizedPPMConvectiveOperator.h
src/navier_stokes/INSStaggeredStabilizedPPMConvectiveOperator.cpp

We commonly use flow straightening near open boundaries, but in these regions, u.grad(u) ~ 0.
In those regions, it may make sense to set u.grad(u) = 0 explicitly, to avoid instabilities that appear to be related to the treatment of open boundary conditions.
This PR allows us to explicitly remove the convective term in the "stabilization" region when using the "STABILIZED_PPM" convective operator.

adding option to convective boundary stabilization to use only the visous terms at the boundary

---

ibtk/include/ibtk/CCPoissonPETScLevelSolver.h
ibtk/include/ibtk/SCPoissonPETScLevelSolver.h
ibtk/src/solvers/impls/CCPoissonPETScLevelSolver.cpp
ibtk/src/solvers/impls/PETScLevelSolver.cpp
ibtk/src/solvers/impls/SCPoissonPETScLevelSolver.cpp

@boyceg, @amneetb: I moved the constructPatchLevelASMSubdomains calls for the PETSc level Poisson solvers to a generateASMSubdomains function. Moreover, I added provisions to ensure that generate_petsc_is_from_std_is is never called from PETScLevelSolver when subdomains are indexed by PETSc IS indexing directly.
This allows for ASM preconditioning to be used for PETSc level Possion solvers; it was encountering TBOX_ERROR before.

Adding provisions to allow ASM preconditioning for PETSc level Poisson solvers

---

ibtk/src/lagrangian/LSiloDataWriter.cpp

An option list wasn't being deallocated in the data writer. It caused leaks on the order of ~100 bytes when writing data.

Fixed small memory leak in IB data writer.

---

include/ibamr/PenaltyIBMethod.h
src/IB/IBHierarchyIntegrator.cpp
src/IB/PenaltyIBMethod.cpp

Lagrangian data in the penalty IB method was being initialized *after* all other Lagrangian data had been redistributed.
@boyceg It seems that the penalty IB method is the only IBMethod class that initializes method specific Lagrangian data in the initializePatchHierarchy() function. For example, the generalized IB method initializes director vectors in the initializeLevelData() function. Would it be better to move penalty IB method Lagrangian data initialization to the initializeLevelData() function?

Delayed initial Lagrangian data movement until after all Lag data has been set up.

---

.jenkins_fulltest
.jenkins_quicktest

This way, the dependencies need not be build with a prescribed structure.
This is mostly a suggestion -- I think it would make it easier for the person building the dependencies for the jenkins jobs.

Update jenkins files to use environment variables

---

src/IB/IBStandardInitializer.cpp

Adds checks for duplicated entries in spring, xspring, beam, rod, target, anchor, and mass point files.
Closes #75.

improve error checking in IBStandardInitializer

---

examples/IBFE/explicit/ex7/example.cpp

Removed code that was previously enclosed in {{ #if 0, #endif }}
Example now compiles & runs successfully.

IBFE ex7 tiny fix

---

include/ibamr/AdvDiffHierarchyIntegrator.h
src/adv_diff/AdvDiffSemiImplicitHierarchyIntegrator.cpp

@boyceg Should I make a note in the documentation that if a function to set the velocity is not specified, the variable-context pairs of u_var and getCurrent/Scratch/NewContext() must be specified?

Fixed reset of advection-diffusion velocity after cycle 0.

---

ibtk/src/lagrangian/FEDataManager.cpp
src/IB/CIBFEMethod.cpp

Removed NULL in constructors of UniquePtr for compatibility with C++11 and and the newer version of libMesh. IBAMR now compiles with libMesh, commit  a3ca425d7e4b8f8c43417644e505ae8ac87ee410 (12/26/2017)

updating to C++11 for newer libMesh versions

---

.jenkins_quicktest

Our current CI server is getting bogged down with the full gtests. For now, let's just run those in the nightly builds.

disabling gtest for Jenkins CI tests

---

src/IB/IBFEMethod.cpp

Velocity initialization functions were using coordinate mapping function variables. Fixed this issue.

fixed a small bug in IBFEMethod.cpp

---

src/IB/IBFEInstrumentPanel.cpp

this addition is needed to check if we are correctly
counting the quadrature points on the meter meshes.

added a missing sumReduction 

---

ibtk/src/lagrangian/fortran/lagrangian_delta.f.m4
ibtk/src/lagrangian/fortran/lagrangian_interaction2d.f.m4
ibtk/src/lagrangian/fortran/lagrangian_interaction3d.f.m4
src/adv_diff/fortran/adv_diff_wp_convective_op2d.f.m4
src/adv_diff/fortran/adv_diff_wp_convective_op3d.f.m4
src/level_set/fortran/levelsetops2d.f.m4
src/level_set/fortran/levelsetops3d.f.m4

After some issues with AFS I finally have things set up. Here is a little PR to get started!
1. gfortran rightfully complains that the integral types should be declared before the real ones since they are used to define the real ones.
2. I removed unused local variables or used the technique applied elsewhere (`x = x`) to suppress warnings.

Fix fortran warnings

---

examples/ConstraintIB/impulsively_started_cylinder/RigidBodyKinematics.cpp
ibtk/src/math/PETScMatUtilities.cpp
ibtk/src/math/PETScVecUtilities.cpp
src/IB/CIBFEMethod.cpp
src/IB/CIBMethod.cpp
src/navier_stokes/StaggeredStokesPETScMatUtilities.cpp

This uses the classic `(void)x;` trick or places things in a scope surrounded by `#if/#endif`.

Fix some unused variable warnings.

---

src/level_set/fortran/levelsetops2d.f.m4
src/level_set/fortran/levelsetops3d.f.m4

@boyceg @drwells @amneetb This should fix the uninitialized variable warnings in the level set Fortran code without unintended consequences. I have tested with level_set/ex0.

Fixing uninitialized fortran warnings in level set fortran code

---

examples/CIB/Makefile.am
examples/CIB/Makefile.in
examples/CIBFE/Makefile.am
examples/CIBFE/Makefile.in
examples/ConstraintIB/Makefile.am
examples/ConstraintIB/Makefile.in
examples/IB/Makefile.am
examples/IB/Makefile.in
examples/IB/explicit/Makefile.am
examples/IB/explicit/Makefile.in
examples/IBFE/Makefile.am
examples/IBFE/Makefile.in
examples/IBFE/explicit/Makefile.am
examples/IBFE/explicit/Makefile.in
examples/IMP/Makefile.am
examples/IMP/Makefile.in
examples/IMP/explicit/Makefile.am
examples/IMP/explicit/Makefile.in
examples/Makefile.am
examples/Makefile.in
examples/adv_diff/Makefile.am
examples/adv_diff/Makefile.in
examples/level_set/Makefile.am
examples/level_set/Makefile.in
examples/multiphase_flow/Makefile.am
examples/multiphase_flow/Makefile.in
examples/navier_stokes/Makefile.am
examples/navier_stokes/Makefile.in
examples/vc_navier_stokes/Makefile.am
examples/vc_navier_stokes/Makefile.in

The example programs are currently compiled in the following way:
```makefile
examples:
@(cd IB               && $(MAKE) $(AM_MAKEFLAGS) $@) || exit 1;
@(cd IBFE             && $(MAKE) $(AM_MAKEFLAGS) $@) || exit 1;
@(cd adv_diff         && $(MAKE) $(AM_MAKEFLAGS) $@) || exit 1;
@(cd advect           && $(MAKE) $(AM_MAKEFLAGS) $@) || exit 1;
@(cd navier_stokes    && $(MAKE) $(AM_MAKEFLAGS) $@) || exit 1;
@(cd ConstraintIB     && $(MAKE) $(AM_MAKEFLAGS) $@) || exit 1;
@(cd CIB              && $(MAKE) $(AM_MAKEFLAGS) $@) || exit 1;
@(cd level_set        && $(MAKE) $(AM_MAKEFLAGS) $@) || exit 1;
@(cd multiphase_flow  && $(MAKE) $(AM_MAKEFLAGS) $@) || exit 1;
@(cd vc_navier_stokes && $(MAKE) $(AM_MAKEFLAGS) $@) || exit 1;
```
this prevents parallelization since the rule itself is a sequence …

Enable parallelization in example compilation.

---

examples/ConstraintIB/impulsively_started_cylinder/input2d
examples/ConstraintIB/impulsively_started_cylinder/input2d.test
examples/IB/explicit/ex0/input2d
examples/IB/explicit/ex0/input2d.shell
examples/IB/explicit/ex0/input2d.shell_circum_fibers
examples/IB/explicit/ex0/input2d.test
examples/IBFE/explicit/ex0/input2d
examples/IBFE/explicit/ex0/input2d.test
examples/IBFE/explicit/ex3/input2d
examples/IBFE/explicit/ex3/input2d.test
examples/IBFE/explicit/ex6/input2d
examples/IBFE/explicit/ex6/input2d.test
examples/IBFE/explicit/ex7/input2d.caseC
examples/IBFE/explicit/ex7/input2d.caseS2
examples/IBFE/explicit/ex7/input2d.caseSP
examples/IBFE/explicit/ex7/input2d.test
examples/IBFE/explicit/ex8/input2d
examples/IBFE/explicit/ex8/input2d.test
examples/navier_stokes/ex1/input2d
examples/navier_stokes/ex1/input2d.test
examples/navier_stokes/ex1/input3d
examples/navier_stokes/ex1/input3d.test
ibtk/examples/PETScOps/ProlongationMat/input2d
ibtk/examples/PETScOps/ProlongationMat/input2d.test
ibtk/examples/PETScOps/ProlongationMat/input3d
ibtk/examples/PETScOps/ProlongationMat/input3d.test

Newer versions of muparser removed the `if(A,B,C)` function, so we cannot run the test suite with them.
The ternary syntax is supported by (IIRC) version 2 and newer, which includes the bundled copy of muparser.

Use ternary if in muparser.

---

ibtk/include/ibtk/muParserRobinBcCoefs.h
ibtk/src/boundary/physical_boundary/muParserRobinBcCoefs.cpp

The present implementation works since modifying a variable through a pointer is permissible in a const function.
Since we write to these variables and then read them through Eval(), it is reasonable to mark them as mutable since the value set at by the end of the function won't be read again after the function returns.
Mentioned in #258.

Convert some pointers to mutable variables.

---

examples/adv_diff/ex0/input3d.test

The test itself records that it compares new error calculations to those measured in October 2016: however, the input file is no longer the same (`DT` and `END_TIME`, among other things, are now different) as it was  then. This commit fixes the input file to match the one used to generate the data in 2016 (i.e., near commit cb7b841f1a9).
The test passes with this fix.

Fix the adv_diff ex0 3D test.

---

ibtk/include/ibtk/LDataManager.h
ibtk/include/ibtk/LInitStrategy.h
ibtk/src/lagrangian/LDataManager.cpp
include/ibamr/IBRedundantInitializer.h
include/ibamr/IBStandardInitializer.h
src/IB/IBRedundantInitializer.cpp
src/IB/IBStandardInitializer.cpp

This fixes the issues addressed in #278 for `IBRedundantInitializer`. It removes `const` from a member function in `LInitStrategy` and adds an extra `init` call to `IBRedundantInitializer`.
This change should fix the issue for `IBStandardInitializer` as well.

Update const function in LInitStrategy and add init call to IBRedundantInitializer

---

include/ibamr/IBFEInstrumentPanel.h
src/IB/IBFEInstrumentPanel.cpp

removing exodus io and replacing probably with output to STLs.

Removing exodus io from IBFEInstrumentPanel class

---

examples/adv_diff/ex1/input2d.test
examples/adv_diff/ex1/input3d.test

The issue with these tests is that viz_dump_interval depends on DT, which is never defined. We can get around this by simply never writing output.
Part of #290.

Fix aborting tests in adv_diff.

---

examples/IBFE/explicit/ex0/Makefile.am
examples/IBFE/explicit/ex0/Makefile.in
examples/IBFE/explicit/ex0/test_main.cpp

Commit e6aeeb564ca changed the way we do a particular L2 projection in `IBFE/explicit/ex0`: instead of using a given initial guess for the solution we now zero the vector. This caused the computed solution to be slightly different from the known value.
This commit changes the test to run at a much stricter numerical tolerance, and compares it to values computed (with the same tolerances) before e6aeeb564ca.
We should ultimately find a better way to jointly handle PETSc and SAMRAI options with the input file or command line parameters, but I think we should delay that fix until after 0.3 is done.

Run one test at stricter tolerances.

---

src/IB/IBFEInstrumentPanel.cpp

Not a substantial issue, but I have seen this warning one too many times now.

Fix a warning regarding initialization order.

---

examples/IBFE/explicit/ex5/example.cpp
examples/IBFE/explicit/ex5/input2d
examples/IBFE/explicit/ex5/input2d.test
examples/IBFE/explicit/ex5/input3d
examples/IBFE/explicit/ex5/input3d.test
examples/IBFE/explicit/ex6/example.cpp
examples/IBFE/explicit/ex6/input2d.test

It looks like we defined these tests and examples without adding all physical parameters to the input files. I added them and also cleaned up the implementation a bit: the relevant IBFE objects have nice support for pointers to context objects, so I moved the state there from global statically allocated variables.
This is enough of a fix to make the tests pass (and avoid basic errors, e.g., looking for variables in the database that were not defined in the input file) but the examples still fail with the default values. I will open separate issues for those.

Fix aborting IBFE tests

---

ibtk/src/boundary/physical_boundary/PhysicalBoundaryUtilities.cpp

In both cases the previous clause checked that `codim == 2`. These were caught by the GCC warning -Wduplicated-cond.

Remove some duplicated if statements.

---

src/navier_stokes/StaggeredStokesPhysicalBoundaryHelper.cpp

While the present code is correct, the order of operations (`==`, `&&`, then `||`) is a bit esoteric, so GCC reasonably suggests adding parentheses.

Add parentheses suggested by -Wparentheses.

---

README.md

Part of #266.  This updates a few links to correctly direct to the `github.io` pages. Note that we claim in the README that there are visualization examples on the `github.io` pages (or we will once this is merged), but there are no such visualizations at this time.

Fix links in top level README.

---

src/IB/IBFEDirectForcingKinematics.cpp
src/IB/IBStandardForceGen.cpp

For certain compilers, one will hit the following assertion in debug mode when trying to access or pass `&some_vector[0]` when some_vector is empty:
```
/usr/include/c++/4.8.3/debug/vector:346:error: attempt to subscript 
container with out-of-bounds index 0, but container only holds 0     
elements.
```
I found this because some of the examples will crash in debug mode during the first time step. The changes in this PR fixes that.
For IBStandardForceGen, I think it's safer to include the return statement. This is already done for beams and springs, but it was missing for target points.
For  IBFEDirectForcingKinematics, nodal_X_values should be resized before it gets passed here:
https://github.com/IBAMR/IBAMR/blob/nishant/fix-vector-dbg-assert/src/IB/IBFEDirectForcingKinematics.cpp#L747 …

Fixing out-of-bounds error for vectors

---

configure
ibtk/configure
ibtk/m4/configure_petsc.m4
m4/configure_petsc.m4

PETSc 3.10 will be out soon and we are compatible with it. However, the m4 scripts currently limit us to using 3.9 or older; this PR deletes the upper bound.
The PETSc interfaces we use are quite stable and are unlikely to change in the near future, so there is no reason to specify a maximum version: we should simply document what works and let users use new versions if they like.

Allow versions of PETSc newer than 3.9.

---

configure
ibtk/configure
ibtk/m4/configure_petsc.m4
m4/configure_petsc.m4

Allow versions of PETSc newer than 3.9: 0.3.0 release

---

examples/ConstraintIB/falling_sphere/CartGridBodyForce.cpp

The headers define their own inclusion checks so these are not necessary.

Remove some unused preprocessor guards.

---

ibtk/include/ibtk/FEDataManager.h

It looks like we do not use `boost.m4` anywhere but we should keep it up to date.
This is a followup to #307, which was only on the 0.3.0 branch.

Use the C++11 std::unordered_map.

---

ibtk/include/ibtk/AppInitializer.h
ibtk/include/ibtk/EdgeDataSynchronization.h
ibtk/include/ibtk/FaceDataSynchronization.h
ibtk/include/ibtk/HierarchyGhostCellInterpolation.h
ibtk/include/ibtk/HierarchyMathOps.h
ibtk/include/ibtk/LMarker.h
ibtk/include/ibtk/LMesh.h
ibtk/include/ibtk/LSet.h
ibtk/include/ibtk/NodeDataSynchronization.h
ibtk/include/ibtk/ParallelEdgeMap.h
ibtk/include/ibtk/ParallelMap.h
ibtk/include/ibtk/ParallelSet.h
ibtk/include/ibtk/PatchMathOps.h
ibtk/include/ibtk/SideDataSynchronization.h
ibtk/include/ibtk/StaggeredPhysicalBoundaryHelper.h
include/ibamr/CIBMobilitySolver.h
include/ibamr/CIBSaddlePointSolver.h
include/ibamr/DirectMobilitySolver.h
include/ibamr/IBFEDirectForcingKinematics.h
include/ibamr/IBInstrumentPanel.h
include/ibamr/IBKirchhoffRodForceGen.h
include/ibamr/KrylovFreeBodyMobilitySolver.h
include/ibamr/KrylovMobilitySolver.h
include/ibamr/StokesSpecifications.h

From the discussion in #365: lets fix this before we forget.
These destructors are, presently, already virtual because we inherit from `tbox::DescribedClass`. However, this class was removed in SAMRAI 3, so we will need to do explicitly make them virtual when we require SAMRAI 3 in the future.

Mark more destructors as virtual.

---

doc/news/changes/minor/20181024AaronBarrettDavidWells
src/navier_stokes/fortran/Makefile.am
src/navier_stokes/fortran/Makefile.in

Fixes #373.
The `.f.m4` files are source files; the `.f` files are generated.

Don't delete a source file in make clean.

---

ibtk/include/ibtk/SCPoissonPointRelaxationFACOperator.h
include/ibamr/StaggeredStokesBoxRelaxationFACOperator.h
include/ibamr/StaggeredStokesIBLevelRelaxationFACOperator.h
include/ibamr/StaggeredStokesLevelRelaxationFACOperator.h

Tiny little cosmetic fix; we don't need forward declarations for `boost::array` since we don't use it any more.

Remove forward declarations of boost::array.

---

config/IBAMR_config.h.tmp.in
configure
configure.ac
doc/news/changes/minor/20181031DavidWells

This commit adds basic preprocessor constants and one function for doing version checks. One can now do things like
```cpp
#if IBAMR_VERSION_GTE(1, 0, 0)
std::vector<MeshBase *> meshes;
#else
std::vector<Mesh *> meshes;
#endif
```
for compatibility with the changes made in #368.
I really wish I had realized this was missing before the 0.3.0 release; better late than never, I suppose.

Add versioning macros.

---

ibtk/include/ibtk/private/IndexUtilities-inl.h
src/IB/CIBMethod.cpp
src/IB/ConstraintIBMethod.cpp
src/IB/MobilityFunctions.cpp

Caught while debugging something in #380.
I opted to add the check at the call site instead of the function itself since, conceivably, someone else already has such a check (and an invalid structure id may not mean the program cannot continue).

Add some checks for valid structure ids.

---

ibtk/include/ibtk/LDataManager.h

Prior to #380, `std::vector<bool> LDataManager::d_needs_synch` had been initialized via an initialization list in `LDataManager.cpp` via
```
...
d_needs_synch(true),
...
```
I think that what was happening here is that `true` was being silently converted to the integer value `1`, and then the constructor was populating `d_needs_synch` with `false`.
This member actually does not need to be initialized to anything, because its values will be set correctly in `LDataManager::setPatchLevels()` when setting up the Lagrangian data structures.

fixing initialization of LDataManager::d_needs_synch

---

include/ibamr/StaggeredStokesFACPreconditionerStrategy.h
src/adv_diff/AdvDiffPredictorCorrectorHyperbolicPatchOps.cpp

Follow up to #380. This fixes a spelling error and an incorrect deletion.

Update a few default initialization values.

---

ibtk/src/lagrangian/FEDataManager.cpp

These commits are cosmetic improvements taken from #396 that are not directly related to partitioning.
I think we should always put `TBOX_ASSERT` in curly brackets since it is a macro; weird things can happen if half of the macro is in one scope and the other half is in another.

Reformat loops

---

configure
doc/news/changes/incompatibilities/20181129DavidWells
ibtk/configure
ibtk/include/ibtk/FEDataManager.h
ibtk/m4/configure_libmesh.m4
ibtk/src/lagrangian/FEDataManager.cpp
m4/configure_libmesh.m4

Related to #396: we need to recalculate all members of `FEDataManager` after we repartition the mesh. Its getting a bit complicated to call `delete` in a dozen places, so I replaced all owning raw pointers with `std::unique_ptr`s.
This is a lot easier if we make the (minor) change of really requiring that `libMesh::UniquePtr` is `std::unique_ptr`. I updated the configuration scripts to check this.

Fedatamanager unique ptrs

---

include/ibamr/IBFEMethod.h
src/IB/CIBFEMethod.cpp
src/IB/IBFEMethod.cpp

Some of the IBFE examples (i.e., IBFE/explicit/ex10) leak memory at the end of the calculation: in particular, libMesh claims that we do not delete all `EquationSystem` objects. This PR gets rid of manual memory management of these objects: it doesn't completely fix the problem but it does allow us to get rid of a few tricky `delete` statements.

Use unique_ptr and references in IBFEMethod.

---

examples/CIBFE/ex0/example.cpp
examples/CIBFE/ex1/example.cpp
examples/IBFE/explicit/ex0/example.cpp
examples/IBFE/explicit/ex1/example.cpp
examples/IBFE/explicit/ex10/example.cpp
examples/IBFE/explicit/ex11/example.cpp
examples/IBFE/explicit/ex2/example.cpp
examples/IBFE/explicit/ex3/example.cpp
examples/IBFE/explicit/ex4/example.cpp
examples/IBFE/explicit/ex5/example.cpp
examples/IBFE/explicit/ex6/example.cpp
examples/IBFE/explicit/ex7/example.cpp
examples/IBFE/explicit/ex8/example.cpp
examples/IBFE/explicit/ex9/example.cpp
examples/multiphase_flow/ex2/example.cpp
ibtk/include/ibtk/FEDataManager.h
ibtk/src/lagrangian/FEDataManager.cpp
scripts/replaceLibmeshPointers.pl
src/IB/CIBFEMethod.cpp
src/IB/IBFECentroidPostProcessor.cpp
src/IB/IBFEDirectForcingKinematics.cpp
src/IB/IBFEInstrumentPanel.cpp
src/IB/IBFEMethod.cpp
src/IB/IBFEPatchRecoveryPostProcessor.cpp
src/IB/IBFEPostProcessor.cpp
src/IB/IBFESurfaceMethod.cpp
src/IB/IMPInitializer.cpp

Follow up to #403. Replace all instances of `LibMesh::UniquePtr` with `std::unique_ptr`. A perl script is provided in the scripts directory.
If we want to keep using the Libmesh alias we can close this. I won't be offended :)

Replaced UniquePtr with unique_ptr

---

doc/news/changes/minor/20181214DavidWells
ibtk/include/ibtk/libmesh_utilities.h
ibtk/lib/Makefile.am
ibtk/lib/Makefile.in
ibtk/src/utilities/libmesh_utilities.cpp

Another spinoff from #396: this PR adds two new functions to visualize the libMesh partitioning (both `Elem`-wise and `Node`-wise).

Add lib mesh partitioning visualization

---

ibtk/include/ibtk/IndexUtilities.h
ibtk/include/ibtk/LNodeIndex.h
ibtk/include/ibtk/libmesh_utilities.h
ibtk/src/lagrangian/FEDataManager.cpp
ibtk/src/solvers/impls/CCPoissonBoxRelaxationFACOperator.cpp
ibtk/src/solvers/impls/CCPoissonHypreLevelSolver.cpp
ibtk/src/solvers/impls/CCPoissonPointRelaxationFACOperator.cpp
include/ibamr/IBFEInstrumentPanel.h
include/ibamr/IBInstrumentPanel.h
include/ibamr/IBRedundantInitializer.h
src/IB/IBFESurfaceMethod.cpp

`std::binary_function` is only necessary for defining two member typedefs when using `std::not2`, which we do not ever use. `std::binary_function `was also deprecated in C++11.

Remove usage of std::binary_function.

---

ibtk/include/ibtk/libmesh_utilities.h
ibtk/src/utilities/libmesh_utilities.cpp

These functions should not be marked as inline.
This shows that I should rebase against master more often instead of relying on my own band-aided branches...

Fix a link problem with libmesh utilities.

---

configure
doc/news/changes/incompatibilities/20181220DavidWells
ibtk/configure
ibtk/m4/configure_libmesh.m4
m4/configure_libmesh.m4

We use ReplicatedMesh now, which was new with libMesh 1.1.0.

Require libMesh 1.1.0 or newer.

---

ibtk/include/ibtk/ibtk_utilities.h
include/ibamr/CIBMethod.h
include/ibamr/CIBStrategy.h
include/ibamr/ConstraintIBMethod.h
include/ibamr/IBFEDirectForcingKinematics.h
include/ibamr/IBHydrodynamicForceEvaluator.h
src/IB/CIBFEMethod.cpp
src/IB/CIBMethod.cpp
src/IB/CIBStrategy.cpp

Eigen will automatically use AVX512 and other vectorized instruction sets if they are available. This causes segmentation faults (on AMD64, at least) when objects are not aligned to 128-bit (or better) addresses. This commit gets around this by specifying alignment requirements (or, for std::vector [1], a custom allocator) for objects with Eigen members.
[1] http://eigen.tuxfamily.org/dox-devel/group__TopicStlContainers.html

Fix alignment of Eigen objects.

---

src/IB/IBFEMethod.cpp

interpWeighted is a relatively expensive function: in particular, if there are multiple parts, then a processor may have lots of quadrature points on one part and relatively few on another. We can improve throughput by putting all of the communication at the end.

Move VecAssemblyBegin calls into their own loop.

---

ibtk/include/ibtk/libmesh_utilities.h
ibtk/src/lagrangian/FEDataManager.cpp
include/ibamr/IBFEMethod.h
src/IB/IBFEMethod.cpp

This PR supersedes #430, which had a couple of bugs that changed the computed solution in parallel.

eliminate some calls to NumericVector<T>::close()

---

ibtk/include/ibtk/FECache.h
ibtk/src/lagrangian/FEDataManager.cpp

First part of #436: this lowers run time for my favorite example (IBFE/explicit/ex4) by about 10%. I suspect it will help more with more highly deformed meshes.

Add IBTK::FECache.

---

ibtk/include/ibtk/FECache.h
ibtk/include/ibtk/FEDataManager.h
ibtk/include/ibtk/FEMapCache.h
ibtk/include/ibtk/QuadratureCache.h
ibtk/src/lagrangian/FEDataManager.cpp

This is the last caching object that we can use. I am still running callgrind to see how much this saves us.
I want to add one more optimization: store a `quad_key_type` for each `Elem` during the first loop over elements in `interpWeighted` and `spread`. Since `quad_key_type` is just three integers this is not a lot of memory but it will save us a lot of repeated calculations. I'll try to add that later tonight or tomorrow (I have to be somewhere at 7).

Add quadrature cache

---

ibtk/include/ibtk/FEDataManager.h
ibtk/src/lagrangian/FEDataManager.cpp

Another spinoff of #396.
libMesh guarantees that each processor owns a contiguous range of dofs. Hence, when we repartition, the new dof numbering on each elem and node is unrelated to the old numbering, so all of this information is out of date.

Clear the system dof cache on partitioning.

---

ibtk/include/ibtk/BoxPartitioner.h
ibtk/include/ibtk/PartitioningBox.h
ibtk/include/ibtk/private/PartitioningBox-inl.h
ibtk/lib/Makefile.am
ibtk/lib/Makefile.in
ibtk/src/lagrangian/BoxPartitioner.cpp
ibtk/src/utilities/PartitioningBox.cpp

Another spinoff from #396.
This PR adds the actual partitioner class as well as a 'partitioning box' class. The former inherits from `libMesh::Partitioner` and implements all functionality necessary for integration with libMesh's partitioning code. The later is like a bounding box but uniquely chops up the domain with a tensor product of half-open intervals.
None of this code is actually used in the library at present: I will put up a PR for that once this, #462, and #461 are merged.

Partitioning 2c

---

ibtk/include/ibtk/FEDataManager.h
ibtk/src/lagrangian/FEDataManager.cpp
src/IB/IBFEMethod.cpp

Each IBFEMethod propagates its settings to the FEDataManagers it owns.
This is another spinoff of #396, and, like the last four PRs, does not do a lot but add functionality that will be used by the partitioning and load balancing functions.

Conditionally log FEDataManager's workload data.

---

ibtk/src/lagrangian/FEDataManager.cpp

These data structures contain information referring to the previous partitioning so they need to be rebuilt.
Since everything we clear is recreated on-demand there should not be any need to add more checks elsewhere regarding whether or not something is set up.
This is another spinoff of #396.

Clear stale data after repartitioning.

---

doc/news/changes/incompatibilities/20190213DavidWells
ibtk/include/ibtk/FEDataManager.h
ibtk/include/ibtk/HierarchyIntegrator.h
ibtk/include/ibtk/LDataManager.h
ibtk/include/ibtk/private/LDataManager-inl.h
ibtk/src/lagrangian/FEDataManager.cpp
ibtk/src/lagrangian/LDataManager.cpp
ibtk/src/utilities/HierarchyIntegrator.cpp
include/ibamr/IBFEMethod.h
include/ibamr/IBFESurfaceMethod.h
include/ibamr/IBHierarchyIntegrator.h
include/ibamr/IBMethod.h
include/ibamr/IBStrategy.h
include/ibamr/IBStrategySet.h
include/ibamr/IMPMethod.h
src/IB/IBFEMethod.cpp
src/IB/IBFESurfaceMethod.cpp
src/IB/IBHierarchyIntegrator.cpp
src/IB/IBMethod.cpp
src/IB/IBStrategy.cpp
src/IB/IBStrategySet.cpp
src/IB/IMPMethod.cpp

A (larger) spinoff from #396, with some more fixes.
This came out of a conversation I had with @boyceg this afternoon: we don't really have a consistent way of setting up workload estimates. However, most of the necessary infrastructure to do this is already there. The new version assumes that the parent hierarchy integrator (i.e., whatever we call `advanceHierarchy` on) 'owns' the workload estimate array. To estimate the work, it sets all cells to one and then asks each child integrator to add in its own contributions. Things like `IBFEMethod`, `LDataManager`, etc. do not need to know anything about load balancers or store the workload index (or even store a pointer to the hierarchy): they just add their contribution when asked via `addWorkloadEstimate`.
I am labeling this as 'do not …

Rearrange workload estimation

---

include/ibamr/IBFEMethod.h
include/ibamr/IBFESurfaceMethod.h
include/ibamr/IBMethod.h
include/ibamr/IBStrategy.h
include/ibamr/IBStrategySet.h
include/ibamr/IMPMethod.h
src/IB/IBFEMethod.cpp
src/IB/IBFESurfaceMethod.cpp
src/IB/IBHierarchyIntegrator.cpp
src/IB/IBMethod.cpp
src/IB/IBStrategy.cpp
src/IB/IBStrategySet.cpp
src/IB/IMPMethod.cpp

None of these objects should ever need to use the load balancer or workload index.
We need to take some care with how we notify `IBFEMethod` that workload estimates should be considered when repartitioning the libMesh data (i.e., using the SAMRAI based partitioner makes sense) but that process should be handled automatically. That will be in the main load balancer/partitioner PR.
Part of #396. Followup to #478.

Deprecate more old loadbalancer code.

---

ibtk/include/ibtk/FEDataManager.h
ibtk/src/lagrangian/FEDataInterpolation.cpp
ibtk/src/lagrangian/FEDataManager.cpp
src/IB/IBFEMethod.cpp
src/IB/IBFESurfaceMethod.cpp

Alternative to #468. 
This improves performance with a few changes:
1. Combining the calls to the cache so that only one lookup is done for each system on each cell (instead of each variable).
2. Avoid copying the dofs unless we need to apply constraints.
This lowers the amount of time we spend looking up dof indices by about 75%. Its essentially the same technique as #468 but just returns all variables at once, which we should do anyway; we always need, e.g., all NDIM sets of X dofs.
I left the old lookup function in place so any user code that uses the lookup by variable and copying should still work.

Improve the performance of SystemDofMapCache.

---

examples/IBFE/explicit/ex4/example.cpp
ibtk/include/ibtk/HierarchyIntegrator.h
ibtk/src/lagrangian/FEDataManager.cpp
ibtk/src/utilities/HierarchyIntegrator.cpp
include/ibamr/IBFEMethod.h
include/ibamr/ibamr_enums.h
src/IB/IBFEMethod.cpp
src/IB/IBHierarchyIntegrator.cpp

This is the last partitioning change :tada: 
I want to run some more tests before we merge this, so I am marking it as a work in progress for now.
@cpuelz If you want to give this a spin with the heart model, use this branch and attach the load balancer to the time integrator. Look at how I modified example 4 to see how this is done. You can check the logs to see how it repartitions:
```
workload estimate on processor 0  = 136880 (pid is 19028)
workload estimate on processor 1  = 124576 (pid is 19029)
workload estimate on processor 2  = 126832 (pid is 19030)
workload estimate on processor 3  = 156626 (pid is 19031)
workload estimate on processor 4  = 124834 (pid is 19032)
workload estimate on processor 5  = 143008 (pid is 19033)
workload estimate on processor 6  = 133872 (pid is 19034) …
```

Partitioning 2g

---

include/ibamr/IBFEInstrumentPanel.h

We need to delete the meshes after the systems since the systems store pointers to the meshes.
This fixes some crashes at the end of a run for me.

Fix deletion order for some libMesh objects.

---

ibtk/src/lagrangian/BoxPartitioner.cpp

The function `Mesh::is_replicated` was only added in 1.2, so lets just skip the check for older versions.

Fix compatibility with libMesh 1.1.

---

configure
doc/news/changes/minor/20190221DavidWells
ibtk/configure
ibtk/m4/configure_libmesh.m4
m4/configure_libmesh.m4

This adds some comments that make it easier to read the m4 and adds another check to verify that libMesh was compiled with support for PETSc. It also fixes a silly error where I state that we require libMesh 1.1 but the code checks for libMesh 1.2.
Fixes #435.

Clean up the libMesh detection scripts a bit.

---

ibtk/src/utilities/AppInitializer.cpp

I noticed this when writing a unit test for some of our libMesh code.

Fix bug with empty string.

---

ibtk/src/lagrangian/BoxPartitioner.cpp

Fix a signed integer comparison warning.

---

src/IB/IBFEInstrumentPanel.cpp

This was deprecated in 1.4, not 1.3. See also #500.

Fix the previous patch.

---

ibtk/include/ibtk/FEDataManager.h
ibtk/include/ibtk/libmesh_utilities.h
ibtk/src/lagrangian/FEDataManager.cpp
include/ibamr/IBFEPostProcessor.h
src/IB/IBFEInstrumentPanel.cpp
src/IB/IBFEMethod.cpp

We use a lot of deprecated libMesh functions. I went through and got rid of everything that is deprecated as of 1.4.0 where possible: in one case I had to use the preprocessor to keep compatibility with 1.1.0. This stops a lot of annoying warnings.
Since we require 1.1.0 or newer this shouldn't break anything.
Candidate for inclusion in 0.4; see #424.

Update deprecated lib mesh

---

ibtk/include/ibtk/libmesh_utilities.h
ibtk/src/lagrangian/FEDataManager.cpp

I wrote this patch while testing out some new parts of the test runner. In fact, #494 already includes a test for this change to verify that the new algorithm doesn't change the computed edge length.
This function takes up roughly 4% of our total run time in the heart model: these changes lower, in valgrind, the total number of cycles spent in this function from 262 billion to 30 billion (and total time down to 0.46%).

Improve max elem edge length

---

ibtk/include/ibtk/FEDataManager.h
ibtk/src/lagrangian/FEDataManager.cpp
include/ibamr/IBFEMethod.h
src/IB/IBFEMethod.cpp

The current strategy, based on FEDataManager::buildIBGhostedVector, stores a vector inside FEDataManager and a pointer to that vector inside IBFEMethod. This commit changes the way we do things so that the vectors are actually owned by IBFEMethod itself.
This change is necessary since some components require ghosted RHS vectors and others require ghosted solution vectors: it is easiest to simply keep cloning these things whenever we need them instead of worrying about how we should interpret the vector owned by FEDataManager.
While we are here: set up the projected velocity RHS vector with IB ghosted entries. This changes nothing at the moment but is needed in a future PR.
Part of #492.

Change the way we set up IB ghosted vectors.

---

doc/news/changes/incompatibilities/20180412DavidWells
ibtk/src/lagrangian/FEDataManager.cpp
src/IB/IBFEMethod.cpp

This was a bad idea since it makes the log output unreproducible. I doubt anyone but me ever looked at this so I think its okay to remove this misfeature from the logs.
Part of #494.

Disable PID printing.

---

doc/news/changes/minor/20191304DavidWells
ibtk/include/ibtk/HierarchyIntegrator.h
ibtk/src/utilities/HierarchyIntegrator.cpp
src/adv_diff/AdvDiffPredictorCorrectorHierarchyIntegrator.cpp
src/adv_diff/AdvDiffSemiImplicitHierarchyIntegrator.cpp
src/navier_stokes/INSCollocatedHierarchyIntegrator.cpp
src/navier_stokes/INSStaggeredHierarchyIntegrator.cpp
src/navier_stokes/INSVCStaggeredConservativeHierarchyIntegrator.cpp
src/navier_stokes/INSVCStaggeredNonConservativeHierarchyIntegrator.cpp

I think this is the last prerequisite patch for the test suite.
The number of solver iterations is not stable in the sense that small perturbations (the way a vector is aligned, order of operations in floating point, etc.) can change it by O(1), e.g., some solvers in the test suite take 6 iterations 90% of the time and 7 iterations 10% of the time. The best way to fix this is to simply not log the number of solver iterations.
This PR adds a new boolean that controls this. The default is to simply copy the value

Conditionally disable logging of solver iterations.

---

src/IB/IBFEInstrumentPanel.cpp

This change to the libMesh API did not occur until version 1.4.

Fix compatibility with libMesh 1.3.x. (0.4.1)

---

scripts/misc_cpp11_updates.pl

This updates the script that replaces `UniquePtr` with `unique_ptr` to also replace `boost::array` with `std::array`. @drwells Are there any other simple changes like this that would be useful to include?
@AminKolah You can use this script to do some of the dull search and replaces on #240.

Updates to a c++11 update script.

---

doc/news/changes/incompatibilities/20190416DavidWells
doc/news/changes/minor/20190415DavidWells
ibtk/include/ibtk/HierarchyIntegrator.h
ibtk/src/utilities/HierarchyIntegrator.cpp
include/ibamr/IBHierarchyIntegrator.h
include/ibamr/INSCollocatedHierarchyIntegrator.h
include/ibamr/INSHierarchyIntegrator.h
include/ibamr/INSStaggeredHierarchyIntegrator.h
include/ibamr/INSVCStaggeredConservativeHierarchyIntegrator.h
include/ibamr/INSVCStaggeredHierarchyIntegrator.h
include/ibamr/INSVCStaggeredNonConservativeHierarchyIntegrator.h
src/IB/IBHierarchyIntegrator.cpp
src/navier_stokes/INSCollocatedHierarchyIntegrator.cpp
src/navier_stokes/INSStaggeredHierarchyIntegrator.cpp
src/navier_stokes/INSVCStaggeredConservativeHierarchyIntegrator.cpp
src/navier_stokes/INSVCStaggeredHierarchyIntegrator.cpp
src/navier_stokes/INSVCStaggeredNonConservativeHierarchyIntegrator.cpp

`IBTK::HierarchyIntegrator::regridHierarchy` currently calls both `initializeCompositeHierarchyDataSpecialized` and `synchronizeHierarchyDataSpecialized` on itself and all child integrators. However, No class actually implements a nonempty `synchronizeHierarchyDataSpecialized` method aside from `IBTK::HierarchyIntegrator`, and putting everything in a routine named `initialize` is confusing. Hence I added (I am not in love with the names) `regridHierarchyBeginSpecialized` and `regridHierarchyEndSpecialized` which are called immediately before and after we do the actual regridding inside SAMRAI.
From the discussion in #343: I am now convinced that this is the correct way to handle this since a lot of classes need to do stuff immediately before or after regridding and there is no way to do …

Move regrid hierarchy calls

---

ibtk/src/lagrangian/FEDataManager.cpp

This eliminates some comparisons between `int`s and `unsigned int`s in the new templated functions in `FEDataManager`.
I just changed everything to `int`, which I think should be fine in the current context of use.

eliminate comparisons between signed and unsigned ints

---

ibtk/src/lagrangian/FEDataManager.cpp

With apologies to @cpuelz.
Using biquadratic elements in 2D revealed a bug and a problem:
1. We do a run-time calculation of the number of variables incorrectly (we should use the second entry in the shape array)
2. We should provide instantiations for biquadratic elements since we use them in the examples.
This PR fixes the bug (sorry) and also adds instantiations so we can get a nice speed-up for biquadratic elements too.

Fix template bounds

---

tests/IBFE/Makefile.am
tests/IBFE/Makefile.in
tests/IBTK/Makefile.am
tests/IBTK/Makefile.in

Its not necessary to create a symbolic link and doesn't work on macs.
Some context: some tests use identical input files aside from the mpirun directive. Its a little better to dereference the symbolic link (instead of having a link to a link) but not necessary.

Don't use -L with ln.

---

scripts/project_templates/sublime/ibamr.sublime-project.template

These settings tell `cppcheck` to assume that header (`.h`) files are in C++ and not C.

update Sublime project template

---

src/IB/IBHydrodynamicSurfaceForceEvaluator.cpp

Fix for the issue in #550: we were removing patch data that was not allocated which causes SAMRAI to segfault, even in debug mode.
I am writing up some notes on how to debug things with valgrind (and other tools) with MPI so that everyone can learn the tricks that I just learned.

Do not remove an unused patch data index.

---

include/ibamr/StaggeredStokesSolver.h
src/navier_stokes/StaggeredStokesSolver.cpp

The type of these objects is not dynamic, so we might as well just use values and delete the destructor.

Remove some unnecessary pointers.

---

include/ibamr/IBFEMethod.h
src/IB/IBFEMethod.cpp
tests/IBFE/interpolate_velocity_01.d.cached.mpirun=4.input
tests/IBFE/interpolate_velocity_01.d.cached.mpirun=4.output
tests/IBFE/interpolate_velocity_01.d.ghosted.mpirun=4.input
tests/IBFE/interpolate_velocity_01.d.ghosted.mpirun=4.output

This allows us to switch back to the old VecCache based implementation.
I added two tests where we explicitly use one option or the other when setting up IBFEMethod. They both work.
Part of #492.

Add a switch for the vector type for U's RHS.

---

ibtk/include/ibtk/HierarchyGhostCellInterpolation.h

Follow up from #570. I needed to add in `#include <memory>` to get IBAMR to compile with certain older compilers (gcc 4.8.4 in particular).

Added memory header file.

---

examples/IBFE/explicit/ex10/example.cpp
examples/IBFE/explicit/ex11/example.cpp
examples/IBFE/explicit/ex2/example.cpp
examples/IBFE/explicit/ex3/example.cpp
examples/IBFE/explicit/ex4/example.cpp
examples/IBFE/explicit/ex5/example.cpp
examples/IBFE/explicit/ex9/example.cpp
examples/IMP/explicit/ex0/main.cpp
src/IB/IBFEPatchRecoveryPostProcessor.cpp
tests/IBFE/explicit_ex4.cpp

This may break compatibility with some older versions of libMesh, but seems to be needed to avoid configuring libMesh `master` with `--enable-deprecated`.

remove some deprecated libMesh functions

---

tests/multiphase_flow/free_falling_cyl_cib.cpp
tests/multiphase_flow/rotating_barge_cib.cpp

From a comment in #588: the current version works (perhaps by coincidence) but we should make it explicit.

Guard writing to input files with a rank check.

---

ibtk/include/ibtk/FEDataManager.h
ibtk/src/lagrangian/FEDataManager.cpp
src/IB/IBFEMethod.cpp

Followup to #419, though this is a lot easier now since we merged a lot of stuff in the mean time. Part of #492.
This actually passes the test suite (!) but I still need to convince myself that this is the right way to do it.

Assemble into ghost regions in interpWeighted.

---

tests/IBTK/ldata_01.cpp

For some reason mpich was okay with omitting this so I did not catch it before.

Add a missing call to PetscFinalize().

---

ibtk/m4/configure_petsc.m4

This was somehow omitted from #601. I am not sure how we managed to configure IBTK given this problem.

Add a missing symbolic link.

---

tests/IBFE/interpolate_velocity_01.b.bspline-3.input
tests/IBFE/interpolate_velocity_01.b.bspline-3.output
tests/IBFE/interpolate_velocity_01.b.bspline-4.input
tests/IBFE/interpolate_velocity_01.b.bspline-4.output
tests/IBFE/interpolate_velocity_01.b.bspline-5.input
tests/IBFE/interpolate_velocity_01.b.bspline-5.output
tests/IBFE/interpolate_velocity_01.b.bspline-6.input
tests/IBFE/interpolate_velocity_01.b.bspline-6.output
tests/IBFE/interpolate_velocity_01.b.ib-3.input
tests/IBFE/interpolate_velocity_01.b.ib-3.output
tests/IBFE/interpolate_velocity_01.b.piecewise-cubic.input
tests/IBFE/interpolate_velocity_01.b.piecewise-cubic.output
tests/IBFE/interpolate_velocity_01.cpp

These explicitly use different interpolation kernels. The error is about equal to other interpolation results at the same grid resolution.
After several missteps I found a way to finally improve the performance of these FORTRAN kernels, but we should add tests first to guarantee I didn't break anything.

Add more interpolation tests.

---

ibtk/src/lagrangian/fortran/lagrangian_delta.f.m4
ibtk/src/lagrangian/fortran/lagrangian_interaction2d.f.m4
ibtk/src/lagrangian/fortran/lagrangian_interaction3d.f.m4

This can be better inlined by the compiler: callgrind reports that we use about 10% less instructions in the IB kernels with this switch. More precisely: since `lagrangian_floor` is `EXTERNAL` *and* in another translation unit the compiler cannot optimize it without something very fancy like `-fwhole-program` or link-time optimization.
One minor change in this patch is that `lagrangian_floor(-42)` is `-43` while `floor(-42)` is `-42`. I don't think this is a big deal since we are `floor`ing structure coordinates which are not going to end up at integer multiples of `dx` anyway.

Use F95's FLOOR instead of lagrangian_floor.

---

configure
configure.ac
ibtk/configure
ibtk/configure.ac

Fixes #591.
We set 'NDEBUG' when SAMRAI is in release mode: hence, for compatibility with libMesh, we have to make sure libMesh is in opt or devel mode in this case so that NDEBUG is consistently defined.

Verify consistent debug settings.

---

ibtk/src/lagrangian/fortran/lagrangian_interaction2d.f.m4
ibtk/src/lagrangian/fortran/lagrangian_interaction3d.f.m4

This lowers the cost of these corners (by counting instructions in callgrind) by about 25%.

Add unrolled variants of some kernels

---

ibtk/include/ibtk/ibtk_macros.h

Clang needs the flag '-Wunknown-warning-option' to be happy with this macro.

Get rid of warnings in clang.

---

doc/news/changes/minor/20181210AmneetBhalla
src/IB/CIBFEMethod.cpp
src/IB/CIBMethod.cpp
src/IB/IBFEDirectForcingKinematics.cpp

This was done on the NWT branch, though its a bug in IBAMR. In Eigen, `Quaterniond::normalize()` normalizes the quaternion, while `Quaterniond::normalized()` copies the current object and normalizes the copy.
I searched through the rest of the library to make sure that we always do this correctly.

NWT: correctly normalize quaternions.

---

configure
configure.ac
ibtk/configure
ibtk/configure.ac

The test suite doesn't work without libMesh (though we can compile and run a subset of tests), but I am willing to let that pass for now.

Fix compilation without libMesh.

---

tests/IBFE/interpolate_velocity_01.cpp
tests/IBFE/interpolate_velocity_01_2d.a.mpirun=4.output
tests/IBFE/interpolate_velocity_01_2d.b.mpirun=4.output
tests/IBFE/interpolate_velocity_01_2d.c.mpirun=4.output
tests/IBFE/interpolate_velocity_01_2d.d.mpirun=4.output
tests/IBFE/interpolate_velocity_01_3d.a.mpirun=4.output
tests/IBFE/interpolate_velocity_01_3d.b.mpirun=4.output
tests/IBFE/interpolate_velocity_01_3d.c.mpirun=4.output

The default partitioner for libMesh, metis, does a good job, but the way it is seeded changed in libMesh 1.4.0: i.e., we get different partitionings with different versions of libMesh. This results in (for reasons I don't fully understand) slightly different solutions to the velocity projection problem.
Get around the issue by using libMesh's linear partitioner, which is much more consistent than metis (and always available).
Fixes #636. I don't like that we can get different answers with different partitioners but this gives us the same numbers across different libMesh versions.

Use a more stable partitioner.

---

ibtk/include/ibtk/ibtk_macros.h

This one shows up in the multi_array header.

Suppress another boost warning.

---

tests/IBTK/Makefile.am
tests/IBTK/Makefile.in

This was caught by @abarret. Fortunately, since the test doesn't use SAMRAI and dimensionality is a run-time parameter for libMesh, the error is harmless.

Fix elem_hmax_02's link libraries.

---

ibtk/include/ibtk/ibtk_macros.h

Implicitly-generated copy constructors where, in some circumstances, deprecated in C++11, but we are a long way from this being actually removed from C++.
Lets put this in 0.5 and then get ready to tag a release.

Suppress a new GCC warning.

---

doc/news/changes/minor/20190730AaronBarrett
src/adv_diff/AdvDiffSemiImplicitHierarchyIntegrator.cpp

This removes the solve in `AdvDiffSemiImplicitHierarchyIntegrator` if the diffusion coefficient is zero. This does not change the error norms for the examples. Fixes #573.

Removed solve for advection diffusion solver with zero diffusion coefficient

---

ibtk/include/ibtk/libmesh_utilities.h

We only really require that X_node have NDIM columns. This should make the code work correctly for surface meshes in debug mode.
I thought we had fixed this, but alas, we did not. Caught by @xxjaehoxx.

Fix some code to work with surface meshes.

---

ibtk/include/ibtk/CartExtrapPhysBdryOp.h
ibtk/src/boundary/physical_boundary/CartExtrapPhysBdryOp.cpp

Part of #649. This fixes the quadratic extrapolation at codim 1 boundaries. There was a missing minus sign.
This does not fix the problem at other types of boundaries, i.e. corner boundaries in two spatial dimensions. Since our quadratic interpolation is dimension by dimension, we do not match _all_ quadratic functions. Currently, the code reduces to linear interpolation in these cases. I updated the header file to clarify this. I also fixed some other random spacing inconsistencies in the header.

Fix quadratic extrapolation.

---

ibtk/include/ibtk/libmesh_utilities.h

Some versions of GCC complain about U_node.shape()[0] being uninitialized. There is nothing we can do about it in this function so ignore the warning.

Silence a bogus boost warning.

---

ibtk/include/ibtk/FEDataManager.h
ibtk/src/lagrangian/FEDataManager.cpp

Part of #647: as discussed in that issue, we should split FEDataManager into two parts: something that keeps track of all the libMesh objects and something (building on top of the first) that keeps track of the parts dependent on the Eulerian grid.
This PR just moves all of the libMesh data structures that do not need to know anything about Eulerian data (the IB-ghosted vectors are still in FEDataManager) into a new base class `FEData`. I am not in love with the name but it works.

Refactor fe data manager 1

---

scripts/setup_compile_commands.sh

Set a specific C++ compiler to make it easier to get `clangd` to work with the generated `compile_commands.json`.

update setup_compile_commands.sh to set specific compiler

---

ibtk/contrib/muparser/include/muParserBytecode.h
ibtk/contrib/muparser/src/muParserBase.cpp
ibtk/contrib/muparser/src/muParserBytecode.cpp

Clang rightfully complains that anonymous types declared in an anonymous union is an extension, so name the union.
Fixes #676.

Silence a muParser warning.

---

ibtk/include/ibtk/FEDataManager.h
ibtk/src/lagrangian/FEDataManager.cpp

This is necessary for some upcoming work that will require multiple `FEDataManager` objects to use the same Lagrangian data but different Eulerian data: i.e., multiple `FEDataManager` objects will share the same `FEData` object. In particular: both `IBFEPostProcessor` and `IBFEMethod` need to do some Lagrangian-Eulerian interaction, but really need different `FEDataManager` objects since the former should use the immediately available hierarchy and the later should use the scratch hierarchy.
Part of #647.

Make FEDataManager no longer inherit from FEData.

---

doc/news/changes/major/20190919BoyceGriffith
ibtk/src/lagrangian/LDataManager.cpp

This should fix the issue @jabrown893 was encountering, in which he "inactivated" a structure but it still applied forces.

zero IB forces in the right place

---

doc/release-tasks.md

#686 demonstrates that we need to do a better job testing releases: all of the machines I run on have a system copy of HDF5 (or I compile PETSc with HDF5 support), which caused me to miss this configuration bug. To get around this I wrote up a checklist for putting out a release inspired by
https://github.com/dealii/release-papers/blob/master/release-tasks
which will remind us to actually check this configuration at release time.

Add a document describing the release process.

---

configure
doc/news/changes/minor/20190920DavidWells
ibtk/configure
m4/configure_hdf5.m4
m4/configure_hypre.m4
m4/configure_petsc.m4
m4/configure_silo.m4

Fixes #686. I need to do some more tests before we merge but this appears to add the correct linker flags. @jabrown893 if you have some time it would help a lot if you could run this on longleaf.
We should not have the -L prefix here, so we should pass the directory instead.

Fix a path fed to rpath.

---

doc/news/changes/incompatibilities/20190916DavidWells
ibtk/include/ibtk/FECache.h
ibtk/src/lagrangian/FEDataManager.cpp

Most of the fix for #675: we should now reinitialize the FE objects correctly with subdivision elements inside FEDataManager.
@xxjaehoxx I don't actually have any test code for subdivision elements but we should add some to this PR. Do you have the L2 projection code done? If so, send it to me and I will modify it to use `FECache` to check that our implementation actually works.

Redo fe cache

---

ibtk/src/math/PETScMatUtilities.cpp

This is something I noticed with @jabrown893 yesterday.

Silence a warning from Intel's compiler.

---

tests/IBFE/explicit_ex4.cpp
tests/IBFE/explicit_ex4_2d.postprocessor.input
tests/IBFE/explicit_ex4_2d.postprocessor.output

Part of #654: we need to be able to test the postprocessor before we can implement the 'use multiple `FEDataManager`s' logic.
This PR just adds one new test for the postprocessor: I will add more tests once we can use multiple `FEDataManager`s with the same Lagrangian data.

Add test for IBFECentroidPostProcessor.

---

attest

attest: allow -j (without a number) for all cores.

---

ibtk/include/ibtk/FEDataManager.h

Also taken from #654.
This will make more sense later when we also include nodal weights.

Change the default q point weight to 1.0.

---

ibtk/include/ibtk/FEDataManager.h
ibtk/src/lagrangian/FEDataManager.cpp
tests/IBFE/explicit_ex4.cpp
tests/IBFE/explicit_ex4_2d.a.postprocessor.input
tests/IBFE/explicit_ex4_2d.a.postprocessor.output

Part of #647: we can now successfully create `IBFECentroidPostProcessor`s that use an `FEDataManager` object that is external to `IBFEMethod`. While this itself is a bit clumsy, it verifies that the planned approach (`IBFEMethod` maintaining two different sets of `FEDataManager`s with different Eulerian partitionings) will work.

Allow FEDataManagers to share one FEData object.

---

ibtk/src/lagrangian/FEDataManager.cpp

Peeled off from #654.
These pointers have to point to the same patch hierarchy so explicitly assert it.

Add a pointer check to FEDataManager.

---

doc/news/changes/minor/20190919DavidWells
doc/news/changes/minor/20190920DavidWells
examples/ConstraintIB/flow_past_cylinder_HF/HydroForceEval.cpp
ibtk/src/utilities/LMarkerUtilities.cpp
include/ibamr/IBStandardInitializer.h
src/IB/CIBMethod.cpp
src/IB/IBStandardInitializer.cpp

Ensure that we actually opened the file in all cases.
Fixes #413 and #643.

Consistently check ifstream states.

---

ibtk/include/ibtk/FEDataManager.h
ibtk/include/ibtk/libmesh_utilities.h
ibtk/src/lagrangian/FEDataManager.cpp
ibtk/src/utilities/libmesh_utilities.cpp

Part of #715: the relationship between IBFEMethod and FEDataManager is overly complicated. Fortunately, a lot of the stuff FEDataManager does that is required by IBFEMethod doesn't really depend on FEDataManager at all - just on the Lagrangian data.
This function, and several functions that call it, do not need to be member functions.

Refactor computeActiveElementBoundingBoxes.

---

include/ibamr/IBFEMethod.h
src/IB/CIBFEMethod.cpp
src/IB/IBFEMethod.cpp

IBFEMethod will need to, in the future, handle multiple FEDataManagers which are associated with different patch hierarchies. This patch adds support for multiple FEDataManager sets: future work will actually turn the scratch hierarchy on.
This patch doesn't really do anything: the default and only choice is to use the 'primary' FEDataManager, which is associated with the main patch hierarchy.

Rearrange things to permit the scratch hierarchy.

---

ibtk/include/ibtk/FEDataManager.h
ibtk/src/lagrangian/FEDataManager.cpp
include/ibamr/IBFEMethod.h
include/ibamr/IBFESurfaceMethod.h
src/IB/IBFEMethod.cpp
src/IB/IBFESurfaceMethod.cpp

Allow callers to share one (or more) `SAMRAIDataCache` objects between multiple `FEDataManager`s.

reuse SAMRAIDataCache objects between FEDataManager instances

---

include/ibamr/AdvDiffHierarchyIntegrator.h
include/ibamr/AdvDiffSemiImplicitHierarchyIntegrator.h
src/adv_diff/AdvDiffHierarchyIntegrator.cpp
src/adv_diff/AdvDiffSemiImplicitHierarchyIntegrator.cpp

This adds an optional argument when registering variables with the advection diffusion integrators to turn off drawing of the variables.

Add optional argument to not draw convected quantities or source terms

---

doc/news/changes/incompatibilities/20190710DavidWells
doc/news/changes/major/20191031DavidWells
doc/news/changes/minor/20191104DavidWells
ibtk/include/ibtk/FEDataManager.h
ibtk/src/lagrangian/FEDataManager.cpp
include/ibamr/IBFEMethod.h
src/IB/IBFEMethod.cpp
src/IB/IBFESurfaceMethod.cpp
tests/IBFE/explicit_ex4_2d.postprocessor.scratch_hier.mpirun=4.input
tests/IBFE/explicit_ex4_2d.postprocessor.scratch_hier.mpirun=4.output
tests/IBFE/explicit_ex4_3d.scratch_hier.mpirun=4.input
tests/IBFE/explicit_ex4_3d.scratch_hier.mpirun=4.output
tests/IBFE/explicit_ex8_2d.scratch_hier.input
tests/IBFE/explicit_ex8_2d.scratch_hier.mpirun=4.input
tests/IBFE/explicit_ex8_2d.scratch_hier.mpirun=4.output
tests/IBFE/explicit_ex8_2d.scratch_hier.output

Super WIP (the history is presently nonsense) but I figured I would put this up to show what I have been up to for the last two weeks.
@boyceg and I discussed dealing with load imbalancing with IBFE at a previous group meeting. We came to the conclusion that the best way to do this would be to use a 'scratch hierarchy' whose patches are partitioned by the number of interaction (quadrature) points, rather than the number of (Eulerian) cells.
We can now do this! I am working on some scaling experiments now, but the tentative results look great: all processors have, within about 0.1%, the same number of quadrature points on the scratch hierarchy and (I didn't count them explicitly) an approximately equal number of Eulerian cells on the real hierarchy.
There are a number of problems with the …

Add ib interaction hierarchy

---

doc/release-tasks.md
ibtk/src/utilities/libmesh_utilities.cpp

This is expensive with libMesh: it currently occupies about half the run time of IBTK::get_global_active_element_bounding_boxes.
I checked and we do this correctly everywhere else.

Avoid calculating an end iterator in a loop.

---

ibtk/src/lagrangian/LDataManager.cpp
src/IB/CIBMethod.cpp
src/IB/ConstraintIBMethod.cpp
src/IB/IBFEDirectForcingKinematics.cpp
src/IB/IBFESurfaceMethod.cpp
src/IB/IBHydrodynamicSurfaceForceEvaluator.cpp

This avoids some confusion where we are using 3D arrays in 2D; i.e., `NDIM` is wrong. I made this mistake back in #607.

Use array sizes for reductions.

---

doc/news/changes/minor/20191112AaronBarrett
src/navier_stokes/INSHierarchyIntegrator.cpp

Previously, `INSHierarchyIntegrator` would overwrite previously registered forcing functions despite claiming to evaluate them in registered order. This fixes that issue. This also addresses the problems raised in #747.

Multiple body force functions can be registered with INS integrators.

---

Makefile.am
Makefile.in
attest

A minor new feature for `attest`: `attest -E regex` will skip tests whose name matches `regex`.
@abarret This is the patch I mentioned a day or two ago.

Add an excluding regex option to attest.

---

attest

This leads to catastrophically bad performance since we expect all parallelization to be done with MPI in IBAMR.
This is largely necessary for hypre, which will try to parallelize itself with OpenMP when it is configured to do so (which happens to be the default on my desktop).

Disable OpenMP threading in the test suite.

---

ibtk/include/ibtk/libmesh_utilities.h
ibtk/src/lagrangian/FEDataManager.cpp
ibtk/src/utilities/libmesh_utilities.cpp

`libMesh::BoundingBox` was `libMesh::MeshTools::BoundingBox` until 1.2.0.

Fix compatibility with libMesh 1.1.0.

---

CONTRIBUTING.md

This document clarifies what expectations we have for copyrights. Fixes #604.

Add the developer certificate of origin.

---

Makefile.in
config/IBAMR_config.h.tmp.in
configure
doc/news/changes/minor/20191119AaronBarrett
ibtk/Makefile.in
ibtk/config/IBTK_config.h.tmp.in
ibtk/configure
ibtk/m4/configure_boost.m4
m4/configure_boost.m4
m4/configure_libmesh.m4

Currently, IBAMR _must_ be compiled with an external boost if libMesh is present. This allows IBAMR to use the bundled boost if libMesh is configured without boost support.
@drwells, I'm not very familiar with the buildsystem. Can you double check this?

Allow IBAMR to be built with bundled boost when libMesh is enabled with no boost support.

---

doc/release-tasks.md

At some point we should add this task to a linter CI job, but for now it suffices to spend a few minutes before each release checking.

Add another release task

---

.clang-format
ibtk/include/ibtk/CCPoissonHypreLevelSolver.h
ibtk/include/ibtk/SCPoissonHypreLevelSolver.h
ibtk/include/ibtk/ibtk_macros.h
ibtk/src/solvers/impls/CCPoissonHypreLevelSolver.cpp
ibtk/src/solvers/impls/SCPoissonHypreLevelSolver.cpp

These are new in hypre 2.18 (or some other recent release) that added some CUDA functions that we don't use.

Get rid of some warnings from hypre headers.

---

src/wave_generation/WaveDampingFunctions.cpp
src/wave_generation/WaveGenerationFunctions.cpp

Part of #749. Also found by cppcheck.
@amneetb this should make the wave calculations ever so slightly better :)

Use std::expm1 where appropriate.

---

ibtk/src/solvers/impls/CCPoissonLevelRelaxationFACOperator.cpp
ibtk/src/solvers/impls/CCPoissonPointRelaxationFACOperator.cpp
ibtk/src/solvers/impls/SCPoissonPointRelaxationFACOperator.cpp
ibtk/src/solvers/impls/VCSCViscousOpPointRelaxationFACOperator.cpp
src/IB/CIBMethod.cpp
src/IB/ConstraintIBMethod.cpp
src/IB/GeneralizedIBMethod.cpp
src/IB/IBFEInstrumentPanel.cpp
src/IB/IBHydrodynamicSurfaceForceEvaluator.cpp
src/IB/IBImplicitStaggeredHierarchyIntegrator.cpp
src/IB/IBInterpolantMethod.cpp
src/IB/IBRedundantInitializer.cpp
src/IB/IBStandardForceGen.cpp
src/IB/IMPInitializer.cpp
src/IB/IMPMethod.cpp
src/complex_fluids/CFGiesekusRelaxation.cpp
src/complex_fluids/CFINSForcing.cpp
src/complex_fluids/CFOldroydBRelaxation.cpp
src/navier_stokes/INSCollocatedHierarchyIntegrator.cpp
src/navier_stokes/INSVCStaggeredNonConservativeHierarchyIntegrator.cpp
src/navier_stokes/StaggeredStokesBlockFactorizationPreconditioner.cpp
src/navier_stokes/StaggeredStokesFACPreconditionerStrategy.cpp
src/wave_generation/IrregularWaveBcCoef.cpp
src/wave_generation/StokesFirstOrderWaveBcCoef.cpp
src/wave_generation/StokesSecondOrderWaveBcCoef.cpp

Found by cppcheck. Part of #749 
I am not going to fix everything cppcheck found: some of the issues, e.g., use of virtual functions in ctors and dtors, require care. I am going to put up patches with some of the really obvious fixes (like this).

Remove some unused variables.

---

ibtk/src/lagrangian/FEDataManager.cpp

This function was renamed and deprecated in libMesh 1.2.

Fix compilation with libMesh 1.1.

---

ibtk/lib/Makefile.am
ibtk/lib/Makefile.in

This isn't too important, but to keep people's build scripts happy we need something in `libIBTK.a` and I have another upcoming patch that will remove `lagrangian_delta.f` from this list.

Cleanup libIBTK

---

Makefile.in
doc/news/changes/minor/2020121DavidWells
ibtk/Makefile.in
ibtk/lib/Makefile.am
ibtk/lib/Makefile.in
ibtk/src/lagrangian/fortran/Makefile.am
ibtk/src/lagrangian/fortran/Makefile.in
ibtk/src/lagrangian/fortran/lagrangian_delta.f.m4
ibtk/src/lagrangian/fortran/lagrangian_interaction2d.f.m4
ibtk/src/lagrangian/fortran/lagrangian_interaction3d.f.m4

This makes the 3D BSPLINE_3 kernels for both interpolation and spreading take about 15% less time since the delta functions are inlined.
autotools doesn't generate dependency information for Fortran - AFAICT it cannot correctly track the file dependency created by the `include` statement. Hence we have to manually specify this dependency in the Makefile.

Combine some translation units to improve inlining.

---

doc/release-tasks.md
ibtk/include/ibtk/libmesh_utilities.h
ibtk/src/lagrangian/FEDataManager.cpp
ibtk/src/lagrangian/JacobianCalculator.cpp
src/IB/IBFEInstrumentPanel.cpp
tests/IBTK/bounding_boxes_01.cpp

The version checks in FEDataManager are wrong - they use `LIBMESH_MAJOR_VERSION` twice. Ooops :)
Fix the problem more permanently by using the convenience macro provided by libMesh for doing version checks.

Fix a libMesh version check and clean up the rest.

---

tests/IBTK/box_utilities_01.cpp

Another silly mistake from #832 - I messed up implementing part of a test. The test still passes but it was skipping a check.
check_box_contained returns a boolean - it should always return true in this case since every box in the input list should be contained by a box in the output list.

Fix a check in a test.

---

ibtk/include/ibtk/HierarchyIntegrator.h
include/ibamr/IBStrategy.h

I merged #849 without actually running the CI - the result was that we broke something with clang. Fortunately this is straightforward to fix - we just need some real definitions for `std::unique_ptr` instead of forward declarations.

Fix compilation with clang.

---

tests/Makefile.am
tests/Makefile.in

This was incorrectly changed in 401cdec3fe8 - I deleted this directory while testing something else and forgot to include it back.

Fix test compilation.

---

include/ibamr/IBFEMethod.h
src/IB/IBFEMethod.cpp
tests/IBFE/explicit_ex4_2d.scratch_hier.restart=25.mpirun=4.input
tests/IBFE/explicit_ex4_2d.scratch_hier.restart=25.mpirun=4.output

A bug in SAMRAI prevents the usage of GriddingAlgorithm objects that do not correspond to a restart database entry (i.e., one cannot dynamically create GriddingAlgorithm objects in a restarted simulation). Get around this by setting up the GriddingAlgorithm object and friends in the constructor of IBFEMethod so that they are always available.
@marshallrdavey this fixes the problem you pointed out to me earlier. It turns out that we don't have any tests for restarts with the scratch hierarchy - we now do.

Fix restarts on the scratch hierarchy.

---

attest

This fixes a python bug where `bool(conf['keep_work_directories'])` would always evaluate to `True` since the truth-value of `"False"` is `True` (its not an empty string).

Correctly delete test working directories.

---

ibtk/include/ibtk/FEDataManager.h
ibtk/src/lagrangian/FEDataManager.cpp

These do not copy data - a nice feature for IBFEMethod, which will copy data on its own anyway.
This is the FEDataManager part of #737. Once this and #857 are merged we can go ahead and use the new functions from this PR (which require a scratch index) directly, which will finish #737.

Add more overloads of FEDataManager::spread().

---

ibtk/include/ibtk/BoxPartitioner.h
ibtk/include/ibtk/FEDataInterpolation.h
ibtk/include/ibtk/FEDataManager.h
ibtk/include/ibtk/HierarchyIntegrator.h
ibtk/include/ibtk/LaplaceOperator.h
ibtk/include/ibtk/PoissonFACPreconditionerStrategy.h
ibtk/include/ibtk/PoissonSolver.h
include/ibamr/ConstraintIBMethod.h
include/ibamr/IBFEMethod.h
include/ibamr/IBStrategy.h

We cannot compile on some systems without explicitly including the memory header in IBStrategy.h - add it everywhere else we might need it while we are at it.

Add some missing header inclusions.

---

doc/news/changes/minor/20200215DavidWells
ibtk/src/lagrangian/fortran/lagrangian_interaction2d.f.m4
ibtk/src/lagrangian/fortran/lagrangian_interaction3d.f.m4

`ic_center` was read before initialized in the 3D version of this kernel. I fixed it and cleaned up the other kernel implementations to match.
The test output for this test is still unreliable but I have a more general fix for that in the pipeline.
Part of #784.

Fix the discontinuous linear 3D spread kernel.

---

tests/IBFE/ib_partitioning_01.cpp

GCC's address sanitizer complains about this - its quick so lets just fix it.

Initialize a variable.

---

src/IB/IBFEMethod.cpp

This is never read when we do the communication with the scratch hierarchy so we can skip it.
Fixes #737.

Skip copying ghost data when we can.

---

ibtk/src/lagrangian/FEDataManager.cpp
tests/spread/spread_01.cpp
tests/spread/spread_01_2d.square.b.bspline_3.input
tests/spread/spread_01_2d.square.b.bspline_3.output

Found while working on #857 - it looks like this function hasn't ever worked correctly when one did not provide the boundary ops object since we spread values into ghost regions and then do not add those values back to the provided force index.

Fix a bug in FEDataManager::spread().

---

ibtk/src/lagrangian/fortran/lagrangian_interaction2d.f.m4
ibtk/src/lagrangian/fortran/lagrangian_interaction3d.f.m4

I have been working on this patch off-and-on for the last two months - its now done ~except for the high-order IB kernels (those are unlike the rest of the kernels in that they compute the complete stencil regardless of the position of the point in the box: i.e., they compute stencil values that are never used if we are at a patch boundary).~ Clarification: once #615 is done we will always need the complete stencil for every point so converting the kernels that already unconditionally compute the stencil (constant, RT0, and high order IB) is not worth doing quite yet.
This mostly addresses the goals of #615 - once we change things to sum values spread into ghost regions into other patch interiors then we can fix the remaining issues (we can avoid the awkward partial stencil calculations). …

Clean up most of the IB kernels.

---

doc/news/changes/incompatibilities/20200311DavidWells
include/ibamr/IBFEMethod.h
include/ibamr/ibamr_enums.h
src/IB/IBFEMethod.cpp

The old version was based on an incorrect assumption that the nonlocality of libMesh data was the cause of performance problems - in fact, the problem was/is the number of IB points per processor. We should not repartition the Lagrangian data unless the user explicitly asks for it since this will actually degrade performance in the calculation of forces on the Lagrangian mesh.

Change the default settings for libMesh remeshing.

---

doc/mpi.md

Fixes #884. This problem is quite difficult but we should at least provide enough information for users to get started (and to figure out how to saturate memory bandwidth).
There is one missing section on good slurm parameters - I will fill that in tomorrow. We should also cite some references (like adding a link to the PETSc manual).

Add some notes on using MPI.

---

doc/news/changes/minor/20200311DavidWells
include/ibamr/IBFEMethod.h
src/IB/IBFEMethod.cpp

This doesn't change anything after the first time we call it. This function accounts for about 15% of the total time spent setting things up after regridding so its worth removing for performance reasons.
We regrid about every other timestep when we start the TAVR code so this is actually noticeable in some regimes of some applications.

Remove call to IBFEMethod::reinitializeFEData().

---

attest

A scheduler may assign multiple MPI jobs to the same processors on a cluster unless we explicitly disable binding. This is necessary for the test suite since we have multiple concurrent MPI programs running.

Slightly improve test suite performance.

---

doc/news/changes/minor/20200306AaronBarrett
ibtk/include/ibtk/IBTKInit.h
ibtk/include/ibtk/IBTK_MPI.h
ibtk/include/ibtk/private/IBTK_MPI-inl.h
ibtk/lib/Makefile.am
ibtk/lib/Makefile.in
ibtk/src/utilities/IBTKInit.cpp
ibtk/src/utilities/IBTK_MPI.cpp
tests/IBTK/Makefile.am
tests/IBTK/Makefile.in
tests/IBTK/ibtk_init.cpp
tests/IBTK/ibtk_init.input
tests/IBTK/ibtk_init.output

This is a follow up from #287. We need to add an initialization class to ensure that the default communicator in `IBTK_MPI` is set. This also initializes standard libraries to make a transition to SAMRAI 3 easier (SAMRAI 3 adds required initialization calls). I also went ahead and moved templated `IBTK_MPI` functions to a separate private file.
This PR just adds the class, but does change any of the examples.

IBTK Initialization class

---

doc/news/changes/minor/20200316DavidWells
include/ibamr/IBFEMethod.h
src/IB/IBFEMethod.cpp

I took a look at our mass matrix solves and I noticed (via `-ksp_log`) that our matrices allocated three times as many entries as they actually used in 3D. This is because, by default, libMesh assumes all variables couple to each-other.
We can get around this by providing an extra argument to libMesh. This saves us some memory (about 10% for the heart model). Fortunately PETSc is already smart enough to ignore the zero entries so it does not really change the performance.

Improve fe coupling

---

configure
configure.ac

This is sometimes useful when comparing builds. Fixes #881. 
It would be nice to also make this information available in something like
```cpp
print_ibamr_hash(std::ostream &out);
```
but this would require rerunning `configure` after every commit to make sure we always have the correct hash in the source code. Its not clear to me how to do this with autotools and I don't think its worthwhile at this time since running configure takes a long time.

Print IBAMR version and git commit hash in config.log.

---

doc/news/changes/minor/20200318DavidWells
ibtk/src/solvers/impls/CCPoissonHypreLevelSolver.cpp
ibtk/src/solvers/impls/SCPoissonHypreLevelSolver.cpp

Additionally, exit successfully if there were no iterations and the residual norm is nan - this can happen when the right-hand side is the zero vector (which occurs durring initialization, like in regridProjection).
Part of #778 - we need this change to get most of the tests passing with floating point exceptions enabled.

Zero some stored hypre residuals.

---

doc/release-tasks.md
ibtk/include/ibtk/PETScVecUtilities.h
ibtk/include/ibtk/SAMRAIGhostDataAccumulator.h
ibtk/src/utilities/SAMRAIDataCache.cpp
include/ibamr/CFRelaxationOperator.h
include/ibamr/IBBeamForceSpec.h
include/ibamr/IBHierarchyIntegrator.h
include/ibamr/IBInstrumentationSpec.h
include/ibamr/IBKirchhoffRodForceGen.h
include/ibamr/IBRodForceSpec.h
include/ibamr/IBTargetPointForceSpec.h
include/ibamr/MaterialPointSpec.h
include/ibamr/private/IBInstrumentationSpec-inl.h
src/IB/IBFEMethod.cpp
src/IB/IBFEPostProcessor.cpp
src/IB/KrylovMobilitySolver.cpp
src/adv_diff/AdvDiffHierarchyIntegrator.cpp

1. We don't need to include unistd.h in these headers - we aren't doing any
system calls.
2. We don't need stddef.h.
3. Fix a compilation problem where IWYU added an internal GCC header.
4. Remove IWYU from the list of release tasks - its just not worth the pain.

Fix some IWYU issues.

---

bootstrap

This now rebuilds new versions of autotools if the version installed on the user's machine does not match the required versions. The old version of the script just checked that the minor version number instead of the whole thing.
Additionally, I ran shellcheck and fixed most of the problems with the script.
Related to #944.

Clean up the bootstrap script.

---

doc/news/changes/minor/20200330DavidWells
src/IB/IBFEMethod.cpp
tests/IBFE/Makefile.am
tests/IBFE/Makefile.in
tests/IBFE/explicit_ex1.cpp
tests/IBFE/explicit_ex1_2d.mpirun=4.input
tests/IBFE/explicit_ex1_2d.mpirun=4.output

I'm skipping fluid sources for the last step of #896 but I want to be sure that we handle jump conditions correctly since they are used in a lot of examples. It turns out that this didn't work correctly with AMR - fortunately the fix is pretty simple. I added an interesting test (a thin elastic ring) to make sure we are accumulating forces correctly.

Fix spreadTransmissionForceDensity() + AMR.

---

tests/IBFE/interpolate_velocity_01.cpp
tests/IBFE/interpolate_velocity_01_2d.a.mpirun=4.output
tests/IBFE/interpolate_velocity_01_2d.b.mpirun=4.output
tests/IBFE/interpolate_velocity_01_2d.c.mpirun=4.output
tests/IBFE/interpolate_velocity_01_2d.d.ghosted.mpirun=4.output
tests/IBFE/interpolate_velocity_01_2d.d.mpirun=4.output
tests/IBFE/interpolate_velocity_01_2d.nodal_quadrature.a.mpirun=4.output
tests/IBFE/interpolate_velocity_01_2d.nodal_quadrature.b.mpirun=4.output
tests/IBFE/interpolate_velocity_01_2d.nodal_quadrature.c.mpirun=4.output
tests/IBFE/interpolate_velocity_01_3d.a.mpirun=4.output
tests/IBFE/interpolate_velocity_01_3d.b.mpirun=4.output
tests/IBFE/interpolate_velocity_01_3d.c.cached.mpirun=4.output
tests/IBFE/interpolate_velocity_01_3d.c.ghosted.mpirun=4.output
tests/IBFE/interpolate_velocity_01_3d.c.mpirun=4.output
tests/IBFE/interpolate_velocity_01_3d.nodal_quadrature.a.mpirun=4.output
tests/IBFE/interpolate_velocity_01_3d.nodal_quadrature.b.mpirun=4.output
tests/IBFE/interpolate_velocity_01_3d.nodal_quadrature.c.mpirun=4.output

Quick followup to #957 - I forgot to do a max reduction everywhere.
Additionally, to make sure that we really do get the same results independent of the number of processors, I replaced all parallel output files with symbolic links to serial output files.

Fix test again

---

ibtk/include/ibtk/JacobianCalculator.h
ibtk/include/ibtk/JacobianCalculatorCache.h
ibtk/src/lagrangian/JacobianCalculator.cpp
tests/IBTK/jacobian_calc_01.cpp

First part of #482: we need to efficiently sidestep libMesh's computations of the contravariant so that we can compute both JxW values and gradients.
This first PR doesn't do much - it just explicitly stores the computed contravariant in a renamed class. The new few PRs will add other useful mapping features (array of jacobians, mapped quadrature points). Once we have all the features of the mapping we can move on to replace `libMesh::FEBase` for a subset of elements. …

Implement contravariants

---

examples/IBFE/explicit/ex4/example.cpp

that we do not need to compile more test executables.     
Bugfix in one of the examples.
...

Fixed compilation error in IBFE ex4: missing replicated_mesh header

---

ibtk/src/math/SAMRAIGhostDataAccumulator.cpp

Caught by massif while looking around for other problems. I modified a test to create `SAMRAIDataAccumulator`s in a loop - it leaks on master but doesn't with this patch.
We shouldn't create multiple variables - this actually uses a noticeable amount of memory in long time integrations.

Fix a memory consumption bug in SAMRAIGhostDataAccumulator.

---

doc/news/changes/minor/20200408BoyceGriffith
src/adv_diff/AdvDiffWavePropConvectiveOperator.cpp
tests/adv_diff/Makefile.am
tests/adv_diff/Makefile.in
tests/adv_diff/adv_diff_convec_opers.cpp
tests/adv_diff/adv_diff_convec_opers_2d.constant.input
tests/adv_diff/adv_diff_convec_opers_2d.constant.output
tests/adv_diff/adv_diff_convec_opers_2d.linear.input
tests/adv_diff/adv_diff_convec_opers_2d.linear.output
tests/adv_diff/adv_diff_convec_opers_2d.none.input
tests/adv_diff/adv_diff_convec_opers_2d.none.output
tests/adv_diff/adv_diff_convec_opers_2d.quadratic.input
tests/adv_diff/adv_diff_convec_opers_2d.quadratic.output
tests/adv_diff/adv_diff_convec_opers_3d.constant.input
tests/adv_diff/adv_diff_convec_opers_3d.constant.output
tests/adv_diff/adv_diff_convec_opers_3d.linear.input
tests/adv_diff/adv_diff_convec_opers_3d.linear.output
tests/adv_diff/adv_diff_convec_opers_3d.none.input
tests/adv_diff/adv_diff_convec_opers_3d.none.output
tests/adv_diff/adv_diff_convec_opers_3d.quadratic.input
tests/adv_diff/adv_diff_convec_opers_3d.quadratic.output

allow users to set outflow_bdry_extrap_type in AdvDiffWavePropConvectiveOperator

---

ibtk/include/ibtk/LibMeshSystemIBVectors.h
ibtk/include/ibtk/LibMeshSystemVectors.h
ibtk/lib/Makefile.am
ibtk/lib/Makefile.in
ibtk/src/utilities/LibMeshSystemIBVectors.cpp
ibtk/src/utilities/LibMeshSystemVectors.cpp
include/ibamr/IBFEMethod.h
src/IB/IBFEMethod.cpp

The base class, `LibMeshSystemVectors`, now only needs to use `libMesh::EquationSystem` objects to track the vectors. The new derived class, `LibMeshSystemIBVectors`, uses `FEDataManager` objects to determine IB ghosting.
Part of #966.

split LibMeshSystemVectors into base and derived classes

---

tests/IBFE/explicit_ex4_2d.a.postprocessor.output
tests/IBFE/explicit_ex4_2d.inactive_1.mpirun=4.output
tests/IBFE/explicit_ex4_2d.inactive_1.mpirun=4.restart=50.output
tests/IBFE/explicit_ex4_2d.mpirun=4.output
tests/IBFE/explicit_ex4_2d.mpirun=5.output
tests/IBFE/explicit_ex4_2d.output
tests/IBFE/explicit_ex4_2d.postprocessor.mpirun=4.output
tests/IBFE/explicit_ex4_2d.postprocessor.output
tests/IBFE/explicit_ex4_2d.postprocessor.scratch_hier.mpirun=4.output
tests/IBFE/explicit_ex4_2d.restart=50.mpirun=5.output
tests/IBFE/explicit_ex4_2d.restart=50.output
tests/IBFE/explicit_ex4_2d.scratch_hier.merge.mpirun=4.output
tests/IBFE/explicit_ex4_2d.scratch_hier.mpirun=4.output
tests/IBFE/explicit_ex4_2d.scratch_hier.restart=25.mpirun=4.output
tests/IBFE/explicit_ex4_3d.inactive_1.mpirun=4.output
tests/IBFE/explicit_ex4_3d.mpirun=4.output
tests/IBFE/explicit_ex4_3d.scratch_hier.merge.mpirun=4.output
tests/IBFE/explicit_ex4_3d.scratch_hier.mpirun=4.output
tests/IBFE/explicit_ex8_2d.scratch_hier.mpirun=4.output

It looks like I managed to merge #968 without running the test suite - this causes a bunch of test failures for trivial reasons (we log the creation of the solver in a different class now). This is good motivation for us to get the CI running the test suite.
Since this PR only affects the test suite I suggest we merge asap.

Fix test output related to FEProjector.

---

ibtk/include/ibtk/FECache.h
ibtk/include/ibtk/JacobianCalculator.h
ibtk/include/ibtk/JacobianCalculatorCache.h
ibtk/src/lagrangian/JacobianCalculator.cpp
tests/IBTK/Makefile.am
tests/IBTK/Makefile.in
tests/IBTK/jacobian_calc_01.cpp
tests/IBTK/mapping_01.cpp

Part of #482: this PR adds our own replacement code for computing finite element mappings (not values of shape functions), i.e., the contravariant, jacobian, JxW, and coordinates of quadrature points. This is about 20x faster than libMesh's equivalent.

Add compute q points

---

attest

This prevents us from running python at 100% when we have more available processors than work. This can happen when, for example, we run
./attest -j6 -R 'mpirun=4'
here we will never fully utilize the number of allocated cores, so the loop will endlessly attempt to schedule more jobs without waiting on the lone worker to finish first.

Fix a busy wait problem in attest.

---

ibtk/src/utilities/box_utilities.cpp

We get different partitions with the libc++ version of std::sort() than the
libstdc++ version of std::sort(), so just use std::stable_sort() to get the same
thing in both cases.
Note that this is a problem with the original algorithm: since we sort by magnitudes many entries have (as far as the sorting algorithm can see) the same value. Hence two different unstable sorting algorithms yield two different results.
GitHub …

Fix the merging algorithm used by MergingLoadBalancer.

---

src/IB/CIBMethod.cpp

Added IBTK namespace to a call to Vector in CIBMethod that was leading to compilation errors on the UNC longleaf system when using gcc 4.8.5 compilers.

Fixed namespace issue for Vector in CIBMethod

---

attest

The old check was too imprecise: if we are executing a single test we may still
be able to run more tests at the current time. Instead of waiting if we are only
running one test, instead wait if we couldn't launch any new tests.

Fix attest's busy wait again.

---

doc/news/changes/minor/20200528NishantNangia
src/navier_stokes/fortran/navier_stokes_staggered_helpers2d.f.m4
src/navier_stokes/fortran/navier_stokes_staggered_helpers3d.f.m4
tests/vc_navier_stokes/vc_navier_stokes_01_2d.output
tests/vc_navier_stokes/vc_navier_stokes_01_3d.output

This PR fixes a small bug in an edge case in the HR limiters used for the CUI, MGAMMA, and FBICS convective operator. I verified that this fix does not significantly change the order of accuracy of these operators, but it does change the output of two of the tests (which I went ahead and modified so that they pass).

Fix edge case in HR limiters

---

doc/news/changes/minor/20200529DavidWells
src/IB/IBFEMethod.cpp
tests/IBFE/explicit_ex4.cpp
tests/IBFE/explicit_ex4_2d.scratch_hier.levels=1.mpirun=4.input
tests/IBFE/explicit_ex4_2d.scratch_hier.levels=1.mpirun=4.output
tests/IBFE/explicit_ex4_2d.scratch_hier.levels=4.mpirun=4.input
tests/IBFE/explicit_ex4_2d.scratch_hier.levels=4.mpirun=4.output

The fix here is easy - we only want to regrid one level (the finest) so we
should not hard-code zero as the coarser level in the call to
regridAllFinerLevels.

Fix the scratch hierarchy with more than two levels.

---

configure
ibtk/configure
m4/configure_hypre.m4

New versions of hypre removed these very old symbols. I checked that the version of hypre downloaded with PETSc 3.7.7 still works with IBAMR.

Fix detection of newer versions of hypre.

---

doc/news/changes/minor/20200626AaronBarrett
ibtk/include/ibtk/HierarchyIntegrator.h
src/adv_diff/AdvDiffHierarchyIntegrator.cpp

Fixes #1022. `AdvDiffHierarchyIntegrator` did not compute timestep sizes consistent across all processors. I've updated the documentation in `HierarchyIntegrator` to note that time step sizes should be consistent in implementations of `getMinimumTimeStepSizeSpecialized` and `getMaximumTimeStepSizeSpecialized`. ~~This is also fixes a minor bug in `HierarchyIntegrator` to select the smallest …

Bug fixes to compute time steps in parallel.

---

doc/news/changes/minor/20200629DavidWells
ibtk/include/ibtk/libmesh_utilities.h

GCC 10.1.0 got a lot better at vectorizing code, but in this case I am pretty sure it is doing something wrong: it is generating wrong code w.r.t. where the array index is placed which causes bus errors. I will ultimately report this to the GCC guys but I want to finish up a few other things first - for now this workaround seems to defeat the loop vectorization function.

Prevent some code from being overoptimized.

---

include/ibamr/AdvectorExplicitPredictorPatchOps.h
src/advect/AdvectorExplicitPredictorPatchOps.cpp
src/advect/fortran/advect_predictors3d.f.m4

Enabling link-time optimization with GCC has the interesting side effect of enabling type-checking of our Fortran interfaces. In particular, it looks like LOGICAL is not the same as unsigned int: some FORTRAN compilers make logical true equal to -1 so this is not the right choice.
After reading through some gfortran documentation I'm not sure at all what integral type LOGICAL is supposed to be, so lets completely avoid the issue and use an integer set to 1 if we want the corner code on.
Here is one of the four GCC warnings:
```
/home/drwells/Documents/Code/CPP/ibamr/src/advect/AdvectorExplicitPredictorPatchOps.cpp:411:10:
warning: type of 'advect_predict_ppm_with_source3d_' does not match original declaration
411 |     void ADVECT_PREDICT_PPM_WITH_SOURCE_FC(const double*,
|          ^ …
```

Fix an ABI problem in some Fortran code.

---

ibtk/src/refine_ops/fortran/Makefile.am
ibtk/src/refine_ops/fortran/Makefile.in
ibtk/src/refine_ops/fortran/cart_side_helpers.f.m4
ibtk/src/refine_ops/fortran/cart_side_refine2d.f.m4
ibtk/src/refine_ops/fortran/cart_side_refine3d.f.m4
src/advect/fortran/advect_helpers.f.m4

We need to do this in the CMake build so that there are no undefined symbols in libIBTK2d and libIBTK3d. With static libraries this is not a problem but it is with shared libraries on mac (the linker fails if any symbols are undefined).

Move a Fortran function used in IBTK into IBTK.

---

.dir-locals.el

This is specific to a particular user's projectile configuration.
The usual checksheet doesn't apply since this is strictly an emacs configuration file.

Remove a stray emacs file.

---

doc/news/changes/minor/2020713DavidWells
src/IB/IBFEMethod.cpp

Thanks to @jabrown893 for pointing this out.
IBFEMethod can determine the ghost cell width required by itself and by FEDataManager, but it doesn't know about ghost cell with requirements of other classes. Hence we should not use its own ghost width for setting up force spreading accumulation data structures - instead we can just read it from the input data.

Fix the ghost cell size given to SAMRAIGhostDataAccumulator.

---

ibtk/include/ibtk/JacobianCalculatorCache.h

At some point we need to get rid of this class in favor of our own homebrew Mapping class but we aren't there yet. In the mean time we can simplify things by using Mapping::build() instead of a custom switch statement.
Including a few more custom element sizes makes HEX8 meshes faster - in particular this makes IBFE/explicit/ex4 about 1% faster in 3D.

Use Mapping::build() directly in JacobianCalculatorCache.

---

doc/news/changes/major/20200723DavidWells
ibtk/src/lagrangian/FEProjector.cpp
tests/IBFE/explicit_ex1_2d.nodal_quadrature.mpirun=4.output
tests/IBFE/explicit_ex1_2d.nodal_quadrature.output
tests/IBFE/explicit_ex4_2d.a.postprocessor.output
tests/IBFE/explicit_ex4_2d.amr.mpirun=4.output
tests/IBFE/explicit_ex4_2d.amr.nodal_quadrature.mpirun=4.output
tests/IBFE/explicit_ex4_2d.amr.restart=50.mpirun=4.output
tests/IBFE/explicit_ex4_2d.inactive_1.mpirun=4.output
tests/IBFE/explicit_ex4_2d.inactive_1.mpirun=4.restart=50.output
tests/IBFE/explicit_ex4_2d.mpirun=4.output
tests/IBFE/explicit_ex4_2d.mpirun=5.output
tests/IBFE/explicit_ex4_2d.output
tests/IBFE/explicit_ex4_2d.postprocessor.mpirun=4.output
tests/IBFE/explicit_ex4_2d.postprocessor.output
tests/IBFE/explicit_ex4_2d.postprocessor.scratch_hier.mpirun=4.output
tests/IBFE/explicit_ex4_2d.restart=50.mpirun=5.output
tests/IBFE/explicit_ex4_2d.restart=50.output
tests/IBFE/explicit_ex4_2d.scratch_hier.levels=1.mpirun=4.output
tests/IBFE/explicit_ex4_2d.scratch_hier.levels=4.mpirun=4.output
tests/IBFE/explicit_ex4_2d.scratch_hier.merge.mpirun=4.output
tests/IBFE/explicit_ex4_2d.scratch_hier.mpirun=4.output
tests/IBFE/explicit_ex4_2d.scratch_hier.restart=25.mpirun=4.output
tests/IBFE/explicit_ex4_3d.inactive_1.mpirun=4.output
tests/IBFE/explicit_ex4_3d.mpirun=4.output
tests/IBFE/explicit_ex4_3d.scratch_hier.merge.mpirun=4.output
tests/IBFE/explicit_ex4_3d.scratch_hier.mpirun=4.output
tests/IBFE/explicit_ex8_2d.scratch_hier.mpirun=4.output

It occurred to me that, now that we have a lumped mass matrix, we have a much better preconditioner available to us for mass matrix solves than just using ILU or a Jacobi variant.
Using MINRES and a Jacobi preconditioner based on the lumped mass matrix is about twice as fast as the previous approach (GMRES and ILU) largely because ILU is overkill for this problem.

Use a better algorithm for L2 projection.

---

doc/news/changes/minor/20200724DavidWells
ibtk/include/ibtk/FEDataManager.h
ibtk/src/lagrangian/FEDataManager.cpp
include/ibamr/IBFEMethod.h
src/IB/IBFEMethod.cpp
tests/IBFE/explicit_ex4_2d.scratch_hier.nodeweight.mpirun=4.input
tests/IBFE/explicit_ex4_2d.scratch_hier.nodeweight.mpirun=4.output

This is a decent measure of the number of elements. It is preferable to using element centroids since multiple patches may need to integrate over a single element.
I am still running some tests to try and figure out good values for the weight relative to the quadrature point weight.

Permit load balancing also by the number of (duplicated) nodes.

---

doc/news/changes/minor/20200727AaronBarrett
ibtk/src/utilities/AppInitializer.cpp

`AppInitializer` sets up visualization, restart, and timer objects in that order. But since the SAMRAI class `VisItDataWriter` also sets up timers through the static `TimerManager` class, a default `TimerManager` class will be created. The simple fix is to create the `TimerManager` object before `VisItDataWriter`.

Create timer manager before everything else.

---

examples/IB/explicit/ex0/example.cpp
examples/IBFE/explicit/ex0/example.cpp
ibtk/src/utilities/IBTK_MPI.cpp
tests/IB/explicit_ex0.cpp
tests/IBFE/explicit_ex0.cpp

This allows for backwards compatibility after #976. We now use a default communicator of `MPI_COMM_WORLD`. I also reverted two examples `IB/explicit/ex0` and `IBFE/explicit/ex0` (one with libMesh, one without) and tests `IB/explicit_ex0` and `IBFE/explicit_ex0` to ensure everything still works.

Changed default MPI communicator for backwards compatibility

---

doc/news/changes/minor/20200731DavidWells
ibtk/src/lagrangian/FEDataManager.cpp

We can get much better performance by implementing a few extra things:
1. Inline the function
2. Explicit short-circuit logic in the loop over spatial dimensions
3. Skip a fourth redundant line segment check
This seems trivial, but it makes a huge difference in models with large numbers
of elements (such as the TAVR code) that regrid frequently since we presently
call this function, for N local patches and K global elements, K*N times: i.e.,
if one processor has twice as many patches it has to do twice as much work, so
making this much cheaper has a large benefit to both serial preformance and time
spent waiting in parallel.
number is …

Implement a faster bounding box intersection function.

---

ibtk/src/utilities/AppInitializer.cpp

This avoids a warning later on where SAMRAI will create it with a null database anyway.
Followup to #1055.

Always create SAMRAI's TimerManager.

---

ibtk/src/utilities/AppInitializer.cpp

Fix some issues in #1073: it looks like I messed up running the test suite somehow. Fortunately its not a big deal to remedy.
This does not work as intended since if absolutely nothing is specified (like in most of the tests) then timer_dump_interval_key_name is an empty string - lets just avoid the problem by getting rid of it. The problem is obvious, anyway - if no timer information is specified the TimerManager will print things we don't want.
Furthermore - we don't want to use a null database here since that will always pass checks for whether or not a key exists (here 'null database' really means that they are using the null object pattern, not that it is an empty database).
up appropriately for …

Get rid of an extra warning.

---

doc/news/changes/incompatibilities/20200813DavidWells
ibtk/include/ibtk/FEDataManager.h
ibtk/include/ibtk/libmesh_utilities.h
ibtk/src/lagrangian/FEDataManager.cpp
ibtk/src/lagrangian/FEProjector.cpp
src/IB/FEMechanicsBase.cpp
src/IB/IBFEMethod.cpp
src/IB/IBFESurfaceMethod.cpp

A decent chunk of our total memory usage (something like ~70~ 150 MB out of 2000 MB) per processor is taken up by allocating tons of these vectors. We can get this somewhat under control by using a denser data structure.
Unfortunately we do need to keep `SystemDofMapCache` for now since it is much more efficient than the native libMesh methods.
Edit: I misread massif's memory profiling. The …

Vector vector to multiarray

---

Makefile.in
config/config.h.tmp
configure
configure.ac
ibtk/Makefile.in
ibtk/config/config.h.tmp
ibtk/configure
ibtk/configure.ac

Part of #1020: We need to ultimately get rid of `IBTK_config.h` and `IBAMR_config.h` since they are top-level files. This PR adds shims that are compatible with both the new CMake build system (which doesn't have top level files) to ease the transition. Upcoming PRs will remove direct `IBTK_config.h` and `IBAMR_config.h` inclusions from the library.

Add compatibility headers for CMake.

---

ibtk/include/ibtk/FEDataManager.h
ibtk/src/lagrangian/FEDataManager.cpp

The dofs are always the same if we have the same FEType.
Followup to #1075.

Reduce the total number of SystemDofMapCaches.

---

ibtk/src/utilities/box_utilities.cpp
tests/IBTK/box_utilities_01.cpp

The extra insert statement doesn't make any sense: its a set so it already contains its first element, and if it is an empty set then this creates an invalid object (we read whatever happens to be at `begin()` and turn it into an object). In particular, since some processors can end up with zero boxes in very strange situations, this causes nonsense boxes to be created in the output as a result.
I think this bug only shows up in test problems since it is really rare, in practice, for a process to end up with no patches. This also only effects the scratch hierarchy.
or tests should be added. New tests should run …

Fix the merging load balancer.

---

ibtk/include/ibtk/libmesh_utilities.h

libMesh expects an unsigned integer - lets oblige.

Fix a sign warning in debug mode.

---

ibtk/include/ibtk/FEDataManager.h
ibtk/src/lagrangian/FEDataManager.cpp

Future patches (such as multilevel interaction and behavior with nodes outside
patches) really need some things to be set in an input database, so make one
available.
In particular we need this for passing in parameters in #1087.

Add another FEDataManager::getManager overload.

---

ibtk/include/ibtk/FEProjector.h
ibtk/src/lagrangian/FEProjector.cpp

This is mostly just moving some code around in the implementation file to keep things synched with the header.
I also update some variable names to use "`L2`" consistently (since L^2 and l^2 are different), and make some member variable names more consistent.

clean up FEProjector

---

doc/news/changes/minor/20200826DavidWells
ibtk/include/ibtk/FEDataManager.h
ibtk/include/ibtk/ibtk_enums.h
ibtk/src/lagrangian/FEDataManager.cpp
include/ibamr/IBFEMethod.h
src/IB/IBFEMethod.cpp

Part of #1085 - this is just the last patch from #1086.
We could have saved a lot of time trying to diagnose #1085 if we had a way to detect that IBFEMethod was not working correctly. This PR adds a check to ensure that all mesh nodes are actually inside a patch or outside the domain.
To get around a problem with SAMRAI we use bounding boxes for patches that are slightly larger than the patch itself. Similarly, to determine if a point is outside the domain, we use a bounding box slightly smaller than the domain itself. In either case the node is OK.
or tests should be added. New tests should run quickly (less than a …

Check for nodes that are inside the domain but outside a patch.

---

doc/news/changes/major/20200825DavidWells
include/ibamr/IBFEMethod.h
src/IB/IBFEMethod.cpp
tests/IBFE/explicit_ex4_2d.no-regrid.mpirun=4.input
tests/IBFE/explicit_ex4_2d.no-regrid.mpirun=4.output

Fixes #1085.
The fix I have here still causes a few tests to fail because I added a check to error out if there are nodes that are not associated with patches. Hence, before proceeding, I think its worth deciding whether or not we want to continue supporting nodes outside the physical domain - if any IB points are outside the physical domain we implicitly assume that they have zero velocity and don't spread forces. The former is a questionable assumption since, e.g., for the lid driven cavity, the velocity very well may not be zero.
in release …

Ibfemethod patch elem assoc

---

include/ibamr/IBFESurfaceMethod.h
src/IB/IBFESurfaceMethod.cpp

Part of #934 - `LibMeshSystemData` ended up being added to the library and used so we should go ahead and use it in `IBFESurfaceMethod`. Using it here also lets use remove some deprecated `FEDataManager` functions which will be nice for cleaning up that class (as part of the multilevel project).

Use LibMeshSystemIBVectors in IBFESurfaceMethod, part 1.

---

tests/IBTK/samraidatacache_01.cpp

This is a copy-paste bug from #976.

Fixed test suite compilation when libmesh is not present.

---

Makefile.am
Makefile.in

Make requires `$$`, even in strings.
The current version of this results in omitting, by default, all the navier stokes tests since those start with `n`. I guess we never noticed. Ooops.

Fix an escaped dollar sign.

---

config/IBAMR_config.h.tmp.in
configure
doc/news/changes/incompatibilities/20200916DavidWells
ibtk/config/IBTK_config.h.tmp.in
ibtk/configure
m4/configure_hdf5.m4

Fixes a problem reported on the mailing list (thanks Govind for reporting this).
We never use it (as far as I can tell SAMRAI does not use it either) and not all machines have it - it became a mandatory dependency in 0.5 due to #601.

Don't link against libhdf5_hl.

---

doc/news/changes/incompatibilities/20200917DavidWells
ibtk/include/ibtk/FEDataManager.h
ibtk/src/lagrangian/FEDataManager.cpp
src/IB/IBFEMethod.cpp
src/IB/IBFEPostProcessor.cpp
src/IB/IBFESurfaceMethod.cpp
tests/IBFE/explicit_ex4.cpp

This PR is mostly a cleanup of a bunch of different FEDataManager functions - it no longer makes sense to ask for the level on which the patch hierarchy resides, nor does it make sense to assign this with a function call (its set up in the constructor by the input database).
I removed a bunch of functions so this isn't backwards compatible but since this feature didn't exist in the past I think it's not a big deal to break it.
Part of #1112.
that we do not need to compile …

Multilevel ibfe 6

---

src/IB/IBFEMethod.cpp
tests/IBFE/explicit_ex4_2d.multilevel.b.input
tests/IBFE/explicit_ex4_2d.multilevel.b.mpirun=5.output
tests/IBFE/explicit_ex4_2d.multilevel.b.output
tests/IBFE/explicit_ex4_2d.scratch_hier.multilevel.b.input
tests/IBFE/explicit_ex4_2d.scratch_hier.multilevel.b.mpirun=4.output
tests/IBFE/explicit_ex4_2d.scratch_hier.multilevel.b.output

I am working on a new IBFE example and I noticed that the scratch multilevel tests aren't right - they don't actually use multiple levels. It turns out the other tests I added don't either. Fortunately you can see that they don't make a big difference in the values we compute (which implies that the multilevel stuff works).
Another fix: we were not regridding all scratch hierarchy levels which lead to some poor load balancing. This is also fixed.
that we do not need to …

Fix scratch and multilevel tests

---

doc/release-tasks.md
src/IB/IBFEMethod.cpp
src/IB/IBFESurfaceMethod.cpp
src/complex_fluids/CFINSForcing.cpp

It turns out that unless we request a unique `HierachyDataOps` then we store a copy of that object indefinitely, and that object stores a pointer to the scratch hierarchy - i.e., we never deallocate the scratch hierarchies and we get a new one every time we regrid.
I figured this out by setting a breakpoint in `SAMRAIDataCache::setPatchHierarchy()`. At the point we are supposed to destroy the hierarchy (because its reference count is zero) we in fact have a reference count of 3. To verify that this works I rigged up a copy of an IBFE example to regrid at every time step - without this patch it more than triples in memory and with this patch the memory usage is nearly constant (in both cases I had 1000 timesteps with 1000 regrids).
Since these are not really memory leaks (we destroy the …

Fix the memory leak with the scratch hierarchy.

---

ibtk/include/ibtk/HierarchyIntegrator.h
include/ibamr/IBHierarchyIntegrator.h
src/IB/IBExplicitHierarchyIntegrator.cpp
src/IB/IBHierarchyIntegrator.cpp
src/IB/IBImplicitStaggeredHierarchyIntegrator.cpp
src/IB/IBInterpolantHierarchyIntegrator.cpp

This class is responsible for managing the estimated point displacement values, so it should update them (instead of all three inheriting classes copying and pasting the same code).
Part of #1147 - we really shouldn't implement the same structure logic three times.

Let IBHierarchyIntegrator postprocess its own data.

---

src/IB/IBFEMethod.cpp
tests/IBFE/explicit_ex4_2d.displace.mpirun=4.output

This gets around a bug in numdiff where a number followed by a period isn't treated the same way as a number followed by a space. Thanks @jabrown893 for pointing out that this test is failing!

Fix a displacement test.

---

config/IBAMR_config.h.tmp.in
configure
doc/news/changes/minor/20200910DavidWells
ibtk/config/IBTK_config.h.tmp.in
ibtk/configure
m4/configure_silo.m4

It looks like @cpuelz encountered this recently. Coincidentally I found some publicly-available notes from Michael Waldron which also contained a workaround.
Almost every Unix machine has zlib installed in a standard location so this flag is basically never necessary. This patch fixes the link flags so that it actually works correctly in the very unlikely case that it is explicitly needed.

Fix --with-zlib

---

CMakeLists.txt
src/CMakeLists.txt

Fixes #1172 - the link order resulted in both `libIBTK.so` and `libIBAMR.so` having copies of the same SAMRAI symbols, which lead to very strange results (like a file handle being set for IBTK but not IBAMR). I'm surprised this isn't a problem on Linux - good thing we test with multiple platforms. I cleaned up a few other things while I was around.

Cmake mac fixes

---

tests/CMakeLists.txt

This fixes a very silly repeated variable definition bug. The definition at the top of the file is correct.
The usual checklist isn't relevant. This makes the coarsen tests added in #1122 actually run.

CMake: remove a duplicate definition.

---

tests/IBFE/explicit_ex4_2d.multilevel.d.input
tests/IBFE/explicit_ex4_2d.multilevel.d.output

The point of this test is to verify that we can put the structure on a fluid level that is not the finest. For reasons I don't fully understand (SAMRAI might be generating machine-dependent grids) we get slightly different CFL numbers but exactly the same structure volumes on different machines, regardless of optimization settings. Hence I'm content to fix the problem (which is unrelated to multilevel IBFE) by making the test easier (only one finer level than the structure instead of 2).
Fixes #1173.
in release mode). If possible, an older …

Fix multilevel.d test

---

src/IB/IBFEMethod.cpp

This option should have been included in #1188.

add input option controlling if negative weights are allowed in IBFE coupling

---

CMakeLists.txt

The usual checklist doesn't apply since this just modifies CMake messages.

CMake: improve the MPI check messages.

---

doc/news/changes/minor/20210122DavidWells
ibtk/include/ibtk/FEMapping.h
ibtk/src/lagrangian/FEMapping.cpp
tests/IBTK/jacobian_calc_01.cpp
tests/IBTK/mapping_01.cpp

We need to specify the element used for both the quadrature rule (since QNODAL depends on that) and also the mapping itself (which libMesh assumes is always a Lagrange-type mapping based on the nodes of the mesh).
Fixes #1209.

Fix FEMapping with QNODAL.

---

ibtk/include/ibtk/FEMapping.h
ibtk/include/ibtk/FischerGuess.h
ibtk/src/lagrangian/FEMapping.cpp
ibtk/src/lagrangian/FischerGuess.cpp

Thes solves a few problems:
1. We assume (in FischerGuess) that libMesh links against LAPACK - this might not be true so we shouldn't use its SVD solve.
2. Even in OPT mode, libMesh still does some bounds checking that shows up in profiling (e.g., in IBTK::PointMap). We check the bounds outside the loop anyway so switching to Eigen (which won't bounds-check) is safe and more efficient.
3. Eigen offers a cleaner API. …

Convert libMesh::DenseMatrix to Eigen::Matrix.

---

ibtk/src/lagrangian/FischerGuess.cpp

The BCDSVD algorithm defaults to using Jacobi for small matrices so this has no effect in practice. Fixes #1213.

Fix compatibility with Eigen 3.2.

---

doc/news/changes/minor/20200301DavidWells
ibtk/src/lagrangian/FEProjector.cpp
tests/IBFE/explicit_ex2_3d.mpirun=2.input
tests/IBFE/explicit_ex2_3d.mpirun=2.output

We need to set these options after we implement constraints since, during that step, we will temporarily not have a symmetric matrix. This fixes the bug reported to the mailing list last week.

Fix the order in which we set some Mat options.

---

ibtk/src/lagrangian/FEProjector.cpp
src/IB/FEMechanicsBase.cpp
src/IB/IBFEInstrumentPanel.cpp
src/IB/IBFEMethod.cpp
tests/IBFE/explicit_ex2.cpp
tests/IBFE/explicit_ex5.cpp
tests/IBFE/ib_partitioning_02.cpp
tests/IBTK/fe_values_02.cpp
tests/IBTK/jacobian_calc_01.cpp
tests/level_set/fe_surface_distance.cpp
tests/wave_tank/nwt_cylinder.cpp

`boundary_info` is now protected and thus IBAMR won't compile unless deprecated code is turned back on in libMesh.
We are currently incompatible with libMesh's development branch - see https://github.com/libMesh/libmesh/issues/2883.

Remove some deprecated libMesh code.

---

include/ibamr/IBFEMethod.h
src/IB/IBFEMethod.cpp

Part of #1235.
This class should be responsible for managing its own scratch data object. 

Move a SAMRAIDataCache into SecondaryHierarchy.

---

CMakeLists.txt

libMesh now supports compilation with C++17, so we need to keep pace.
At the same time, we don't really support letting libMesh install its own copies of Eigen and Boost (the version of boost is insufficient and the version of Eigen doesn't use CMake) so try to detect those cases and error out appropriately.

Improve our CMake-based configuration of libMesh.

---

examples/IBFE/explicit/ex8/example.cpp
tests/IBFE/explicit_ex8.cpp

The new standard requires that these be const. GCC 11 defaults to C++17: fortunately this is the only patch we need to be able to compile as C++17.

Fix some more C++17 stuff.

---

doc/cmake.md

Normal checklist isn't relevant.
Fixes #1258, unless something odd is happening: @abarret this is only with CMake, correct?

Clarify that we need fPIC with SAMRAI.

---

doc/news/changes/minor/20210527AaronBarrett
ibtk/src/utilities/HierarchyIntegrator.cpp
tests/CMakeLists.txt
tests/IBTK/Makefile.am
tests/IBTK/Makefile.in
tests/IBTK/child_integrators.cpp
tests/IBTK/child_integrators_2d.input
tests/IBTK/child_integrators_2d.output

Fixes #1260. This fixes `HierarchyIntegrator` so that it properly traverses the tree of child integrators during `regridHierarchy`. I still need to add a test.

Child integrators are now traversed correctly in regridHierarchy().

---

src/IB/IBFEMethod.cpp
tests/IBFE/explicit_ex4_2d.postprocessor.scratch_hier.mpirun=4.output
tests/IBFE/explicit_ex4_2d.scratch_hier.levels=1.mpirun=4.output
tests/IBFE/explicit_ex4_2d.scratch_hier.levels=4.mpirun=4.output
tests/IBFE/explicit_ex4_2d.scratch_hier.merge.mpirun=4.output
tests/IBFE/explicit_ex4_2d.scratch_hier.mpirun=4.output
tests/IBFE/explicit_ex4_2d.scratch_hier.multilevel.b.mpirun=4.output
tests/IBFE/explicit_ex4_2d.scratch_hier.multilevel.b.output
tests/IBFE/explicit_ex4_2d.scratch_hier.nodeweight.mpirun=4.output
tests/IBFE/explicit_ex4_3d.scratch_hier.merge.mpirun=4.output
tests/IBFE/explicit_ex4_3d.scratch_hier.mpirun=4.output

For reasons already documented this isn't portable before timestepping.
Followup to #1256 - I forgot that printing out the initial workload isn't portable, so we need an extra check for that.
@abarret thanks again for finding this. Could you please double-check that all these tests pass?

Avoid printing the initial workload.

---

CMakeLists.txt

These should be a string of flags, not a semicolon-separated (i.e., CMake) list. It looks CMake 3.20 is strict enough in checking error codes that it detects this mistake.

Fix the CMake flags used in libMesh tests.

---

ibtk/src/utilities/SecondaryHierarchy.cpp
tests/IBTK/secondary_hierarchy_01.cpp

Since `tbox::Pointer`s can be converted to eachother all the way up through the `DescribedClass` base class we cannot specify default arguments here. I'm not sure how this works with new versions of GCC.
Regardless the fix is very easy - just delete unnecessary default arguments.

Fix a problem with overload resolution and the secondary hierarchy.

---

CMakeLists.txt

I think the CMake build system puts bundled Eigen headers in the wrong place. I needed this to configure an external project with a bundled Eigen.

Fix placement of bundled Eigen headers when using CMake install.

---

doc/news/changes/minor/20210706DavidWells
ibtk/include/ibtk/libmesh_utilities.h
src/IB/FEMechanicsBase.cpp

There is a lot of overhead in this loop since we need to do the same things (find FF, possibly evaluate position and velocity values, etc) for each PK1 stress function. We can essentially eliminate all the overhead by just combining together sufficiently similar PK1 stress functions - i.e., we do the same stuff if we have the same libMesh systems and quadrature rules.
Fixes #996.

Combine evaluation of PK1 stress functions.

---

attest

I verified that this worked by running with a very low test timeout - 78% of our tests can run in less than 2 seconds, which is nice.
Needed by #1285 or a followup to #1285.

Add a timeout to attest.

---

CMakeLists.txt

The usual list isn't relevant.

Print required and optional CMake paths in different places.

---

CMakeLists.txt

We use XDR in restarts so require it. Similarly, we always use MPI so make sure we have it on.
The normal checklist doesn't apply. Additionally, this will probably not pass with the current CI since (as discussed in #1289) we managed to configure libMesh without MPI in the docker image.

Add some more checks for libMesh features.

---

tests/fe_mechanics/fe_mechanics_ex0.cpp
tests/spread/spread_02.cpp

I still have ExodusII installed with libMesh but I checked every file that writes exodus output and all of them now check that we have it installed.
We only use ExodusII for plotting in applications - its not actually used inside the library itself.

Make ExodusII optional in the tests.

---

cmake/IBAMRConfig.cmake.in

This is nice to have during compilation (since we do not officially require anything more than the boost headers) but it really should not be set when users use IBAMR since they may want to use other parts of boost.
An example: https://github.com/drwells/fiddle uses IBAMR + deal.II, and deal.II uses the boost serialization library which is not header-only. For reasons I don't fully understand things seem to work, but it doesn't make sense to define this symbol in this circumstance, so we just shouldn't define it and let users do whatever they think is appropriate.
As usual, the list doesn't apply.
@abarret it would help if you could try this one out too before merging.

Remove an exported boost preprocessor symbol.

---

attest
src/IB/ConstraintIBMethod.cpp
tests/IBFE/explicit_ex8.cpp

In #1289 we obtained an implicit dependence on Python 3.7. This reverts that change.
I've also included a few needed `Vector` namespace changes.

Revert attest to require Python 3.5.

---

tests/IBTK/child_integrators.cpp

Follow-up to #1313. The tests pass when silo is not present.

Fixed child integrator test that outputs warnings when silo is not present.

---

ibtk/include/ibtk/config.h.in

Needed to work around some boost warnings.
Fixes the annoying boost warnings @boyceg, @marshallrdavey, and myself just saw.

Skip -Wparentheses in external headers.

---

ibtk/config/config.h.tmp

Same as #1315 but for autotools.
Unfortunately we do need to implement this twice. The ultimate goal is to have a single configuration header - in particular, one that is populated by CMake and is thus incompatible with autotools. Hence the autotools stub header needs to duplicate code.

Also avoid -Wparentheses warnings with autotools.

---

CMakeLists.txt
configure
ibtk/configure
m4/configure_petsc.m4

The usual checklist doesn't apply since this doesn't change the library.

Check that PETSc does not use 64bit indices.

---

ibtk/include/ibtk/SecondaryHierarchy.h
ibtk/src/utilities/SecondaryHierarchy.cpp
src/IB/IBFEMethod.cpp

I want to put this in now so that we can go back and add more timers later -
that will make it easier to justify the choice of multiple Eulerian data
partitionings in the load balancing paper.
In particular, I want to merge this now since this is an API change and we don't
have to worry about compatibility with this class yet since it is new in 0.9.

Transfer data inside the SecondaryHierarchy.

---

CMakeLists.txt

- Print a better error message if `LIBMESH_METHOD` is not provided
- Work correctly with non-installed PETSc builds

Fix two more minor CMake problems.

---

cmake/IBAMRConfig.cmake.in

The normal stuff doesn't apply - this only effects some messages printed in user projects configured with CMake.

Remove a debugging message.

---

doc/cmake.md

We should mention how to disable tests in `cmake.md` which contains the rest of the configuration documentation for CMake.

Recommend disabling tests.

---

examples/complex_fluids/ex2/example.cpp
examples/complex_fluids/ex4/example.cpp
examples/fe_mechanics/ex0/example.cpp

Fixes #1291. I will put up a second PR in a moment that documents the status quo on ibamr.github.io.
We do this in all the other libMesh examples that use ExodusII.

Print some warnings if libMesh doesn't have ExodusII.

---

include/ibamr/ConstraintIBMethod.h

Fixes #1110.
We decided to not switch to std::function since
1. We already pass context pointers as part of the API, so we don't really need to support binding to member functions, storing data with std::bind(), etc.
2. std::function usually requires an additional function call when it is bound to a function pointer defined in another compilation unit. Since we call these functions a lot (every quadrature point in IBFE) we should avoid that extra overhead.
3. Its better to use one way of passing functions around and not convert half the library to std::function.
This commit just removes a comment so I am not going to bother with the normal checklist.

Remove a note on std::function.

---

.github/cmake/github_ci.cmake

This only effects the CI, so the usual checklist doesn't apply.
This PR fixes two things:
- We wrote `REGEX_REPLACE` when we should have written `REGEX REPLACE`
- Our convention is to put CMake keywords in ALL CAPS to make them conspicuous

Cleanup GitHub ci

---

CMakeLists.txt
src/IB/DirectMobilitySolver.cpp

I don't really understand this problem - the `typedef` is clearly in an included Eigen header (`Meta.h`). Nevertheless relying on the type stored by the matrix works for both recent versions of Eigen and the one bundled with IBAMR.

Fix usage of Eigen::Index to work with older versions of Eigen.

---

CMakeLists.txt

Another small build system patch - the normal checklist doesn't apply.

Only run a libMesh check when we have libMesh.

---

ibtk/src/lagrangian/StableCentroidPartitioner.cpp
src/level_set/FESurfaceDistanceEvaluator.cpp
tests/IBFE/explicit_ex4.cpp
tests/IBFE/interpolate_velocity_01.cpp
tests/IBTK/multilevel_fe_01.cpp
tests/spread/spread_02.cpp

The upcoming release of libMesh (1.7.0) deprecates `Elem::centroid()` in favor of `Elem::vertex_average()` and `Elem::true_centroid()`.

Add some workarounds for newly deprecated libMesh functions.

---

doc/news/changes/minor/20211018DavidWells
ibtk/include/ibtk/LEInteractor.h
ibtk/src/lagrangian/FEDataManager.cpp
ibtk/src/lagrangian/LDataManager.cpp
ibtk/src/lagrangian/LEInteractor.cpp
src/IB/IBFEMethod.cpp
src/IB/IBFESurfaceMethod.cpp
src/IB/IBInterpolantMethod.cpp
src/IB/IBMethod.cpp

Incredibly, `fdl::IFEDMethod` spends about 6-7% of its time doing string comparisons inside `LEInteractor`. This patch rewrites those string comparison functions to check the minimal number of characters and instead moves the 'verify the kernel' checks to debug mode and also object constructors.

Improve kernel selection

---

attest

python 3.10 deprecates distutils with no replacement for strtobool - implement
our own.

Avoid using a deprecated feature in attest.

---

examples/ConstraintIB/eel3d/IBEELKinematics3d.cpp
examples/ConstraintIB/eel3d/eelgenerator3d.cpp
tests/external/eelgenerator3d.cpp

Some versions of boost expect the domain of the integral to be positive:
we can get around this by just returning 0.0 when the end points are
equal.

Workaround an assertion in older boost versions.

---

doc/news/changes/minor/20211215DavidWells
ibtk/include/ibtk/FEProjector.h
ibtk/src/lagrangian/FEProjector.cpp

This is a bit more useful and it shows a difference between force projection and velocity interpolation. I want to use this information in the L2 guess paper.
example output:
```
xfer::RefineSchedule::fillData()   0.053352 (1%)  
IBTK::FEProjector::computeL2Projection()[IB force system]  0.0448761 (1%)  
xfer::RefineSchedule::recursive_fill  0.0446169 (1%) …
```

Output linear solver times for each System.

---

doc/news/changes/incompatibilities/20211215DavidWells
ibtk/include/ibtk/IBTK_MPI.h
ibtk/include/ibtk/private/IBTK_MPI-inl.h
ibtk/src/utilities/IBTK_MPI.cpp
ibtk/src/utilities/ParallelEdgeMap.cpp
ibtk/src/utilities/ParallelSet.cpp

This came up on the mailing list and, unfortunately, the permanent fix is quite long.
The issue we have is that we made the MPI communicator argument implicit. Some versions of MPI have
```cpp
typedef unsigned int MPI_Comm;
```
which means that, with
```cpp
template <typename T>
static T sumReduction(T, IBTK_MPI::comm commiunicator = getCommunicator());
template <typename T>
static void sumReduction(T* x, const int n = 1, IBTK_MPI::comm communicator = getCommunicator());
```
if we do
```cpp
unsigned int size = 100;
double *values = array.begin();
sumReduction(values, size);
```
we end up calling the *first* function instead of the second one (due to C++ overload resolution rules its a better fit), which is wrong.
As far as I can tell, we have two reasonable options:
1. Audit every call …

Fix ibtk mpi

---

.github/cmake/configure_common.cmake
.github/cmake/configure_fedora33.cmake
.github/cmake/configure_sccache.cmake
.github/cmake/ctest_build.cmake
.github/cmake/ctest_configure.cmake
.github/cmake/ctest_exclusions.cmake
.github/cmake/ctest_submit_multi.cmake
.github/cmake/ctest_test.cmake
CMakeLists.txt
tests/CMakeLists.txt

Most of the time I want to compile `tests` independently of the library - i.e., `tests` should not be part of the `all` target. This isn't the standard CMake practice but 
This should work with the GitHub CI infrastructure - lets see if the tests still run with these changes.

Exclude tests from all

---

ibtk/include/ibtk/libmesh_utilities.h
src/IB/IIMethod.cpp

We encounter the same issue here as we do in IBFEMethod - serialized vectors are
not set up as ghosted when they should be. It looks like newer versions of
libMesh fixed this, but it is definitely present in 1.5.1.

Fix IIM restarts with older versions of libMesh.

---

CMakeLists.txt
cmake/IBAMRConfig.cmake.in
doc/cmake.md

This PR adds two minor tweaks to the CMake build system:
1. If we are using a new enough version of clang, then automatically turn off some warnings that generate huge amounts of line noise
2. Save the flags we use when compiling IBAMR - this will let users set things up in their own projects. These don't include preprocessor directives like defining NDIM.
I'll put up a version of this for 0.10.0 later.
GitHub for the …

Enable a small number of flags by default in CMake.

---

CMakeLists.txt

If we use the MPI compiler wrappers then MPI_C_LIBRARIES is empty, as there are no additional libraries for us to link against. In this case this check will unconditionally fail since whatever MPI library an external dependency links against will obviously not be in that empty list.
Hence, only run the check if MPI_C_LIBRARIES has something in it. Regardless of the link check, we use PETSc's preprocessor logic to verify that we have the same MPI library version, so we still have pretty good protection against mixing MPI implementations by accident.
Like #1397, this is a small CMake fix that will make it easy for users to set up everything with autoibamr.
up appropriately for restarts? If so, ensure that the …

Disable checking MPI library linking if we use mpicc etc.

---

CMakeLists.txt

Another problem caught by autoibamr.
I think this is a CMake bug - if hypre and PETSc are installed in the same place then CMake puts calls like
execute_process(COMMAND /usr/bin/install_name_tool
-delete_rpath "/Users/drwells/autoibamr/packages/petsc-3.13.1/lib"
"$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libIBAMR2d.dylib")
inside src/cmake_install.cmake. This doesn't make any sense: that path doesn't need to be removed from the library prior to installation because it is for an external dependency. Furthermore, those paths are duplicated, which leads to errors of the form
error: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: 
for: /Users/drwells/autoibamr/packages/IBAMR-0.10.0-rc1/lib/libIBAMR3d.dylib
(for architecture x86_64) option "-add_rpath …

Work around an rpath problem on macOS.

---

CMakeLists.txt

Newer versions of CMake let you set this, but in our case it doesn't matter - we never compile standalone boost files so the language version attached to them is never used.
Like the other such patches, since we didn't change anything in the library, the normal checklist isn't helpful.
Same as #1412 but for 0.10. Part of #1409

CMake: fix compatibility with 3.15-3.19.

---

CMakeLists.txt
doc/news/changes/0.10.0-vs-0.10.1.html

Same as #1417 but for 0.10.1. Part of #1409.

Fix mpi compiler wrapper detection 0.10.1

---

CMakeLists.txt

Another build system fix - thanks to @jabrown893 and @labdala for helping me track this down.
It is well-known that CMake does not handle MPI compiler wrappers well. In particular, if we provide our own compiler wrappers and have a system copy of MPI installed, then CMake will use both, causing a disaster. This patch tries to detect if we are using an MPI compiler wrapper and if so it sets `MPI_ROOT` to the directory up from the executables.

Fix another MPI compiler wrapper case.

---

examples/IBLevelSet/ex3/CMakeLists.txt

Yuck, another build system problem that I should have caught before - this is more evidence that we need better CI.
I compile the library without libMesh, and I compile the examples, but apparently I haven't done both recently.

Mark an example that requires libMesh as such.

---

examples/CMakeLists.txt

Equivalent of #1416 for master.

Fix compilation of examples that depend just on boost.

---

CMakeLists.txt
doc/cmake.md
doc/news/changes/minor/20220221DavidWells

SILO's source code contains the following explanation:
in configure.ac: hence, if we link against HDF5 correctly then we will always get the correct zlib propagation.
To the best of my knowledge, we/SAMRAI never use zlib compression for writing out Eulerian data, so the only place it might get used is inside SILO. I tested this on a machine without any installation of zlib (i.e., with headers or without) and its fine.
That being said - I'm not sure that we are pulling in HDF5's full link interface with autotools so I left things alone there. CMake will use hdf5's compiler wrappers to get the full link interface, and I don't think we have that set up in autotools.
up appropriately for restarts? If so, ensure …

Remove ZLIB as an explicit dependency.

---

.github/cmake/configure_centos7.cmake
.github/workflows/push-pull.yml
CMakeLists.txt
ibtk/contrib/boost/boost/math/policies/policy.hpp

Now that the CI is set up its relatively easy to copy and paste what we have to add more testers.
We can't catch bugs like #1425 with our present configurations since we only use relatively recent compilers. This PR adds another tester based on CENTOS 7 (first released in 2014, formally supported through 2024) which uses gcc 4.8, libmesh 1.1 and PETSc 3.7.7.
This might take a few rounds to get working correctly.

Test oldest configuration

---

doc/news/changes/minor/20220308AaronBarrett
src/adv_diff/AdvDiffHierarchyIntegrator.cpp

The advection diffusion solver only draws scalar and vector quantities correctly. This adds a check if the advected quantity is a tensor, and defaults to outputting every component of the variable.

Fix how the advection diffusion integrators output variables with different depths.

---

src/IB/IBRedundantInitializer.cpp

The line
hierarchy->getPatchLevel(vertex_level_number);
fails inside SAMRAI with a difficult to understand type casting error for some
tests in which the grid is not fully set up at the point when this is called.
Fortunately the fix is pretty easy - we don't actually need to account for the
periodic shift to get the actual position of a vertex, we just need to know
which directions are periodic since those can be ignored when we check for
points outside the physical domain.
Thanks @abarret for pointing this out.
in release mode). If possible, …

Fix the 'point outside' check with some other examples.

---

doc/news/changes/incompatibilities/20200426AaronBarrett
examples/IB/explicit/ex0/example.cpp
examples/IBLevelSet/ex0/example.cpp
include/ibamr/IBRedundantInitializer.h
src/IB/IBRedundantInitializer.cpp
tests/IB/explicit_ex0.cpp
tests/IB/ib_body_force.cpp
tests/IB/ib_body_force_kirchhoff.cpp
tests/IBTK/child_integrators.cpp
tests/wave_tank/nwt_cylinder.cpp

IBRedundantInitializer uses function pointers with no way to forward object states. This adds in `void *` to all the arguments with defaults of `nullptr` to bring the class in line with what happens in the rest of the library.
This change can potentially break user codes, but only requires adding the parameter `void *` to any functions that are passed to IBRedundantInitializer.

Add capture variables to function pointers in IBRedundantInitializer.

---

doc/news/changes/minor/20220428DavidWells
ibtk/src/lagrangian/FEProjector.cpp
tests/IBFE/explicit_ex4.cpp
tests/IIM/flow_past_cylinder.cpp
tests/IIM/flow_past_sphere.cpp
tests/IIM/hagen_poiseuille_flow.cpp
tests/IIM/poiseuille_flow.cpp
tests/IIM/taylor_couette_2d.cpp
tests/IIM/taylor_couette_3d.cpp
tests/IIM/taylor_couette_3d.mpirun=2.output

Fixes #1053. I don't have the old timing numbers but CG is clearly better when we look at the actual solver wall times (and not just callgrind).
I had to adjust a few tests to use low solver tolerances - we should always do this in the test suite anyway to be robust w.r.t. minor changes in algorithms.

Switch to using CG for FE projections.

---

CMakeLists.txt
cmake/IBAMRConfig.cmake.in

Fixes #1445.
This fixes a couple of bugs with our CMake boost detection. New versions of boost install CMake scripts which do not work well with CMake versions older than 3.19: in particular, they ignore the option for 'do not search in system directories'. I fixed that problem, which also fixed the issue with detecting incomplete boost installations. While I was at it I added checks to make sure we can successfully compile the boost headers we need.

Improve boost detection

---

doc/news/changes/minor/20220526AaronBarrett
include/ibamr/INSHierarchyIntegrator.h
include/ibamr/INSVCStaggeredHierarchyIntegrator.h
include/ibamr/INSVCStaggeredNonConservativeHierarchyIntegrator.h
src/navier_stokes/INSCollocatedHierarchyIntegrator.cpp
src/navier_stokes/INSHierarchyIntegrator.cpp
src/navier_stokes/INSStaggeredHierarchyIntegrator.cpp
src/navier_stokes/INSVCStaggeredConservativeHierarchyIntegrator.cpp
src/navier_stokes/INSVCStaggeredHierarchyIntegrator.cpp
src/navier_stokes/INSVCStaggeredNonConservativeHierarchyIntegrator.cpp
tests/IBTK/child_integrators.2_hierarchies.input
tests/IBTK/child_integrators.2_hierarchies.output
tests/IBTK/child_integrators.cpp

It's useful to be able to evolve different fields with different kinds of advection diffusion integrators. This replaces the single `AdvDiffHierarchyIntegrator` object in `INSHierarchyIntegrator` with a vector of integrators.
Note that we can not use a similar strategy as `IBStrategySet` for this as the INS solver needs to directly interact with the advection diffusion solver.
Also, for the VC INS solvers, the correct index of the advection diffusion integrator that owns the density or viscosity variable needs to be set.
in release mode). If …

Allow multiple AdvDiffHierarchyIntegrator objects to be registered with the INS solvers.

---

.github/workflows/push-pull.yml

For various reasons, picking the compilation cache from the libMesh build in the non-libMesh build just doesn't work that well. Lets just save the cache we generate here instead.

CI: pick a better key for the no-libMesh build.

---

.github/workflows/push-pull.yml

More CI stuff - I noticed in #1465 that we are not actually compiling the examples under cmake with warnings turned into errors.

Compile examples with warnings

---

CMakeLists.txt
cmake/IBAMRConfig.cmake.in
src/CMakeLists.txt

One comment is out of date - the other two could use grammar improvements.
Since this doesn't modify the library itself the usual checklist doesn't apply.

Clean up some CMake comments.

---

ibtk/src/math/PoissonUtilities.cpp

I missed this class while fixing harmonic averaging to avoid division by zero. I also checked through git grep to make sure no other files require a harmonic average fix. The test suite runs fine.

fix harmonic avg in PoissonUtilities

---

.github/workflows/push-pull.yml

We should automatically check that all our examples work with the oldest set of dependencies - in practice this really means checking libMesh since that's the only external dependency we typically use in some significant way in examples.

CI: compile more examples on CENTOS-7.

---

ibtk/include/ibtk/BoxPartitioner.h
ibtk/include/ibtk/StableCentroidPartitioner.h
ibtk/src/lagrangian/LSiloDataWriter.cpp
src/IB/IBInstrumentPanel.cpp

- We get some deprecated header warnings from libMesh
- We have some unused variables when SILO isn't installed

Fix some minor warnings under clang.

---

.gitignore

The usual checklist does not apply.

update .gitignore to include .clang-tidy files

---

CMakeLists.txt

1. Crash if we cannot determine the Fortran link interface. The error message here is ugly but its better to crash here than at link time.
2. Print a better message w.r.t. how mpic++ is used.
Normal checklist doesn't apply.

Add two minor CMake improvements.

---

src/IB/FEMechanicsBase.cpp

We should set these values immediately before 'assemble'. I don't think this will make a significant difference since we do MAT_IGNORE_ZERO_ENTRIES elsewhere but not allocating them at all is an improvement.

FEMechanicsBase: fix the component coupling.

---

cmake/IBAMRConfig.cmake.in

The previous version worked correctly when flags were explicitly set but does not work correctly when we use a CMake build type.
The fix is quite verbose since this file uses CMake's templating syntax and standard variables are not available.
It's a build system patch so the normal checklist doesn't apply.

CMake: fix flag exporting when using CMAKE_BUILD_TYPE.

---

.github/workflows/push-pull.yml

cache@v2 uses some deprecated stuff so we need to upgrade.
Lets see if the rest of our CI still works with this.

CI: upgrade to cache@v3.

---

CMakeLists.txt

What we presently have is fine for IBAMR apps but we need another tweak to make things work with external dependencies which also depend on HDF5.
Followup to #1532 - hopefully this will work for both linkers.

Fix the link order again.

---

include/ibamr/IBInterpolantHierarchyIntegrator.h
src/IB/IBExplicitHierarchyIntegrator.cpp
src/IB/IBHierarchyIntegrator.cpp
src/IB/IBImplicitStaggeredHierarchyIntegrator.cpp
src/IB/IBInterpolantHierarchyIntegrator.cpp

We need to move a few things around to get marker points working. In particular - if a class sets up an object in `preprocess` it should be responsible for it in `postprocess` and classes should be responsible for managing their own class members. Hence - this patch moves a bunch of stuff down to `IBHierarchyIntegrator`, which will make it simpler to implement marker points as we can compute them from the INS hierarchy integrator before it gets reset.
that we do not need …

Refactor pre and post timestep

---

src/IB/IBExplicitHierarchyIntegrator.cpp

Fixes #1592 (probably).
I cannot reproduce this (and our trusty gcc 4.8 CI tester is happy with the present version) but some older compilers have trouble converting `{}` into various aggregate types. Work around it by being explicit with what we return.

Fix a compilation error.

---

include/ibamr/IBInstrumentPanel.h
src/IB/IBInstrumentPanel.cpp

There's no reason to use this instead of snprintf().
To the best of my knowledge, this class isn't finished (e.g., there is no way to actually specify the locations of meters) so I did not add any tests. We should include this in the release since some platforms are finally deprecating sprintf().

Remove sprintf().

---

ibtk/include/ibtk/PoissonFACPreconditionerStrategy.h
ibtk/src/solvers/impls/PoissonFACPreconditionerStrategy.cpp

Currently, if the provided RHS patch index does not have the same ghost cell width as that provided in the constructor (or database), you get a very obtuse error message about `CoarsenSchedule` consistency. This adds a check in `initializeOperatorState()` to print a more helpful message.

Add a check for ghost cell consistency in the PoissonFACPreconditionerStrategy

---

examples/IIM/ex0/input2d
examples/IIM/ex0/input3d
examples/IIM/ex2/input3d
examples/IIM/ex3/input2d
examples/IIM/ex4/input2d.LMred
examples/IIM/ex4/input2d.SMred
examples/IIM/ex7/input2d
include/ibamr/IIMethod.h
src/IB/IIMethod.cpp

It's important that we can easily test activating 1) only the pressure correction 2) only the viscous term correction, 3) the pressure and viscous terms corrections but not the interpolation correction, 4) viscous term and interpolation correction but not the pressure correction and 5) all the corrections or none of them. 
Additionally, it helps to be able to provide ad-hoc tolerance values related to the intersection algorithm via the input file, for instance in an application with extreme physical/discretization parameters for which additional digits of precision may become important. 
or tests should be added. New …

A few jump options /cleanup

---

doc/news/changes/incompatibilities/20231114DavidWells
include/ibamr/INSHierarchyIntegrator.h
src/IB/IBHierarchyIntegrator.cpp
src/navier_stokes/INSCollocatedHierarchyIntegrator.cpp
src/navier_stokes/INSHierarchyIntegrator.cpp
src/navier_stokes/INSStaggeredHierarchyIntegrator.cpp
src/navier_stokes/INSVCStaggeredHierarchyIntegrator.cpp
tests/IBTK/child_integrators.2_hierarchies.output
tests/IBTK/child_integrators.output

Presently, the CFL number is only available through the logfile. This PR consolidates where we calculate it (the INS solver is always responsible) and makes it available via `getCurrentCFLNumber()`.

Add an API for getting the CFL number.

---

src/adv_diff/AdvDiffSemiImplicitHierarchyIntegrator.cpp
tests/IBTK/hierarchy_callbacks.output

I have updated the diffusion coefficient in integrateHierarchy with the new values. Now I initialize the LHS and RHS of the adv diff equation in the integrateHierarchy and preprocessIntegrateHierarchy, respectively. Please take a look. All the existing adv_diff tests pass with this patch. I can also add a new test if you have any suggestions.

Fix bug related to diffusion coef in AdvDiffSemiImplicit class

---

ibtk/include/ibtk/LDataManager.h
include/ibamr/ConstraintIBKinematics.h
include/ibamr/IBFEDirectForcingKinematics.h

`Serializable` inherits from `DescribedClass` so we don't need to do this. I also made the order of inheritance uniform (`Serializable is now always last).

Cleanup basic inheritance

---

doc/news/changes/incompatibilities/20240123AaronBarrett
examples/IB/explicit/ex6/IBSimpleHierarchyIntegrator.cpp
examples/IB/explicit/ex6/IBSimpleHierarchyIntegrator.h
ibtk/include/ibtk/HierarchyIntegrator.h
ibtk/src/utilities/HierarchyIntegrator.cpp
include/ibamr/AdvDiffPredictorCorrectorHierarchyIntegrator.h
include/ibamr/AdvDiffSemiImplicitHierarchyIntegrator.h
include/ibamr/BrinkmanAdvDiffSemiImplicitHierarchyIntegrator.h
include/ibamr/IBExplicitHierarchyIntegrator.h
include/ibamr/IBImplicitStaggeredHierarchyIntegrator.h
include/ibamr/IBInterpolantHierarchyIntegrator.h
include/ibamr/INSCollocatedHierarchyIntegrator.h
include/ibamr/INSStaggeredHierarchyIntegrator.h
include/ibamr/INSVCStaggeredConservativeHierarchyIntegrator.h
include/ibamr/INSVCStaggeredNonConservativeHierarchyIntegrator.h
src/IB/IBExplicitHierarchyIntegrator.cpp
src/IB/IBImplicitStaggeredHierarchyIntegrator.cpp
src/IB/IBInterpolantHierarchyIntegrator.cpp
src/adv_diff/AdvDiffPredictorCorrectorHierarchyIntegrator.cpp
src/adv_diff/AdvDiffSemiImplicitHierarchyIntegrator.cpp
src/adv_diff/BrinkmanAdvDiffSemiImplicitHierarchyIntegrator.cpp
src/navier_stokes/INSCollocatedHierarchyIntegrator.cpp
src/navier_stokes/INSStaggeredHierarchyIntegrator.cpp
src/navier_stokes/INSVCStaggeredConservativeHierarchyIntegrator.cpp
src/navier_stokes/INSVCStaggeredNonConservativeHierarchyIntegrator.cpp
tests/IBTK/child_integrators.2_hierarchies.output
tests/IBTK/child_integrators.cpp
tests/IBTK/child_integrators.output

Fixes #1636. This introduces a new protected pure virtual function `doIntegrateHierarchy()` in `HierarchyIntegrator`. Previously, `integrateHierarchy()` was designed to do two things: (1) perform an integration cycle and (2) execute post integration callbacks. The design principle was that the class furthest down the hierarchy ends up calling the post integration callbacks. This causes problems (e.g. in the phase change code from @amneetb and @Raamkrishnan) where child classes want to call the parent class's `integrateHierarchy()` to perform action (1) but not (2).
This changes the design principle so that the parent class `HierarchyIntegrator::integrateHierarchy()` executes post integration callbacks after `doIntegrateHierarchy()` is called. Child classes no longer need to execute the …

Introduce doIntegrateHierarchy() virtual function.

---

attest

I updated things on my local machine and that has necessitated some fixes - I have a few more minor updates for the mailing list and ibsamrai2.
This version of openmpi reads a different set of environment variables. It is infrastructure so the normal list does not apply.

Update attest to work with openmpi 5.

---

doc/news/changes/major/20240311DavidWells
ibtk/include/ibtk/HierarchyIntegrator.h
ibtk/src/utilities/HierarchyIntegrator.cpp
include/ibamr/INSStaggeredHierarchyIntegrator.h
src/navier_stokes/INSStaggeredHierarchyIntegrator.cpp

Follow-up to a conversation I had with @marshallrdavey - it turns out that most of the stuff we store in a restart database is never actually read. Removing things we don't ever use, like plot-only variables, shrinks its size by about 50%.

Clean up restart db

---

README.md
doc/pull_request_template.md

This makes things a little clearer. One thing we need to manually do now is make sure that all the outstanding PR authors are aware that they will need to run `make indent` since updating the checklist on `master` does not update it in their PRs.
It's an infrastructure change so the normal checklist doesn't apply.

Add some more documentation on clang-format.

---

doc/news/changes/minor/20240515DavidWells
ibtk/src/utilities/HierarchyIntegrator.cpp
include/ibamr/INSCollocatedHierarchyIntegrator.h
include/ibamr/INSHierarchyIntegrator.h
include/ibamr/INSStaggeredHierarchyIntegrator.h
include/ibamr/INSVCStaggeredHierarchyIntegrator.h
src/navier_stokes/INSCollocatedHierarchyIntegrator.cpp
src/navier_stokes/INSHierarchyIntegrator.cpp
src/navier_stokes/INSStaggeredHierarchyIntegrator.cpp
src/navier_stokes/INSVCStaggeredHierarchyIntegrator.cpp
tests/navier_stokes/navier_stokes_01_2d.collocated.input
tests/navier_stokes/navier_stokes_01_2d.collocated.output

Part of #1697.
This PR consolidates all the ways we handle computing the vorticity for tagging into two places instead of scattering them around the INS classes. I also added some tests for the collocated solver since, surprisingly, there were none in the test suite.

Only compute vorticity when we need it.

---

ibtk/src/math/SAMRAIGhostDataAccumulator.cpp

I noticed this while profiling the heart model with massif - storing all these indexing arrays isn't negligible. We can get rid of the global indices after setting up the PETSc vector, which helps a little.

Deallocate and remove an unused data index.

---

ibtk/src/utilities/HierarchyIntegrator.cpp
include/ibamr/IBStrategy.h
src/IB/IBFEMethod.cpp
src/IB/IBStrategy.cpp

Don't save workload data in the restart database.

---

src/navier_stokes/INSVCStaggeredHierarchyIntegrator.cpp

The test added in #1717 aborts on `master` because of this typo from the vorticity patches. @Raamkrishnan thanks again for adding this test!

Fix a level number check.

---

scripts/formatting/compile-clang-format
scripts/formatting/download-clang-format

based on updates to the deal.II versions of these scripts.
This is just an infrastructure update so the normal list doesn't apply.

Update clang-format scripts.

---

examples/wave_tank/ex0/LSLocateColumnInterface.cpp
examples/wave_tank/ex0/example.cpp
examples/wave_tank/ex0/input2d
examples/wave_tank/ex0/input2d_5thOrderStokes
examples/wave_tank/ex0/input2d_CaseA
examples/wave_tank/ex0/input2d_CaseA_IrregularWave
examples/wave_tank/ex0/input2d_CaseB
examples/wave_tank/ex0/input2d_CaseC
examples/wave_tank/ex0/input3d
examples/wave_tank/ex1/example.cpp

Making the sign of gas level set consistent in wave_tank ex0 and ex1

---

doc/news/changes/minor/20240907BoyceGriffith
include/ibamr/StaggeredStokesProjectionPreconditioner.h
src/navier_stokes/StaggeredStokesProjectionPreconditioner.cpp
tests/navier_stokes/navier_stokes_01_2d.projection_preconditioner_skip_velocity_solve.input
tests/navier_stokes/navier_stokes_01_2d.projection_preconditioner_skip_velocity_solve.output
tests/navier_stokes/navier_stokes_01_3d.projection_preconditioner_skip_velocity_solve.input
tests/navier_stokes/navier_stokes_01_3d.projection_preconditioner_skip_velocity_solve.output

If viscosity or time step size is very small, then we can skip solving the velocity block in the projection preconditioner without needing to take many more overall Stokes solver iterations.

add an option to skip the velocity solve in the projection preconditioner

---

src/IB/IBFEMethod.cpp
src/IB/IBFESurfaceMethod.cpp

**Issue:** If a surface mesh is provided (a body mesh is needed) `IBFEMethod `can run but will fail with the error `"Assertion `length != static_cast<Real>(0.)' failed."`  This is coming from trying to make a vector of zero length a unit vector.
**Fix 1:** Check the mesh dimension in the constructors of `IBFEMethod `to make sure the mesh dimension is the same as the physical dimension.
**Fix 2:** Check the mesh dimension in the constructors of `IBFESurfaceMesh` to make sure the mesh dimension is 1 less than the physical dimension.

Michaelli/ibfe/check mesh dim for IBFEMethod and IBSurfaceMethod

---

CMakeLists.txt
cmake/IBAMRConfig.cmake.in
configure
ibtk/configure
m4/configure_silo.m4

Two small build system fixes:
1. Fix some issues with boost that only occur when the user installs boost on their own in a non-system directory
2. Enforce using SILO 4.11 or newer. I saw someone use SILO 4.10 last week, which is not compatible with IBAMR - it is not const-correct so we get compilation errors.

Cmake fixes + bump silo version

---

ibtk/include/ibtk/ibtk_enums.h
include/ibamr/IBMethod.h
src/IB/IBMethod.cpp

Currently, the IB data in `IBMethod` during the middle of a time step is inaccessible outside of `IBMethod`. The data is owned by the class `IBMethod` and therefore can not be retrieved via `LDataManager`. This PR makes the get functions public.

Make get functions public in IBMethod.

---

.github/workflows/push-pull.yml

GCC 9 is the oldest more-or-less still maintained compiler we should support.

Add a second new CI runner with updated dependencies.

---

cmake/IBAMRConfig.cmake.in

*Edit* The original version of this didn't work for several reasons, but we can solve the underlying problem in a different way.
Downstream projects will now be able to write something like
```cmake
SET(CMAKE_CXX_COMPILER "${IBAMR_CXX_COMPILER}")
```
etc. This works around a problem where autoibamr will use MPI compiler
wrappers but a user might not set those again when compiling a dependent
project, leading to compilation errors.
that we …

Save the compilers we use.

---

.github/workflows/push-master.yml
.github/workflows/push-pull.yml

Fixes #1774 (this is the last item on the release TODO list). Fixing the caching should make PRs run about twice as fast.
Since this is a CI change the normal checklist doesn't apply.

Cleanup CI caching

---

ibtk/src/solvers/impls/FACPreconditioner.cpp

`FACPreconditioner` has a specialized code path that is used with V-cycles without presmoothing. We can avoid copying one `SAMRAIVectorReal` and duplicating another.

avoid vector copies in the FAC preconditioner

---

include/ibamr/IBHierarchyIntegrator.h
src/IB/IBEulerianSourceFunction.cpp
src/IB/IBExplicitHierarchyIntegrator.cpp
src/IB/IBFEMethod.cpp
src/IB/IBHierarchyIntegrator.cpp
tests/IBFE/explicit_ex4_2d.source_test.output

This is the first of two PRs which will fix a bug where we didn't correctly update sources in calls to
`INSHierarchyIntegrator::regridProjection()`, which resulted in reading undefined data and therefore arbitrary velocity values. To begin, this commit makes it possible to compute sources outside of the normal timestepping loop and also modifies `IBEulerianSourceFunction` to work on the entire `PatchHierarchy` (instead of single patches) at once.
We don't use this implementation of sources in four-chambered-heart or Cardinal: those apps directly add it to the INS integrator. We do have a test for these sources in IBAMR and I checked that, in addition to passing, it has the same visual output as before. …

`IBHierarchyIntegrator` etc.: refactor sources derived from `IBStrategy`.

---

ibtk/include/ibtk/libmesh_utilities.h
ibtk/src/lagrangian/FEDataManager.cpp
ibtk/src/lagrangian/FEMapping.cpp
ibtk/src/lagrangian/StableCentroidPartitioner.cpp
ibtk/src/utilities/libmesh_utilities.cpp
src/IB/IBFEInstrumentPanel.cpp
src/level_set/FESurfaceDistanceEvaluator.cpp
tests/IBFE/explicit_ex4.cpp
tests/IBFE/instrument_panel_01.cpp
tests/IBFE/interpolate_velocity_01.cpp
tests/IBTK/bounding_boxes_01.cpp
tests/IBTK/mapping_01.cpp
tests/IBTK/multilevel_fe_01.cpp
tests/spread/spread_02.cpp

Similar to the other PR - this one removes all the old workarounds which aren't necessary now that 1.7 is the oldest supported version.

libMesh: remove old workarounds.

---

examples/IB/explicit/ex6/IBSimpleHierarchyIntegrator.cpp

Fixes `examples/IB/explicit/ex6`.
(I think that the usual checklist does not apply.)

fix examples/IB/explicit/ex6
