examples/IBFE/explicit/ex0/input2d
examples/IBFE/explicit/ex0/main.cpp
ibtk/include/ibtk/FEDataManager.h
ibtk/include/ibtk/LEInteractor.h
ibtk/src/lagrangian/FEDataManager.cpp
ibtk/src/lagrangian/LEInteractor.cpp
src/IB/IBFEMethod.cpp

@boyceg : Please take a look at the first shot of 2d MLS LEInteractor::interpolation routine for IB_4 kernel.

Moving least squares approach to do one-sided interpolation and spreading

---

examples/IBFE/explicit/ex0/input2d
examples/IBFE/explicit/ex1/input2d
examples/IBFE/explicit/ex2/input2d
examples/IBFE/explicit/ex2/input3d
examples/IBFE/explicit/ex3/input2d
examples/IBFE/explicit/ex4/input2d
examples/IBFE/explicit/ex4/input3d
examples/IBFE/explicit/ex5/input2d
examples/IBFE/explicit/ex5/input3d
examples/IBFE/explicit/ex6/input2d
examples/IBFE/explicit/ex7/input2d.caseC
examples/IBFE/explicit/ex7/input2d.caseS2
examples/IBFE/explicit/ex7/input2d.caseSP
examples/IBFE/explicit/ex8/input2d
include/ibamr/IBFEMethod.h
src/IB/IBFEMethod.cpp

* Removes frictional penalty constraint method from IBFEMethod.
* Removes support for non-IB interpolation/spreading algorithms.
* Corresponding updates to IBFE input files.

Clean up IBFE implementation

---

ibtk/include/ibtk/private/IndexUtilities-inl.h

Clean-up IndexUtilities implementation

---

include/ibamr/IBHierarchyIntegrator.h
src/IB/IBExplicitHierarchyIntegrator.cpp
src/IB/IBHierarchyIntegrator.cpp
src/IB/IBImplicitStaggeredHierarchyIntegrator.cpp

* add IBHierarchyIntegrator::preprocessIntegrateHierarchy()
* move time step size change monitoring into IBHierarchyIntegrator from IBExplicitHierarchyIntegrator

refactoring IB time step size change monitoring

---

tests/Stokes-IB/test0/main.cpp

* Accounting for pre-release version of petsc - 3.6
* Accounting for new BC handling for Stokes operator.
* Adding VecAssemblyBegin/End() after VecSetValue()

Fixing Stokes-IB/test0

---

src/IB/NonbondedForceEvaluator.cpp
src/IB/NonbondedForceEvaluator.h
src/IB/Wall.cpp
src/IB/Wall.h
src/IB/WallForceEvaluator.cpp
src/IB/WallForceEvaluator.h

This finally incorporates classes developed by @sddelong for his PhD research.

add classes for non-bonded interaction forces between IB points

---

ibtk/include/ibtk/PETScLevelSolver.h
ibtk/src/solvers/impls/PETScLevelSolver.cpp
include/ibamr/StaggeredStokesPETScLevelSolver.h
include/ibamr/StaggeredStokesPETScMatUtilities.h
src/navier_stokes/StaggeredStokesPETScLevelSolver.cpp
src/navier_stokes/StaggeredStokesPETScMatUtilities.cpp

Extending interface of PETScLevelSolver for ASM and FieldSplit PC's

---

ibtk/configure
ibtk/configure.ac
ibtk/examples/Makefile.am
ibtk/examples/PETScOps/Makefile.am
ibtk/examples/PETScOps/Makefile.in
ibtk/examples/PETScOps/ProlongationMat/Makefile.am
ibtk/examples/PETScOps/ProlongationMat/Makefile.in
ibtk/examples/PETScOps/ProlongationMat/README
ibtk/examples/PETScOps/ProlongationMat/input2d
ibtk/examples/PETScOps/ProlongationMat/input3d
ibtk/examples/PETScOps/ProlongationMat/main.cpp
ibtk/src/math/PETScMatUtilities.cpp
ibtk/src/math/PETScVecUtilities.cpp

This tests PETSc prolongation matrix for RT0 and LINEAR operators

Adding test cases for PETSc prolongation matrix

---

examples/ConstraintIB/eel2d/IBEELKinematics.cpp
examples/ConstraintIB/knifefish/KnifeFishKinematics.cpp
src/IB/ConstraintIBMethod.cpp

fixed ConstraintIBMethod restart bug and updated examples

---

src/navier_stokes/INSStaggeredStochasticForcing.cpp

Extra stress variables in stochastic forcing function were not deallocated correctly.
Fixes issue #144

Fix stochastic forcing function

---

src/IB/ConstraintIBMethod.cpp

Fixed small bug in 2D torque calculation

Fix torque calculation in 2D for ConstraintIBMethod

---

Makefile.in
ibtk/include/ibtk/PETScKrylovLinearSolver.h
ibtk/src/solvers/impls/PETScKrylovLinearSolver.cpp

We need support for solving systems of equations that involve "extra" variables (in addition to Cartesian grid data).

support for "augmented" linear solves

---

tests/Stokes-IB/test0/main.cpp
tests/Stokes-IB/test1/input2d.shell

@walterjunjun Try it.
@boyceg You can merge it after Walter is happy :-)

updating stokes-ib tests

---

ibtk/src/math/PatchMathOps.cpp
ibtk/src/math/fortran/flux2d.f.m4
ibtk/src/math/fortran/flux3d.f.m4

@boyceg : This fixes the issue I opened a while back (https://github.com/IBAMR/IBAMR/issues/160). Could you review the new kernels?

Fixing gradient computation bug

---

examples/navier_stokes/ex1/Makefile.am
examples/navier_stokes/ex1/Makefile.in
examples/navier_stokes/ex1/input3d
examples/navier_stokes/ex1/input3d.test

A 3D perturbed periodic shear layer problem.

adding 3D input files for example navier_stokes/ex1

---

ibtk/src/solvers/impls/PETScLevelSolver.cpp

Fixes the compile issue for PETSc versions lower than 3.8

Added check for PETSc version.

---

src/IB/IBFEMethod.cpp

moving Q rhs assembly out of inner qp loop

---

include/ibamr/IBFEMethod.h
src/IB/IBFEMethod.cpp

initial velocity for IBFE

---

src/IB/IBFEMethod.cpp

Until we update to C++11, there are some places where we cannot store vectors of UniquePtr<T>.

switch to a container of dumb pointers for now

---

configure
configure.ac
ibtk/configure
ibtk/configure.ac
ibtk/m4/configure_boost.m4
m4/configure_boost.m4

We need to detect Boost before libMesh in configure.

swapping boost detection order

---

include/ibamr/IBFEInstrumentPanel.h
src/IB/IBFEInstrumentPanel.cpp

we are also adding the option to use the libMesh QGrid quadrature rule.

changing IBFE meter meshes to pizza shaped ones

---

examples/IBFE/explicit/ex0/example.cpp
examples/IBFE/explicit/ex1/example.cpp
examples/IBFE/explicit/ex3/example.cpp
examples/IBFE/explicit/ex4/example.cpp
ibtk/include/ibtk/FEDataManager.h
ibtk/src/lagrangian/FEDataManager.cpp
src/IB/IBFEMethod.cpp
src/IB/IBFESurfaceMethod.cpp

For nodal quadrature rules (QTRAP for FIRST order elements, QSIMPSON for SECOND order elements), Lagrangian-Eulerian interaction can be performed directly at the nodes, without looping over the elements.

specialized nodal spreading and interpolation

---

examples/adv_diff/ex0/QInit.cpp
examples/adv_diff/ex0/UFunction.cpp
examples/advect/QInit.cpp
examples/advect/UFunction.cpp
examples/level_set/ex0/LSLocateInterface.cpp
examples/level_set/ex1/LSLocateInterface.cpp
examples/level_set/ex1/example.cpp
examples/multiphase_flow/ex0/LSLocateCircularInterface.cpp
examples/multiphase_flow/ex1/LSLocateCircularInterface.cpp
examples/multiphase_flow/ex1/LSLocateGasInterface.cpp
examples/multiphase_flow/ex1/TagLSRefinementCells.cpp
examples/multiphase_flow/ex2/LSLocateCircularInterface.cpp
examples/multiphase_flow/ex2/LSLocateGasInterface.cpp
examples/multiphase_flow/ex2/TagLSRefinementCells.cpp
ibtk/examples/PhysBdryOps/example.cpp

I cannot compile the examples without the namespace qualification.

Disambiguate SAMRAI::hier::Index and Eigen::Index.

---

examples/ConstraintIB/flow_past_cylinder_HF/example.cpp
examples/level_set/ex1/LSLocateInterface.cpp
examples/multiphase_flow/ex0/LSLocateCircularInterface.cpp
examples/multiphase_flow/ex0/SetFluidProperties.cpp
examples/multiphase_flow/ex1/GravityForcing.cpp
examples/multiphase_flow/ex1/LSLocateCircularInterface.cpp
examples/multiphase_flow/ex1/LSLocateGasInterface.cpp
examples/multiphase_flow/ex1/TagLSRefinementCells.cpp
examples/multiphase_flow/ex2/GravityForcing.cpp
examples/multiphase_flow/ex2/LSLocateCircularInterface.cpp
examples/multiphase_flow/ex2/LSLocateGasInterface.cpp
examples/multiphase_flow/ex2/TagLSRefinementCells.cpp

Fix some unused variable warnings in the examples.

---

src/IB/IBFECentroidPostProcessor.cpp
src/IB/IBFEMethod.cpp
src/IB/KrylovMobilitySolver.cpp
src/IB/NonbondedForceEvaluator.cpp
src/navier_stokes/StaggeredStokesPhysicalBoundaryHelper.cpp

Remove some unused variables.

---

examples/ConstraintIB/falling_sphere/Makefile.am
examples/ConstraintIB/falling_sphere/Makefile.in
examples/level_set/ex0/Makefile.am
examples/level_set/ex0/Makefile.in
examples/level_set/ex0/test_main.cpp
examples/level_set/ex1/Makefile.am
examples/level_set/ex1/Makefile.in
examples/level_set/ex1/test_main.cpp
examples/multiphase_flow/ex1/Makefile.am
examples/multiphase_flow/ex1/Makefile.in
examples/multiphase_flow/ex1/input2d.test
ibtk/examples/VCViscousSolver/Makefile.am
ibtk/examples/VCViscousSolver/Makefile.in

Fixing some of the gtests mentioned in https://github.com/IBAMR/IBAMR/issues/269

Fixing ConstraintIB, level set, and vc gtests

---

examples/CIBFE/ex0/example.cpp
examples/CIBFE/ex1/example.cpp
examples/IBFE/explicit/ex0/example.cpp
examples/IBFE/explicit/ex1/example.cpp
examples/IBFE/explicit/ex10/example.cpp
examples/IBFE/explicit/ex11/example.cpp
examples/IBFE/explicit/ex2/example.cpp
examples/IBFE/explicit/ex3/example.cpp
examples/IBFE/explicit/ex4/example.cpp
examples/IBFE/explicit/ex5/example.cpp
examples/IBFE/explicit/ex6/example.cpp
examples/IBFE/explicit/ex7/example.cpp
examples/IBFE/explicit/ex8/example.cpp
examples/IBFE/explicit/ex9/example.cpp
examples/multiphase_flow/ex2/example.cpp

Add libmesh exodus check

---

examples/CIB/ex0/input2d.test

This verifies that the patches in #261 fix the original problem. Everything works, of course; this just adds the change to the test made in #278.

Set write_viz_interval = 0.

---

examples/multiphase_flow/ex3/LSLocateCircularInterface.cpp
examples/multiphase_flow/ex3/TagLSRefinementCells.cpp
examples/multiphase_flow/ex3/VelocityInitialCondition.cpp

Not much to say: some versions of Eigen define `Index`, so we need to qualify `SAMRAI::hier::Index` as such.

Multiphase flow 3 warnings

---

configure
ibtk/configure
ibtk/m4/configure_libmesh.m4
m4/configure_libmesh.m4

Check for an incompatible libMesh setting.

---

examples/multiphase_flow/ex0/LSLocateCircularInterface.cpp
examples/multiphase_flow/ex0/SetFluidProperties.cpp
examples/multiphase_flow/ex1/SetFluidGasSolidDensity.cpp
examples/multiphase_flow/ex1/SetFluidGasSolidViscosity.cpp
examples/multiphase_flow/ex2/SetFluidGasSolidDensity.cpp
examples/multiphase_flow/ex2/SetFluidGasSolidViscosity.cpp
examples/multiphase_flow/ex3/SetFluidProperties.cpp
examples/multiphase_flow/ex4/GravityForcing.cpp
examples/multiphase_flow/ex4/LSLocateLayerInterface.cpp
examples/multiphase_flow/ex4/SetFluidProperties.cpp
examples/multiphase_flow/ex5/GravityForcing.cpp
examples/multiphase_flow/ex5/LSLocateColumnInterface.cpp
examples/multiphase_flow/ex5/SetFluidProperties.cpp
examples/multiphase_flow/ex5/TagLSRefinementCells.cpp
examples/multiphase_flow/ex6/GravityForcing.cpp
examples/multiphase_flow/ex6/LSLocateFluidInterface.cpp
examples/multiphase_flow/ex6/SetFluidProperties.cpp
examples/multiphase_flow/ex6/TagLSRefinementCells.cpp
examples/multiphase_flow/ex6/VelocityInitialCondition.cpp
examples/vc_navier_stokes/ex2/GravityForcing.cpp
examples/vc_navier_stokes/ex2/LSLocateCircularInterface.cpp
examples/vc_navier_stokes/ex2/SetFluidProperties.cpp
examples/vc_navier_stokes/ex2/TagLSRefinementCells.cpp
src/navier_stokes/INSVCStaggeredConservativeHierarchyIntegrator.cpp

Take over #309 on the 0.3 branch.
Part of #266.

Fix unused variable warnings 0.3

---

src/IB/IBFEPostProcessor.cpp

Redo 315 for 0.3.0

---

src/IB/IBFEDirectForcingKinematics.cpp
src/IB/IBStandardForceGen.cpp

Redo 316 for 0.3.0

---

config/configure.py

enhance error reporting for configure.new

---

ibtk/src/lagrangian/FEDataManager.cpp

fix copy-paste error in FEDataManager.cpp

---

ibtk/src/lagrangian/FEDataManager.cpp

fix copy-paste error

---

include/ibamr/IBFEInstrumentPanel.h
src/IB/IBFEInstrumentPanel.cpp

one for returning the plot directory name.

some more getter functions

---

src/IB/IBRedundantInitializer.cpp

This file does not use Eigen anyway.

Remove a hardcoded path.

---

ibtk/src/utilities/CoarsenPatchStrategySet.cpp
ibtk/src/utilities/RefinePatchStrategySet.cpp
ibtk/src/utilities/StandardTagAndInitStrategySet.cpp

Remove unused using statements and typedefs.

---

include/ibamr/INSVCStaggeredHierarchyIntegrator.h

This destructor should be virtual -- not sure how I missed this...

Adding missing virtual keyword for INSVCStaggeredHierarchyIntegrator destructor

---

include/ibamr/INSVCStaggeredHierarchyIntegrator.h

Revert "Adding missing virtual keyword for INSVCStaggeredHierarchyIntegrator destructor"

---

ibtk/examples/CCLaplace/README
ibtk/examples/CCLaplace/example.cpp
ibtk/examples/CCLaplace/input2d
ibtk/examples/CCLaplace/input3d

This PR adds a lot of comments to this example that I wrote out while trying to figure out what does what in the SAMRAI code.

Add substantial documentation to CCLaplace.

---

examples/ConstraintIB/eel2d/IBEELKinematics.cpp
examples/ConstraintIB/eel3d/IBEELKinematics3d.cpp
examples/ConstraintIB/eel3d/eelgenerator3d.cpp
examples/ConstraintIB/falling_sphere/sphereGen3d.cpp
examples/IBFE/explicit/ex8/example.cpp
examples/multiphase_flow/ex0/SetFluidProperties.cpp
examples/multiphase_flow/ex3/SetFluidProperties.cpp
examples/multiphase_flow/ex3/VelocityInitialCondition.cpp
examples/multiphase_flow/ex4/SetFluidProperties.cpp
examples/multiphase_flow/ex5/SetFluidProperties.cpp
examples/multiphase_flow/ex6/SetFluidProperties.cpp
examples/multiphase_flow/ex6/VelocityInitialCondition.cpp
examples/vc_navier_stokes/ex2/SetFluidProperties.cpp
ibtk/src/lagrangian/LSiloDataWriter.cpp
src/IB/CIBMethod.cpp
src/IB/CIBSaddlePointSolver.cpp
src/IB/IBHydrodynamicForceEvaluator.cpp
src/IB/IBInstrumentPanel.cpp
src/IB/IBRedundantInitializer.cpp
src/IB/KrylovFreeBodyMobilitySolver.cpp
src/IB/KrylovMobilitySolver.cpp
src/level_set/RelaxationLSMethod.cpp
src/navier_stokes/INSStaggeredStochasticForcing.cpp
src/navier_stokes/SurfaceTensionForceFunction.cpp
src/utilities/RNG.cpp

Changed the casting semantics to static_cast<T>.

fix casting in #359

---

ibtk/include/ibtk/FEDataManager.h

I was looking at this while working on #396 and added some comments.

Document SystemDofMapCache.

---

ibtk/include/ibtk/FEDataManager.h
ibtk/src/lagrangian/FEDataManager.cpp

Another minor spinoff from #396.

use std::unique_ptr to store SystemDofMapCaches.

---

ibtk/include/ibtk/FEDataManager.h
ibtk/include/ibtk/HierarchyIntegrator.h
ibtk/src/utilities/HierarchyIntegrator.cpp
include/ibamr/IBFEMethod.h
include/ibamr/IBFESurfaceMethod.h
include/ibamr/IBHierarchyIntegrator.h
include/ibamr/IBMethod.h
include/ibamr/IMPMethod.h
src/IB/IBHierarchyIntegrator.cpp

I spent a large part of today reviewing how we (and SAMRAI) do load balancing. This little PR is the first step in utilizing SAMRAI's very nice infrastructure for doing nonuniform load balancing: it just moves some code around so that we can get a load balancer in INSHierarchyIntegrator.

Rearrange load balancer

---

ibtk/include/ibtk/FECache.h
ibtk/include/ibtk/FEMapCache.h
ibtk/src/lagrangian/FEDataManager.cpp

This passes the test suite. I am doing some profiling now.

Add fe map cache

---

Makefile.in
configure
ibtk/Makefile.in
ibtk/config/compile
ibtk/config/config.guess
ibtk/config/config.sub
ibtk/config/depcomp
ibtk/config/install-sh
ibtk/config/missing
ibtk/configure
ibtk/contrib/muparser/config/ar-lib
ibtk/contrib/muparser/config/compile
ibtk/contrib/muparser/config/depcomp
ibtk/contrib/muparser/config/install-sh
ibtk/contrib/muparser/config/missing
ibtk/contrib/muparser/configure

This is a rerun of bootstrap on master as addressed in #438 and as a follow up to #426.

Rerun of bootstrap on master.

---

ibtk/include/ibtk/libmesh_utilities.h
ibtk/src/lagrangian/FEDataManager.cpp

This PR includes the parts of #450 that @drwells likes and omits the parts that he doesn't.

use PetscVector::get_array_read() to access local form arrays in FEDataManager

---

include/ibamr/IBFEMethod.h
src/IB/IBFEMethod.cpp

First change from #396. Getting this merged will be easier if we do it piecewise.
This doesn't change anything at the moment, but is necessary for using the SAMRAI-based partitioner.

Refactor data reinitialization in IBFEMethod.

---

ibtk/include/ibtk/FEDataManager.h
ibtk/src/lagrangian/FEDataManager.cpp
include/ibamr/IBFEMethod.h
src/IB/IBFEMethod.cpp

Another spinoff from #396: this implements one of the requested features (user-specified workload weights).
There is some new code in here that is not just cherry-picked from #396, so I want to test this some more (i.e., look at workload estimate pictures) before we merge, but I am happy with the current approach and management of multiple parts.

Partitioning 2d

---

README.md
doc/mainpage.dox

Hi, I saw this project at the SIAM conference - very cool software, and the applications shown were really incredible. I was reading the documentation and noticed the first link to SAMRAI gave an error. It seems their software may have moved its homepage. This PR updates that link.

Updated link to SAMRAI.

---

include/ibamr/IBFEMethod.h
src/IB/IBFEMethod.cpp

I found the bug last night when I started doing some profiling.

Workload fixes

---

ibtk/src/lagrangian/FEDataManager.cpp

We spend about 5% of our total run time in the heart model calling this function. This commit reduces the number of calls per cell from five to two (i.e., instead of calling it three times per cell in `interpWeighted` we call it once and instead of twice in `spread` now we just call it one once).
Even though the percent change is small, since we call this in a place where the load balancer has trouble (i.e., we spend a lot of time waiting for other processors to finish interpolating data) so it should also slightly decrease the amount of time we spend waiting for other processors to finish those two functions.

Cache interpolated positions.

---

doc/news/changes/major/20181012BoyceGriffith
doc/news/changes/major/20190125DavidWells
doc/news/changes/major/20190219DavidWells
doc/news/changes/major/20190321Multiple

I plan on putting out a release candidate tomorrow with what we have, so I went back and reviewed the commit history since the last release. I added a few more changelog entries so that people get credit for their contributions.
I tried to add commit log entries for everything that was not just a small bug or typo fix. I lumped all of the 'use C++11' improvements into one entry and credited everyone who sent in patches for that effort.

Add some missing changelog entries.

---

ibtk/include/ibtk/FEDataManager.h
ibtk/include/ibtk/libmesh_utilities.h
ibtk/src/lagrangian/FEDataManager.cpp
include/ibamr/IBFEPostProcessor.h
src/IB/IBFEInstrumentPanel.cpp
src/IB/IBFEMethod.cpp

Same as #500, but now for 0.4.

Update deprecated lib mesh 0.4

---

examples/IBFE/explicit/ex4/example.cpp

These files are not well optimized and are huge in 3D.

Don't write some output in 3D.

---

doc/news/changes/incompatibilities/20190327DavidWells
ibtk/src/lagrangian/FEDataManager.cpp

Its nice to disable these in the test suite.

Conditionally log statements in FEDataManager.

---

src/IB/IBFESurfaceMethod.cpp

I've seen this warning one too many times and finally decided to fix it.

Fix an uninitialized pointer warning.

---

ibtk/src/lagrangian/FEDataManager.cpp

I spent some time looking at profiling data on Saturday and I noticed that setting up this particular load vector is a huge hotspot and we can benefit from unrolling loops quite a bit. This is nearly the same technique we use in deal.II for matrix-free techniques (though there we template on the number of quadrature points, which doesn't make sense for IB computations).
It looks a bit complicated, but all we do is use templates and switch statements to dispatch to a version of the loop where both the number of variables (usually NDIM, but sometimes 1) and number of basis functions are known at compile time. There is also a fallback option where we switch to run-time computation of loop bounds for the `default` case of the switch statements.
Knowing the loop bounds helps a lot for …

Improve performance of FEDataManager by unrolling.

---

doc/news/changes/major/20190415AaronBarrett
ibtk/include/ibtk/IBTK_MPI.h
ibtk/lib/Makefile.am
ibtk/lib/Makefile.in
ibtk/src/utilities/IBTK_MPI.cpp

This adds the `IBTK_MPI` utility class to replace the `SAMRAI_MPI` class (which significantly changes in SAMRAI 3). Part 1 of 3 for separating out #287

Added IBTK_MPI utility class.

---

.gitignore
scripts/project_templates/sublime/ibamr.sublime-project.template
scripts/setup_compile_commands.sh

Some scripts and setting files to facilitate using [Sublime Text](https://www.sublimetext.com/) with IBAMR. See also the related repository, [IBAMR/sublime-settings](https://github.com/IBAMR/sublime-settings).

Sublime Text integration

---

include/ibamr/IBFEMethod.h

Spinoff from #396: this PR contains some added documentation to members of IBFEMethod I wrote.

Document members of IBFEMethod.

---

tests/IBFE/spread_01.cpp

This is what happens when I don't do any development in debug mode: this should be the last fix in the batch.
last_local_index is actually not the last local index: it is one past the last local index.

Fix a bug in a test.

---

ibtk/include/ibtk/IBTK_MPI.h
tests/IBTK/Makefile.am
tests/IBTK/Makefile.in
tests/IBTK/mpi_type_wrappers.cpp
tests/IBTK/mpi_type_wrappers.input
tests/IBTK/mpi_type_wrappers.output

Mpi type wrapper test

---

attest

I put the line breaks in weird places before.

fix line breaks in tester message.

---

ibtk/include/ibtk/SAMRAIDataCache.h
ibtk/lib/Makefile.am
ibtk/lib/Makefile.in
ibtk/src/utilities/SAMRAIDataCache.cpp

This is a draft implementation of a SAMRAI data caching class (see #533).

create class SAMRAIDataCache to cache allocated Eulerian data

---

ibtk/include/ibtk/LData.h

Fixes the new warning from #582.

Fix a clang warning about extra brackets.

---

examples/multiphase_flow/ex11/Makefile.am
examples/multiphase_flow/ex11/Makefile.in
examples/multiphase_flow/ex11/bargeGen.cpp
examples/multiphase_flow/ex12/LSLocateStructureInterface.cpp
examples/multiphase_flow/ex12/Makefile.am
examples/multiphase_flow/ex12/Makefile.in
examples/multiphase_flow/ex12/wedgeGen.cpp

Fix for #548: I saw the green light and hit the button even though my latest changes were not on the branch.

Multiphase examples 2a

---

doc/news/changes/incompatibilities/20190605AmneetBhalla
doc/news/changes/incompatibilities/20190610AmneetBhalla
doc/news/changes/minor/20190606AmneetBhalla
examples/multiphase_flow/ex1/LSLocateCircularInterface.cpp
examples/multiphase_flow/ex1/LSLocateCircularInterface.h
examples/multiphase_flow/ex1/example.cpp
examples/multiphase_flow/ex2/LSLocateCircularInterface.cpp
examples/multiphase_flow/ex2/LSLocateCircularInterface.h
examples/multiphase_flow/ex2/example.cpp
ibtk/include/ibtk/IndexUtilities.h
ibtk/include/ibtk/private/IndexUtilities-inl.h
include/ibamr/IBHydrodynamicSurfaceForceEvaluator.h
src/IB/IBHydrodynamicSurfaceForceEvaluator.cpp
tests/multiphase_flow/LSLocateCircularInterface.h
tests/multiphase_flow/Makefile.am
tests/multiphase_flow/Makefile.in
tests/multiphase_flow/SetLSProperties.h
tests/multiphase_flow/check_hydro_force.cpp
tests/multiphase_flow/check_hydro_force.mpirun=8.input
tests/multiphase_flow/check_hydro_force.mpirun=8.output
tests/multiphase_flow/free_falling_cyl_cib.cpp

These changes are all necessary for the Brinkman code in #418. Part of #546.

NWT: necessary changes for Brinkman code.

---

ibtk/config/IBTK_config.h.tmp.in
ibtk/configure

I must have forgotten to run autoreconf at some point.

Add some missing generated code.

---

doc/news/changes/major/20190624AmneetBhalla
include/ibamr/BrinkmanPenalizationRigidBodyDynamics.h
include/ibamr/BrinkmanPenalizationStrategy.h
lib/Makefile.am
lib/Makefile.in
src/IB/BrinkmanPenalizationRigidBodyDynamics.cpp
src/IB/BrinkmanPenalizationStrategy.cpp

Next part of #546.
I think the only thing missing is a few more sentences on what this class actually does. @amneetb could you write a paragraph or two and give a link to a citation, please?

NWT: Brinkman

---

tests/refine/rt0_refine_01.cpp

Lambda functions do not officially support default arguments yet.

Fix a pedantic test warning.

---

doc/news/changes/incompatibilities/20190919BoyceGriffith
include/ibamr/IBFEMethod.h
src/IB/IBFEMethod.cpp

Taken from #684.
@cpuelz The heart model currently uses this function but the only input files I see in the repository that actually use it are in the `old_input_files` directory.

remove overlapping mesh forces in IBFEMethod

---

ibtk/src/lagrangian/LDataManager.cpp

Moves #681 to the 0.5 branch for the 0.5.1 release.

zero IB forces in the right place

---

configure
ibtk/configure
m4/configure_hdf5.m4
m4/configure_hypre.m4
m4/configure_petsc.m4
m4/configure_silo.m4

Moves #687 and #689 to the 0.5 release.

IBAMR 0.5 687

---

doc/news/changes/0.5.0-vs-0.5.1.html

Summarize our recent changes. We also need this file on `master`.

Add a changelog list for 0.5.1.

---

configure
ibtk/configure

These are from an m4 macro I modified but did not commit.

Remove some debugging messages from configure.

---

attest
ibtk/include/ibtk/FEDataManager.h
ibtk/src/lagrangian/FEDataManager.cpp
tests/IBFE/explicit_ex4_2d.restart=50.input
tests/IBFE/explicit_ex4_2d.restart=50.mpirun=5.input
tests/IBFE/explicit_ex4_2d.restart=50.mpirun=5.output
tests/IBFE/explicit_ex4_2d.restart=50.output

It looks like I messed up FEDataManager's restart settings as part of #647. This PR fixes its restart code and also adds some tests that verify we can successfully restart and then compute correct values.

Add restart test

---

tests/IBFE/explicit_ex4.cpp

This should have been committed with the previous PR.

Actually fix the restart test.

---

ibtk/include/ibtk/FEDataManager.h
ibtk/src/lagrangian/FEDataManager.cpp

This makes it clearer that the data being cleared is managed by FEData.

Add FEData::clearCached().

---

doc/news/changes/minor/20190730AaronBarretDavidWells
scripts/make_visit_file.py

This should also now work with python 3.
@jabrown893 Two things:
1. Would you please try out this version of the script with both python 2 and python 3 to make sure it works with both?
2. I didn't read the script very carefully. Is the summary of it in the changelog entry correct?

Include a python script Aaron wrote.

---

tests/IB/explicit_ex1.output

That change added some new logfile output.

Update test output following #673.

---

tests/IBFE/explicit_ex4_2d.postprocessor.mpirun=4.input
tests/IBFE/explicit_ex4_2d.postprocessor.mpirun=4.output

This test will help verify backwards compatibility of the scratch hierarchy branch: i.e., this test won't work there at the moment since I broke the postprocessor in parallel.

Add a parallel postprocessor test.

---

tests/IBFE/explicit_ex4.cpp
tests/IBFE/explicit_ex4_2d.mpirun=5.output
tests/IBFE/explicit_ex4_2d.postprocessor.mpirun=4.output
tests/IBFE/explicit_ex4_2d.restart=50.mpirun=5.output
tests/IBFE/explicit_ex4_3d.mpirun=4.output
tests/spread/spread_01.cpp

Same as 8f7dc5ebf9, but for the two files I did not get at that point.

Use a robust partitioner in some libmesh tests.

---

tests/IBFE/Makefile.am
tests/IBFE/Makefile.in
tests/IBFE/explicit_ex8.cpp
tests/IBFE/explicit_ex8_2d.input
tests/IBFE/explicit_ex8_2d.mpirun=4.input
tests/IBFE/explicit_ex8_2d.mpirun=4.output
tests/IBFE/explicit_ex8_2d.output

These use multiple FEDataManagers and work in a different way than ex4.
I want to add these before proceeding with #654 to verify that things still work correctly with multiple parts.

Add some tests based on IBFE/explicit/ex8.

---

examples/IBFE/explicit/ex0/test_main.cpp
tests/IBFE/Makefile.am
tests/IBFE/Makefile.in
tests/IBFE/explicit_ex0.cpp
tests/IBFE/explicit_ex0_2d.input
tests/IBFE/explicit_ex0_2d.output

I noticed on Friday that the gtest test no longer worked. Fortunately, this is because the fix in #552 improves the accuracy and lowers the error slightly in the velocity and pressure.
Part of #569.

Convert ibfe ex0 test

---

include/ibamr/IBFEMethod.h

Improve the scratch hierarchy documentation.

---

include/ibamr/IBFEMethod.h
include/ibamr/IBStrategy.h

@xxjaehoxx sent me an email this morning asking about this and the answer wasn't clear without reading a lot of source code.

Document some input parameters.

---

doc/release-tasks.md

Add two more notes to release tasks.

---

README.md
doc/git.md

Add notes on git.

---

doc/git.md

Thanks @amneetb for checking this :)
* fix some spelling errors
* improve flow in some paragraphs
* fix an issue with markdown where multiple lines were combined

Minor fixes for git.md

---

ibtk/src/lagrangian/FEDataManager.cpp

Increment FEDataManager::FE_DATA_MANAGER_VERSION.

---

include/ibamr/IBFEMethod.h
src/IB/IBFEMethod.cpp
tests/IBFE/explicit_ex4_2d.input
tests/IBFE/explicit_ex4_2d.mpirun=5.output
tests/IBFE/explicit_ex4_2d.output
tests/IBFE/explicit_ex4_2d.postprocessor.input
tests/IBFE/explicit_ex4_2d.postprocessor.mpirun=4.output
tests/IBFE/explicit_ex4_2d.postprocessor.output
tests/IBFE/explicit_ex4_2d.postprocessor.scratch_hier.mpirun=4.input
tests/IBFE/explicit_ex4_2d.postprocessor.scratch_hier.mpirun=4.output
tests/IBFE/explicit_ex4_2d.restart=50.input
tests/IBFE/explicit_ex4_3d.mpirun=4.input
tests/IBFE/explicit_ex4_3d.mpirun=4.output
tests/IBFE/explicit_ex4_3d.scratch_hier.mpirun=4.input
tests/IBFE/explicit_ex4_3d.scratch_hier.mpirun=4.output
tests/IBFE/explicit_ex8_2d.scratch_hier.mpirun=4.output

This is enough of a fix for #773 for now. It would be nice to solve the root problem and get SAMRAI to deterministically initially partition patches but I doubt that this is possible from inside IBAMR - hopefully it has been fixed in a more recent release.
Fixes #773.

Fix test partitioning

---

tests/IBTK/bounding_boxes_01.cpp

It looks like I never updated the test when I did #761.

Fix the bounding box test with libMesh 1.1.0.

---

ibtk/include/ibtk/AppInitializer.h
include/ibamr/IBFEMethod.h

added some documentation for IBFE restart

added some documentation to restart functions

---

doc/git.md

added the force push step for editing git history

edited git.md docs for cleaning up history

---

src/IB/IBFEDirectForcingKinematics.cpp
src/IB/IBFEMethod.cpp
src/IB/IBFESurfaceMethod.cpp

Define end iterators outside of loops.

---

doc/news/changes/major/20191218AmneetBhalla

Adding the major changelog

---

doc/news/changes/minor/20191219MarshallDavey
examples/IBFE/explicit/ex0/example.cpp
examples/IBFE/explicit/ex1/example.cpp
examples/IBFE/explicit/ex10/example.cpp
examples/IBFE/explicit/ex11/example.cpp
examples/IBFE/explicit/ex2/example.cpp
examples/IBFE/explicit/ex3/example.cpp
examples/IBFE/explicit/ex4/example.cpp
examples/IBFE/explicit/ex5/example.cpp
examples/IBFE/explicit/ex6/example.cpp
examples/IBFE/explicit/ex7/example.cpp
examples/IBFE/explicit/ex8/example.cpp
examples/IBFE/explicit/ex9/example.cpp

edited examples to include IBFE restart stuff

added restart capabilities to IBFE examples

---

doc/news/changes/minor/20191219DavidWells
src/IB/IBFESurfaceMethod.cpp
tests/IBFE/explicit_ex5.cpp
tests/IBFE/explicit_ex5_2d.restart=40.mpirun=2.input
tests/IBFE/explicit_ex5_2d.restart=40.mpirun=2.output

Fixes #806. Part of #749.
Same as 5ff31c0060 but for IBFESurfaceMethod.

Fix IBFESurfaceMethod's restart load.

---

examples/ConstraintIB/moving_plate/RigidBodyKinematics.h
examples/complex_fluids/ex2/InterpolationUtilities.cpp
ibtk/include/ibtk/LInitStrategy.h
ibtk/include/ibtk/libmesh_utilities.h
ibtk/src/lagrangian/JacobianCalculator.cpp
ibtk/src/solvers/impls/CCPoissonPointRelaxationFACOperator.cpp
ibtk/src/solvers/impls/PETScMFFDJacobianOperator.cpp
include/ibamr/BrinkmanPenalizationRigidBodyDynamics.h
include/ibamr/CFINSForcing.h
include/ibamr/CFRelaxationOperator.h

I found at least one real problem here and silenced a bunch of warnings generated by clang.
Part of #749.

Fix clang warnings

---

src/level_set/FESurfaceDistanceEvaluator.cpp

Fix an unused variable warning.

---

doc/news/changes/0.5.1-vs-0.6.0.html

Remove some empty brackets from the changelog.

---

attest

Two small improvements to attest:
1. avoid recomputing a string
2. avoid sleeping and polling in favor of an event

Improve attest

---

ibtk/src/lagrangian/FEDataManager.cpp

slight performance improvement.

---

ibtk/src/lagrangian/LSiloDataWriter.cpp

Remove strdup

---

ibtk/include/ibtk/FEDataInterpolation.h
ibtk/src/solvers/impls/CCPoissonPointRelaxationFACOperator.cpp
ibtk/src/solvers/impls/PETScLevelSolver.cpp
src/IB/GeneralizedIBMethod.cpp
src/IB/IBExplicitHierarchyIntegrator.cpp
src/IB/IBFEMethod.cpp
src/IB/IBImplicitStaggeredHierarchyIntegrator.cpp
src/IB/IBInstrumentPanel.cpp
src/IB/IBInterpolantHierarchyIntegrator.cpp
src/IB/IBMethod.cpp
src/IB/IBStandardForceGen.cpp
src/IB/IMPMethod.cpp
src/level_set/RelaxationLSMethod.cpp
src/navier_stokes/INSStaggeredPressureBcCoef.cpp
src/navier_stokes/INSVCStaggeredPressureBcCoef.cpp

A few more small things caught by cppcheck.

Cppcheck 4

---

.gitignore

Not too important, but I have dozens of files in my root directory that match these patterns that should not be tracked by git.

Add some more files to .gitignore.

---

tests/wave_tank/nwt_cylinder.cpp

Hi @drwells,
I fixed the bug. Could you please rerun the test with this updated code?

Fixed a bug in numerical wave tank test

---

doc/news/changes/incompatibilities/20200131MarshallDavey
ibtk/include/ibtk/HierarchyIntegrator.h
ibtk/src/utilities/HierarchyIntegrator.cpp
include/ibamr/IBHierarchyIntegrator.h
include/ibamr/IBStrategy.h
src/IB/IBHierarchyIntegrator.cpp
src/IB/IBStrategy.cpp

unique_ptr for HierarchyIntegrator

---

src/IB/ConstraintIBMethod.cpp
src/IB/IBInstrumentPanel.cpp
src/IB/IBInterpolantHierarchyIntegrator.cpp
src/IB/NonbondedForceEvaluator.cpp
src/complex_fluids/CFRelaxationOperator.cpp
src/navier_stokes/INSVCStaggeredNonConservativeHierarchyIntegrator.cpp
src/navier_stokes/StaggeredStokesBlockFactorizationPreconditioner.cpp

Fix a variety of minor warnings generated by my copy of clang.

Fix clang warnings 2

---

attest
doc/news/changes/minor/20200207DavidWells
tests/IBFE/Makefile.am
tests/IBFE/Makefile.in
tests/IBTK/Makefile.am
tests/IBTK/Makefile.in
tests/Makefile.am
tests/Makefile.in
tests/level_set/Makefile.am
tests/level_set/Makefile.in
tests/spread/Makefile.am
tests/spread/Makefile.in
tests/wave_tank/Makefile.am
tests/wave_tank/Makefile.in

Get the test suite working without libMesh.

---

include/ibamr/IBRedundantInitializer.h

Remove an unused header inclusion.

---

Makefile.in
configure
ibtk/Makefile.in
ibtk/configure
ibtk/contrib/boost/boost/math/special_functions/sign.hpp
ibtk/contrib/boost/boost/math/tools/roots.hpp
ibtk/contrib/boost/boost/math/tools/toms748_solve.hpp
ibtk/contrib/boost/boost/math/tools/tuple.hpp
ibtk/m4/configure_boost.m4
m4/configure_boost.m4

Fixes #845. I've added necessary functions to use `boost/math/tools/roots.hpp` as well as added configure checks for all headers we currently use from boost.

Updated bundled boost and added configuring checks.

---

tests/IB/explicit_ex0.cpp
tests/IB/explicit_ex0.restart=300.mpirun=4.input
tests/IB/explicit_ex0.restart=300.mpirun=4.output

Add a test for restarting an IB example.

---

tests/IBTK/Makefile.am
tests/IBTK/Makefile.in
tests/IBTK/ghost_indices_01.cpp
tests/IBTK/ghost_indices_01_2d.a.mpirun=2.input
tests/IBTK/ghost_indices_01_2d.a.mpirun=2.output
tests/IBTK/ghost_indices_01_2d.b.mpirun=2.input
tests/IBTK/ghost_indices_01_2d.b.mpirun=2.output
tests/IBTK/ghost_indices_01_3d.a.mpirun=4.input
tests/IBTK/ghost_indices_01_3d.a.mpirun=4.output
tests/IBTK/ghost_indices_01_3d.b.mpirun=4.input
tests/IBTK/ghost_indices_01_3d.b.mpirun=4.output
tests/spread/spread_01.cpp
tests/tests.h

I'm working on #830 and I wrote some tests on the way as I learned how the code works.

Index tests

---

include/ibamr/IBFEMethod.h
src/IB/IBFEMethod.cpp
tests/IBFE/explicit_ex4_2d.mpirun=4.input
tests/IBFE/explicit_ex4_2d.mpirun=4.output

Most of #737 - I will address the parts pertinent to FEDataManager in another PR.
First part of #830 - now that we have the forces spread onto their own index we can go ahead and redo the way we accumulate data in parallel without worrying about other forces.
I encountered a few bugs along the way while writing this patch - to aid in future debugging I added a new test and modified an existing test so that we have an IBFE-based simulation that executes multiple regrids and gives the same answers with and without the scratch hierarchy.

Redo force spreading 1

---

doc/news/changes/minor/20200220DavidWells
include/ibamr/IBFEMethod.h
include/ibamr/IBMethod.h
include/ibamr/IBStrategy.h
src/IB/IBFEMethod.cpp
src/IB/IBMethod.cpp
src/IB/IBStrategy.cpp
tests/IBFE/explicit_ex4.cpp
tests/IBFE/explicit_ex4_2d.inactive_1.mpirun=4.input
tests/IBFE/explicit_ex4_2d.inactive_1.mpirun=4.output
tests/IBFE/explicit_ex4_3d.inactive_1.mpirun=4.input
tests/IBFE/explicit_ex4_3d.inactive_1.mpirun=4.output

Alternative to #878 - I conferred with @jabrown893 to see how this is done in practice and we came up with some new ideas. In particular, we now have a common API for disabling structures that works in IBFEMethod and IBMethod.
I also added a test based on my favorite (IBFE ex4) that disables a massive structure in the middle of the domain to check that we really can turn things off correctly.

Inactivate parts api

---

tests/interpolate/interpolate_01.cpp

The comment I deleted was from an older version of the test - I fixed the issue so the comment doesn't matter anymore.

Improve some comments in a test.

---

doc/news/changes/incompatibilities/20200303BoyceGriffith
src/IB/IBFEMethod.cpp
tests/IBFE/explicit_ex4.cpp
tests/IBFE/explicit_ex4_2d.inactive_1.mpirun=4.restart=50.input
tests/IBFE/explicit_ex4_2d.inactive_1.mpirun=4.restart=50.output

Quick follow-up to #897 - this test verifies that we do inactivate the structure correctly after restarting.

Add a test for inactivation + restart

---

src/IB/IBFEMethod.cpp

From the heart model meeting - this makes a marginal performance difference (maybe 0.25% improvement?) but it should make things more consistent in parallel. It also shows how we can modify other systems if necessary to use the same tricks.

Force ghosted assembly

---

Makefile.in
ibtk/Makefile.in
ibtk/lib/Makefile.am
ibtk/lib/Makefile.in

This was introduced in 86706a6db14 as a copy-paste error - these files aren't generated like the fortran files are.

Fix a warning issued by make.

---

doc/news/changes/minor/20200303AaronBarrett
ibtk/configure
ibtk/configure.ac
ibtk/examples/GhostCells/Makefile.am
ibtk/examples/GhostCells/Makefile.in
ibtk/examples/GhostCells/README
ibtk/examples/GhostCells/TotalAmountRefineAndCoarsen.cpp
ibtk/examples/GhostCells/TotalAmountRefineAndCoarsen.h
ibtk/examples/GhostCells/example.cpp
ibtk/examples/GhostCells/input2d
ibtk/examples/GhostCells/input3d
ibtk/examples/Makefile.am

Fixes #892. I've added an IBTK example that shows two different ways to fill in ghost cells by 
1) converting from cell average quantities to total cell amounts.
2) Interpolating cell amounts to cell nodes.

Added example on filling in ghost cell values.

---

.github/pull_request_template.md
doc/pull_request_template.md

Fixes #900. After this is merged the following text should appear, by default, in every new PR:
Are we all okay with this list?

Add a template for pull requests.

---

ibtk/src/lagrangian/FEDataManager.cpp

add missing include in FEDataManager.cpp

---

attest

This is a better explanation of what is going on. @jabrown893 asked so I figured it was wise to write the summary down here.

Update attest's output.

---

ibtk/src/refine_ops/CartSideDoubleDivPreservingRefine.cpp
tests/multiphase_flow/SetFluidGasSolidDensity.h
tests/multiphase_flow/SetFluidGasSolidViscosity.h
tests/multiphase_flow/SetFluidProperties.h

Fix some clang warnings.

---

ibtk/src/solvers/impls/CCPoissonBoxRelaxationFACOperator.cpp
src/IB/IBMethod.cpp
src/IB/IBStandardForceGen.cpp

replace deprecated bind2nd with lambda expressions

---

doc/news/changes/incompatibilities/20200324DavidWells
ibtk/include/ibtk/LibMeshSystemVectors.h
ibtk/lib/Makefile.am
ibtk/lib/Makefile.in
ibtk/src/utilities/LibMeshSystemVectors.cpp
include/ibamr/IBFEMethod.h
src/IB/IBFEMethod.cpp
tests/spread/spread_01.cpp

Part of #932, but applied to IBFEMethod first. @boyceg what do you think?

Add LibMeshSystemVectors

---

ibtk/src/utilities/libmesh_utilities.cpp

Fix compilation with libMesh 1.1.0

---

doc/news/changes/minor/20200319AaronBarrett
ibtk/include/ibtk/HierarchyIntegrator.h
ibtk/src/utilities/HierarchyIntegrator.cpp

Can register a callback function with HierarchyIntegrator to allow specialization for HierarchyIntegrator::regridHierarchy()

---

bootstrap

Just to help @boyceg :)
1. Look for previously compiled tools
2. Don't fail silently, even though we don't handle failure well
3. Improve output a little bit

Improve bootstrap a little more.

---

ibtk/include/ibtk/FEDataManager.h
ibtk/src/lagrangian/FEDataManager.cpp

lazy initialize IB ghosted DOF indexing

---

include/ibamr/IBFESurfaceMethod.h
src/IB/IBFESurfaceMethod.cpp

First part of #932 - these are the minor changes that don't really effect anything but add some fields we will need later.
1. switch to d_use_jump_conditions
2. add system names
#932 currently has a merge conflict - this also fixes that. Once this is merged I will open a successor to #932.

Required changes for IIM, part 0

---

doc/news/changes/major/20200405BoyceGriffith
ibtk/include/ibtk/ibtk_utilities.h
include/ibamr/IBFEMethod.h
include/ibamr/IBHierarchyIntegrator.h
src/IB/IBFEMethod.cpp
src/IB/IBHierarchyIntegrator.cpp
tests/IBFE/explicit_ex4_2d.FORWARD_EULER.input
tests/IBFE/explicit_ex4_2d.FORWARD_EULER.mpirun=4.input
tests/IBFE/explicit_ex4_2d.FORWARD_EULER.mpirun=4.output
tests/IBFE/explicit_ex4_2d.FORWARD_EULER.output
tests/IBFE/explicit_ex4_2d.TRAPEZOIDAL_RULE.input
tests/IBFE/explicit_ex4_2d.TRAPEZOIDAL_RULE.mpirun=4.input
tests/IBFE/explicit_ex4_2d.TRAPEZOIDAL_RULE.mpirun=4.output
tests/IBFE/explicit_ex4_2d.TRAPEZOIDAL_RULE.output

add support for different time stepping schemes in IBFEMethod

---

doc/news/changes/major/20200408DavidWells
examples/IBFE/explicit/ex0/example.cpp
examples/IBFE/explicit/ex1/example.cpp
examples/IBFE/explicit/ex11/example.cpp
examples/IBFE/explicit/ex4/example.cpp
examples/IBFE/explicit/ex5/example.cpp
examples/IBFE/explicit/ex6/example.cpp
examples/IBFE/explicit/ex9/example.cpp
src/IB/IBFECentroidPostProcessor.cpp
src/IB/IBFEDirectForcingKinematics.cpp
src/IB/IBFEPostProcessor.cpp
tests/IBFE/explicit_ex0.cpp
tests/IBFE/explicit_ex1.cpp
tests/IBFE/explicit_ex4.cpp
tests/IBFE/explicit_ex4_2d.postprocessor.scratch_hier.mpirun=4.output
tests/IBFE/explicit_ex5.cpp

We still use it in IBFESurfaceMethod which is in the process of being rewritten anyway.
@jabrown893 Please make similar fixes to the TAVR code, should that use `localize` in a similar way anywhere.
Related to #657.

Remove most calls to localize.

---

doc/news/changes/minor/20200414BoyceGriffith
ibtk/include/ibtk/FEDataManager.h
ibtk/include/ibtk/FEProjector.h
ibtk/lib/Makefile.am
ibtk/lib/Makefile.in
ibtk/src/lagrangian/FEDataManager.cpp
ibtk/src/lagrangian/FEProjector.cpp

factor out L2 projection code into new class FEProjector

---

doc/news/changes/minor/20200416BoyceGriffith
ibtk/include/ibtk/FEDataInterpolation.h
ibtk/src/lagrangian/FEDataInterpolation.cpp
src/IB/IBFECentroidPostProcessor.cpp
src/IB/IBFEMethod.cpp
src/IB/IBFESurfaceMethod.cpp

avoid using FEDataManager in FEDataInterpolation

---

src/IB/IBFESurfaceMethod.cpp
tests/IBFE/explicit_ex5_2d.regrid.mpirun=2.input
tests/IBFE/explicit_ex5_2d.regrid.mpirun=2.output

We need to clear SAMRAIGhostDataAccumulator here since it contains grid-dependent information. Thanks to @benlvr for pointing this out on slack.

Fix IBFESurfaceMethod regrid.

---

ibtk/include/ibtk/LibMeshSystemVectors.h
ibtk/src/lagrangian/FEDataManager.cpp
src/IB/IBFEMethod.cpp

1. We need a virtual destructor when we manage objects by pointer
2. Remove an unused function
3. Remove some unnecessary moves - the compiler can use copy elision here.

Fix some warnings with clang 10.

---

doc/news/changes/major/20200504BoyceGriffith
ibtk/include/ibtk/FEDataManager.h
ibtk/src/lagrangian/FEDataInterpolation.cpp
ibtk/src/lagrangian/FEDataManager.cpp
include/ibamr/FEMechanicsBase.h
include/ibamr/IBFEMethod.h
lib/Makefile.am
lib/Makefile.in
src/IB/FEMechanicsBase.cpp
src/IB/IBFEMethod.cpp
tests/IBFE/explicit_ex1_2d.eliminate_pressure_jumps.input
tests/IBFE/explicit_ex1_2d.eliminate_pressure_jumps.output
tests/IBFE/explicit_ex1_2d.impose_pressure_jumps.input
tests/IBFE/explicit_ex1_2d.impose_pressure_jumps.output
tests/IBFE/explicit_ex4.cpp
tests/IBFE/explicit_ex4_2d.source_test.input
tests/IBFE/explicit_ex4_2d.source_test.output
tests/IBFE/zero_exterior_values.cpp

Factor mechanics code from IBFEMethod into FEMechanicsBase

---

tests/IBFE/explicit_ex2.cpp
tests/IBFE/explicit_ex2_3d.nodal_quadrature.output

These warnings contain file paths, which are configuration dependent.

Suppress some warning messages in a test.

---

src/IB/IBFEMethod.cpp

avoid unneeded copies in IBFEMethod for multi-part models

---

ibtk/include/ibtk/FECache.h
ibtk/include/ibtk/FEValues.h
ibtk/include/ibtk/JacobianCalculator.h
ibtk/lib/Makefile.am
ibtk/lib/Makefile.in
ibtk/src/lagrangian/FEValues.cpp
ibtk/src/lagrangian/JacobianCalculator.cpp
tests/IBTK/Makefile.am
tests/IBTK/Makefile.in
tests/IBTK/fe_values_01.cpp

A major chunk of #482 - this isn't used in the library yet but I did add a test.

Add FEValues

---

ibtk/src/lagrangian/JacobianCalculator.cpp

I'm running the test suite now - it looks like I forgot a few of these when I wrote #990.

Fix some more sign comparison warnings

---

ibtk/include/ibtk/FEValues.h

add a defaulted virtual destructor to FEValuesBase

---

doc/news/changes/major/20200519DavidWells
ibtk/include/ibtk/FEDataInterpolation.h
ibtk/src/lagrangian/FEDataInterpolation.cpp

This reverts commit 5dba10c26cfe55027d47cbebee88d63d5d0ff0f1.
This feature passes the test suite but causes problems in user codes
that we don't currently have time to address.

Revert "Use FEValues in FEDataInterpolation."

---

include/ibamr/IBFEMethod.h

Update IBFEMethod documentation.

---

doc/news/changes/minor/20200612AmneetBhalla
examples/IBLevelSet/ex0/example.cpp

Fixing restart for IBLevelSet/ex0

---

doc/input-and-restart-databases.md
doc/news/changes/major/20200612DavidWells

Add some information on restart and input databases.

---

ibtk/lib/Makefile.am
ibtk/lib/Makefile.in

Fixes #969. I ran the testsuite on my mac :)

Fix an automake path.

---

ibtk/src/lagrangian/StableCentroidPartitioner.cpp

For reasons I don't fully understand this is only problematic with the (not yet merged) CMake build on my mac: I can't reproduce this problem with any tested configuration.

Add a missing header.

---

src/IB/IBMethod.cpp
src/navier_stokes/INSVCStaggeredConservativeMassMomentumIntegrator.cpp

Fix some warnings.

---

ibtk/src/lagrangian/FEDataManager.cpp

I keep forgetting that we still support this version.

Fix compilation with libMesh 1.1.0.

---

ibtk/include/ibtk/libmesh_utilities.h

I didn't bother with the test suite for this - its a missing header.

Add another missing header.

---

src/wave_generation/IrregularWaveBcCoef.cpp
src/wave_generation/StokesFifthOrderWaveBcCoef.cpp

Fix some uninitialized variable warnings.

---

tests/IBFE/explicit_ex4_2d.amr.restart=50.mpirun=4.output

It looks like I rebased #1036 incorrectly - a line I added just to debug ended up in an output file.

Remove an extra line from a test

---

include/ibamr/AdvDiffHierarchyIntegrator.h
tests/IBTK/Makefile.am
tests/IBTK/Makefile.in
tests/IBTK/hierarchy_callbacks.cpp
tests/IBTK/hierarchy_callbacks.input
tests/IBTK/hierarchy_callbacks.output

Fixes #943. Adds hierarchy callback tests. This also fixes a small comment that prevented a callback description from showing up in the doxygen generated documentation.

Adding hierarchy callback tests

---

ibtk/include/ibtk/muParserRobinBcCoefs.h
include/ibamr/AdvDiffHierarchyIntegrator.h
include/ibamr/INSHierarchyIntegrator.h

Added additional documentation for physical boundary conditions.

---

tests/vc_navier_stokes/Makefile.am
tests/vc_navier_stokes/Makefile.in
tests/vc_navier_stokes/vc_navier_stokes_01.cpp
tests/wave_tank/Makefile.am
tests/wave_tank/Makefile.in
tests/wave_tank/SetFluidGasSolidDensity.cpp
tests/wave_tank/SetFluidGasSolidViscosity.cpp
tests/wave_tank/nwt_cylinder.cpp

This makes setting things up with CMake a lot simpler.
This makes writing the test compilation in the CMake build system much easier. Part of #1020.

Associate exactly one source file per test.

---

include/ibamr/CIBMethod.h

The interface defined in a strategy class should also be available in classes
that inherit from it so it makes sense for us to include these functions.

Fix some warnings with hidden virtual functions.

---

doc/news/changes/major/20200519DavidWells
ibtk/include/ibtk/FEDataInterpolation.h
ibtk/include/ibtk/FEValues.h
ibtk/src/lagrangian/FEDataInterpolation.cpp
ibtk/src/lagrangian/FEValues.cpp
tests/IBTK/fe_values_01.cpp
tests/IBTK/fe_values_02.cpp

Closes #482 :tada:
Followup to #997: the problem was that we need to support more than isoparametric finite elements in this class (which isn't too hard to do - we just need to restrict ourselves to elements with a straightforward reference element implementation.

Fe values fe interpolation

---

doc/news/changes/incompatibilities/20200803DavidWells
ibtk/include/ibtk/FEMapping.h
ibtk/include/ibtk/FEMappingCache.h
ibtk/include/ibtk/FEValues.h
ibtk/lib/Makefile.am
ibtk/lib/Makefile.in
ibtk/src/lagrangian/FEDataManager.cpp
ibtk/src/lagrangian/FEMapping.cpp
ibtk/src/lagrangian/FEValues.cpp
tests/IBTK/jacobian_calc_01.cpp
tests/IBTK/mapping_01.cpp

Also rename related classes.
Fixes #1061.

Rename Mapping to FEMapping.

---

include/ibamr/IBFEMethod.h

I reread all of our restart code this morning and figured out how to make this consistently work. @cpuelz @marshallrdavey FYI :)

Add some explanatory documentation on setting up external Systems.

---

ibtk/src/lagrangian/FEDataManager.cpp

I used the wrong function in #1062: fortunately its only a problem with the development version of libMesh.

Fix compilation with libMesh's development branch.

---

doc/news/changes/minor/20200806DavidWells
src/IB/IBFEMethod.cpp

Trying to debug some other problems recently showed me how useful TimerManager
can be, so lets add timers to IBFEMethod.

Add some more timers for IBFEMethod.

---

ibtk/include/ibtk/CCPoissonHypreLevelSolver.h
ibtk/include/ibtk/FEDataInterpolation.h
ibtk/include/ibtk/FEDataManager.h
ibtk/include/ibtk/FEMapping.h
ibtk/include/ibtk/LNodeIndex.h
ibtk/include/ibtk/SCPoissonHypreLevelSolver.h
ibtk/include/ibtk/libmesh_utilities.h
ibtk/include/ibtk/private/IndexUtilities-inl.h
ibtk/include/ibtk/private/LData-inl.h
include/ibamr/BrinkmanPenalizationRigidBodyDynamics.h
include/ibamr/CFINSForcing.h
include/ibamr/CIBStrategy.h
include/ibamr/ConstraintIBMethod.h
include/ibamr/IBFEDirectForcingKinematics.h
include/ibamr/IBFEInstrumentPanel.h
include/ibamr/IBFEPostProcessor.h
include/ibamr/IBHydrodynamicForceEvaluator.h
include/ibamr/IBHydrodynamicSurfaceForceEvaluator.h
include/ibamr/IBInterpolantMethod.h
include/ibamr/IBRedundantInitializer.h
src/IB/IBFEPatchRecoveryPostProcessor.cpp
src/complex_fluids/CFRelaxationOperator.cpp

This is necessary for CMake since the new configuration headers are different.

Clean up some file inclusions.

---

include/ibamr/IBFEMethod.h

It's a documentation change so I didn't run the test suite et al.

IBFEMethod documentation fix

---

doc/news/changes/minor/20200901AaronBarrett
include/ibamr/CFINSForcing.h

Fixed CFINSForcing::getVariableIdx() to get the correct patch index.

---

ibtk/include/ibtk/FEDataManager.h
ibtk/src/lagrangian/FEDataManager.cpp
include/ibamr/IBFESurfaceMethod.h
src/IB/IBFESurfaceMethod.cpp

Tidying this class up will make the multilevel stuff easier. I removed all the 'easy' deprecated features - I'll handle the more complicated stuff in the next PR.

Remove some deprecated stuff in FEDataManager.

---

ibtk/include/ibtk/libmesh_utilities.h
ibtk/src/utilities/libmesh_utilities.cpp
include/ibamr/FEMechanicsBase.h
src/IB/FEMechanicsBase.cpp
src/IB/IBFEMethod.cpp

We can use this in IBFESurfaceMethod too. Even though its internal I marked it as deprecated since we have a bunch of other FEMechanicsBase patches in progress.

Move setup_system_vector(s) to libmesh_utilities.

---

src/IB/IBFEMethod.cpp

I had to reread this code to understand the parallel constraints bug again.

Slightly improve IBFEMethod's parallel communication.

---

include/ibamr/IBFESurfaceMethod.h
src/IB/IBFESurfaceMethod.cpp

Merge surface jumps 4

---

include/ibamr/IBFESurfaceMethod.h
src/IB/IBFESurfaceMethod.cpp

Use LibMeshSystemIBVectors in IBFESurfaceMethod, part 5.

---

doc/news/changes/incompatibilities/20200910DavidWells
doc/news/changes/incompatibilities/20200910DavidWells-2
ibtk/include/ibtk/FEDataManager.h
ibtk/src/lagrangian/FEDataManager.cpp
ibtk/src/lagrangian/FEProjector.cpp
include/ibamr/IBFEMethod.h
include/ibamr/IBFESurfaceMethod.h
src/IB/IBFEMethod.cpp
src/IB/IBFESurfaceMethod.cpp
tests/IBFE/explicit_ex4.cpp

We need to fundamentally change the way we set up the patch-to-element mapping to support multilevel interaction in IBFE. It's not backwards-compatible, but we can make our lives a lot easier by just getting rid of all the extra `FEDataManager::getManager()` overloads so that we can set up the block id to patch level mapping just once.

Multilevel ibfe 1

---

doc/news/changes/major/20200911BoyceGriffith
include/ibamr/FEMechanicsBase.h
include/ibamr/IBFEMethod.h
include/ibamr/ibamr_enums.h
src/IB/FEMechanicsBase.cpp
src/IB/IBFEMethod.cpp

add a static pressure (with optional local projection stabilization) to FEMechanicsBase

---

ibtk/include/ibtk/FEDataManager.h
ibtk/src/lagrangian/FEDataManager.cpp

This PR updates our data structures in FEDataManager so that we can also index by patch level.

Multilevel ibfe 2

---

src/IB/FEMechanicsBase.cpp

fix indexing bug in FEMechanicsBase

---

ibtk/src/utilities/libmesh_utilities.cpp

IBFESurfaceMethod does not use ExplicitSystems so libMesh refuses to do the cast in debug mode. I think this worked by coincidence before but we should definitely guard this case.
Unfortunately libMesh is so slow in debug mode that I rarely run the test suite in that configuration. I am doing it now to see what else shows up.

Fix a libMesh::System cast.

---

tests/spread/spread_01.cpp
tests/spread/spread_01_2d.bspline_3.mpirun=4.output
tests/spread/spread_01_2d.ib_6.mpirun=4.output
tests/spread/spread_01_2d.nodal_quadrature.a.mpirun=4.output
tests/spread/spread_01_2d.square.c.bspline_4.mpirun=4.output
tests/spread/spread_01_3d.compositecube.bspline_4.mpirun=4.output
tests/spread/spread_01_3d.cube.b.bspline_4.mpirun=4.output
tests/spread/spread_01_3d.cube.bspline_3.mpirun=4.output
tests/spread/spread_01_3d.ib_6.mpirun=4.output
tests/spread/spread_01_3d.piecewise_linear.mpirun=4.output
tests/tests.h

Fix a problem with printing the partitioning in tests.

---

ibtk/include/ibtk/FEDataManager.h
ibtk/src/lagrangian/FEDataManager.cpp
tests/IBFE/interpolate_velocity_01.cpp
tests/IBFE/interpolate_velocity_01_2d.multilevel.a.input
tests/IBFE/interpolate_velocity_01_2d.multilevel.a.output
tests/IBFE/interpolate_velocity_01_2d.multilevel.b.input
tests/IBFE/interpolate_velocity_01_2d.multilevel.b.mpirun=4.input
tests/IBFE/interpolate_velocity_01_2d.multilevel.b.mpirun=4.output
tests/IBFE/interpolate_velocity_01_2d.multilevel.b.output
tests/IBFE/interpolate_velocity_01_2d.multilevel.c.input
tests/IBFE/interpolate_velocity_01_2d.multilevel.c.output

This is enough to get velocity interpolation working correctly - we get about the same (they are a factor of 2 better) errors as we do when the finest grid level is one level lower and all the elements are on that level.
`FEDataManager::collectActivePatchElements()` is getting a bit messy but I think it would be best for now to leave refactoring that for later - this is already pretty complicated.
GitHub for the pull …

Multilevel ibfe 5

---

ibtk/include/ibtk/FEDataManager.h
ibtk/src/lagrangian/FEDataManager.cpp
tests/IBTK/subdomain_level_translation_01.cpp

Improve the documentation of SubdomainToLevelTranslation.

---

examples/complex_fluids/ex2/InterpolationUtilities.h
ibtk/include/ibtk/FEDataManager.h
ibtk/include/ibtk/SAMRAIDataCache.h
ibtk/src/lagrangian/FEDataManager.cpp
ibtk/src/utilities/SAMRAIDataCache.cpp
include/ibamr/IBFEMethod.h
include/ibamr/IBFESurfaceMethod.h
src/IB/IBFEMethod.cpp
src/IB/IBFESurfaceMethod.cpp
tests/IBFE/explicit_ex4.cpp

Posted here so that @boyceg can take a look. I think that this is most of what we need though there are still a few TODOs.
I am getting tired of having to wait for all the tests to relink so this PR includes the CMake build system - I'll take it out once everything works (that's not yet ready to be merged but in practice works)

Multilevel ibfe 7

---

ibtk/src/lagrangian/FEDataManager.cpp
include/ibamr/IBFEMethod.h

I added a check to explicitly guard against the bug we just encountered in the heart model. I also fixed some issues with the documentation.

Update some checks and documentation related to the FCH bug.

---

src/IB/IBFEMethod.cpp

synch coarse grid values with overlying fine grid data in IBFEMethod::interpolateVelocity()

---

ibtk/include/ibtk/FEDataManager.h
ibtk/src/lagrangian/FEDataManager.cpp
tests/IBFE/explicit_ex4_2d.multilevel.c.input
tests/IBFE/explicit_ex4_2d.multilevel.c.output
tests/IBFE/explicit_ex4_2d.multilevel.d.input
tests/IBFE/explicit_ex4_2d.multilevel.d.output
tests/IBTK/subdomain_level_translation_01.cpp

Fix multilevel IBFE when the structure is not on the finest level.

---

src/IB/IBFEMethod.cpp

Since we are decrementing ln we should be extra-careful and definitely not use
unsigned integers.

Fix a sign warning.

---

include/ibamr/IBFEMethod.h
src/IB/IBFEMethod.cpp

I noticed this when discussing the regridding algorithm earlier today.

Fix a typo.

---

src/IB/IBFEMethod.cpp

This is fine since we will never have a very large (i.e., large enough for the
difference between signed and unsigned to matter) number of levels.

Fix a sign comparison warning.

---

ibtk/src/lagrangian/FEMapping.cpp

These classes have template functions that are defined in the source folder - in order to use them we need to explicitly instantiate the classes. For some reason this is only a problem when we have dynamic linking (via CMake) and not static linking (via autotools).
Part of #1020.

Add some missing instantiations.

---

doc/news/changes/minor/20201016DavidWells

I checked off the box for #1145 for a changelog without actually adding one - oops.

Add a changelog entry for the memory fix.

---

include/ibamr/config.h

Fix some repeated macro definition warnings.

---

tests/IBFE/explicit_ex8.cpp
tests/IBTK/multilevel_fe_01.cpp
tests/multiphase_flow/LSLocateBargeInterface.h
tests/spread/spread_01.cpp
tests/spread/spread_02.cpp

Fix some clang warnings in tests.

---

src/IB/IBHierarchyIntegrator.cpp
tests/IBFE/explicit_ex4_2d.displace.mpirun=4.input

correct IBHierarchyIntegrator flag for specifying structure based regrid

---

.gitignore

add .cache (from clangd) to .gitignore

---

doc/news/changes/minor/20201207AaronBarrett
ibtk/include/ibtk/LDataManager.h

This adds in notes I have for interacting with IB Lagrangian data. Fixes #1040.

Updated documentation for LDataManager.

---

examples/CMakeLists.txt
examples/fe_mechanics/CMakeLists.txt
examples/fe_mechanics/ex0/CMakeLists.txt
src/CMakeLists.txt
tests/CMakeLists.txt

@boyceg Merge whenever you are ready.

Add CMake support.

---

ibtk/src/lagrangian/FEDataManager.cpp
ibtk/src/utilities/libmesh_utilities.cpp
include/ibamr/CFUpperConvectiveOperator.h
include/ibamr/FifthOrderStokesWaveGenerator.h
include/ibamr/IrregularWaveGenerator.h
include/ibamr/StaggeredStokesBoxRelaxationFACOperator.h
src/IB/DirectMobilitySolver.cpp
src/IB/FEMechanicsExplicitIntegrator.cpp
src/level_set/FESurfaceDistanceEvaluator.cpp

Fix gcc warnings

---

ibtk/include/ibtk/LDataManager.h
src/IB/IBHydrodynamicSurfaceForceEvaluator.cpp
src/navier_stokes/INSStaggeredHierarchyIntegrator.cpp
src/navier_stokes/INSStaggeredStabilizedPPMConvectiveOperator.cpp
src/navier_stokes/INSStaggeredUpwindConvectiveOperator.cpp
src/utilities/RNG.cpp
src/wave_generation/IrregularWaveBcCoef.cpp
src/wave_generation/StokesFifthOrderWaveBcCoef.cpp
src/wave_generation/StokesFirstOrderWaveBcCoef.cpp
src/wave_generation/StokesSecondOrderWaveBcCoef.cpp

Run clang-format

---

tests/IBTK/bounding_boxes_01.cpp
tests/IBTK/equal_eps.cpp
tests/wave_tank/SetFluidProperties.h

Fix some more clang warnings.

---

COPYRIGHT
ibtk/CMakeLists.txt
tests/IBTK/fischer_guess_01.cpp
tests/IBTK/subdomain_level_translation_01.cpp

Update copyright for 0.8.0

---

ibtk/src/boundary/cf_interface/CartCellDoubleQuadraticCFInterpolation.cpp
ibtk/src/math/PatchMathOps.cpp
src/IB/IBFEPatchRecoveryPostProcessor.cpp
src/IB/MobilityFunctions.cpp

Cppcheck 5

---

tests/wave_tank/SetFluidProperties.cpp

I'm not sure how I missed this in a previous PR. We really need to upgrade our
CI this year - I must have messed something up when I wrote multiple PRs back to back.

Fix compilation of a test.

---

doc/news/changes/minor/20201201HongNguyen
include/ibamr/ConstraintIBMethod.h
src/IB/ConstraintIBMethod.cpp

corrects the calculations of the COM, MOI and related quantities in the presence of periodic boundary for constraintIB

Periodic correction for the constraintsIB method

---

configure
examples/IBLevelSet/CMakeLists.txt
examples/IBLevelSet/ex1/CMakeLists.txt
examples/IBLevelSet/ex1/SetFluidSolidDensity.cpp
examples/IBLevelSet/ex1/SetFluidSolidDensity.h
examples/IBLevelSet/ex1/SetFluidSolidViscosity.cpp
examples/IBLevelSet/ex1/SetFluidSolidViscosity.h
examples/IBLevelSet/ex1/TagLSRefinementCells.cpp
examples/IBLevelSet/ex1/TagLSRefinementCells.h
examples/IBLevelSet/ex1/example.cpp
ibtk/configure
ibtk/m4/libtool.m4
m4/libtool.m4

I'm skipping the checklist since it doesn't really apply.
I fixed the autotools problems and also a few minor GCC warnings, in addition to getting things set up to work with CMake.
@Kaustubh-Khedkar Sorry this took me an extra week and a half. If you agree with the changes then lets merge this into your branch and then merge the whole thing.

1220 patch

---

examples/IBPD/explicit/ex1/Makefile.am
examples/IBPD/explicit/ex1/Makefile.in
examples/IBPD/explicit/ex1/generate_sheet2d.cpp
examples/IBPD/explicit/ex1/main.cpp

Update 2D IBPD

---

examples/IBPD/explicit/ex0/Makefile.am
examples/IBPD/explicit/ex0/Makefile.in
examples/IBPD/explicit/ex0/generate_membrane2d_failure.cpp
examples/IBPD/explicit/ex0/input2d_failure
examples/IBPD/explicit/ex0/main.cpp

Update PD w/ failure

---

examples/IBFE/explicit/ex2/example.cpp
examples/IBFE/explicit/ex3/example.cpp
examples/IBFE/explicit/ex5/example.cpp
examples/IBFE/explicit/ex9/example.cpp

Fix example compilation with libMesh's development branch.

---

doc/news/changes/incompatibilities/20210330DavidWells
ibtk/include/ibtk/FEDataManager.h
ibtk/src/lagrangian/FEDataManager.cpp

Part of the effort to completely decouple FEDataManager from FEProjector - see #1182.

Remove an unused function.

---

include/ibamr/IBFEMethod.h
src/IB/IBFEMethod.cpp

This is the first commit in a sequence which will refactor out the scratch hierarchy from IBFEMethod into a more general class (that could be used with IBMethod or other future IB-based classes). In particular, this commit just puts everything in a struct that IBFEMethod still manages. Part of #1235.

Move all scratch hierarchy objects into a separate class.

---

ibtk/src/solvers/impls/CCPoissonHypreLevelSolver.cpp
ibtk/src/solvers/impls/SCPoissonHypreLevelSolver.cpp

I get this error when I install hypre through homebrew. Since no one has mentioned it before I don't think its a big deal - unless someone complains I don't plan on putting it in 0.7.0.
This is still WIP since it causes a bunch of weird crashes.

Fix 64-bit hypre.

---

include/ibamr/IBFEMethod.h
src/IB/IBFEMethod.cpp

Move two functions into the secondary hierarchy class.

---

include/ibamr/IBFEMethod.h
src/IB/IBFEMethod.cpp

More of #1235 - this PR makes some `SecondaryHierarchy` fields protected and sets up a rudimentary constructor and reinit function.

Make some SecondaryHierarchy fields protected.

---

include/ibamr/IBFEMethod.h
src/IB/IBFEMethod.cpp

More progress towards #1235 - this PR moves some initialization into that class.

Refactor scratch hierarchy 4

---

ibtk/include/ibtk/SecondaryHierarchy.h
ibtk/lib/Makefile.am
ibtk/lib/Makefile.in
ibtk/src/CMakeLists.txt
ibtk/src/utilities/SecondaryHierarchy.cpp
include/ibamr/IBFEMethod.h
src/IB/IBFEMethod.cpp

Yet another part of #1235. We're getting closer - the main things left now are adding some more accessor functions and then cleaning up the load balancing logic (which will put a big dent in #1126, since we will avoid calculating workloads two more times).

Move the SecondaryHierarchy to its own file in IBTK.

---

configure
examples/IBLevelSet/ex0/example.cpp
examples/complex_fluids/ex2/example.cpp
examples/complex_fluids/ex4/example.cpp
ibtk/configure
m4/configure_libmesh.m4
tests/level_set/fe_surface_distance.cpp
tests/wave_tank/nwt_cylinder.cpp

Fortunately this is all the autotools scripts need to work with the development copy of libMesh.

Remove libMesh::UniquePtr.

---

examples/IBLevelSet/ex0/example.cpp
examples/complex_fluids/ex2/example.cpp
examples/complex_fluids/ex4/example.cpp

Followup to #1229: It looks like I forgot to check non-IBFE examples.

Fix compilation with the development version of libMesh.

---

doc/news/changes/incompatibilities/20210517DavidWells
doc/news/changes/major/20210517DavidWells
ibtk/include/ibtk/SecondaryHierarchy.h
ibtk/src/utilities/SecondaryHierarchy.cpp
src/IB/IBFEMethod.cpp
tests/CMakeLists.txt
tests/IBFE/explicit_ex4_2d.postprocessor.scratch_hier.mpirun=4.output
tests/IBFE/explicit_ex4_2d.scratch_hier.levels=1.mpirun=4.output
tests/IBFE/explicit_ex4_2d.scratch_hier.levels=4.mpirun=4.output
tests/IBFE/explicit_ex4_2d.scratch_hier.merge.mpirun=4.output
tests/IBFE/explicit_ex4_2d.scratch_hier.mpirun=4.output
tests/IBFE/explicit_ex4_2d.scratch_hier.multilevel.b.mpirun=4.output
tests/IBFE/explicit_ex4_2d.scratch_hier.multilevel.b.output
tests/IBFE/explicit_ex4_2d.scratch_hier.nodeweight.mpirun=4.output
tests/IBFE/explicit_ex4_2d.scratch_hier.restart=25.mpirun=4.output
tests/IBFE/explicit_ex4_3d.scratch_hier.merge.mpirun=4.output
tests/IBFE/explicit_ex4_3d.scratch_hier.mpirun=4.output
tests/IBFE/explicit_ex8_2d.scratch_hier.mpirun=4.output
tests/IBTK/Makefile.am
tests/IBTK/Makefile.in
tests/IBTK/secondary_hierarchy_01.cpp
tests/IBTK/secondary_hierarchy_01_2d.input
tests/IBTK/secondary_hierarchy_01_2d.mpirun=4.input
tests/IBTK/secondary_hierarchy_01_2d.mpirun=4.output
tests/IBTK/secondary_hierarchy_01_2d.output

Fixes #1235. This patch is longer than the others since it moves both tagging and load balancing into the SecondaryHierarchy (which requires that IBFEMethod no longer do those things in some contexts).

Refactor scratch hierarchy 7

---

.gitignore
doc/news/changes/major/20210529BoyceGriffith
include/ibamr/IBKirchhoffRodForceGen.h
include/ibamr/IBStandardForceGen.h
src/IB/IBKirchhoffRodForceGen.cpp
src/IB/IBRedundantInitializer.cpp
src/IB/IBStandardForceGen.cpp
tests/CMakeLists.txt
tests/IB/Makefile.am
tests/IB/Makefile.in
tests/IB/ib_body_force.cpp
tests/IB/ib_body_force.input
tests/IB/ib_body_force.output
tests/IB/ib_body_force_kirchhoff.cpp
tests/IB/ib_body_force_kirchhoff.input
tests/IB/ib_body_force_kirchhoff.output

add support for uniform body forces for IB structures

---

tests/ConstraintIB/oscillating_rigid_cylinder.cpp
tests/IBTK/child_integrators.cpp

Fix some more minor warnings in tests.

---

ibtk/include/ibtk/SecondaryHierarchy.h
ibtk/src/utilities/SecondaryHierarchy.cpp
src/IB/IBFEMethod.cpp
tests/IBTK/secondary_hierarchy_01.cpp

Refactor scratch hierarchy 9

---

ibtk/src/lagrangian/FischerGuess.cpp

We very occasionally get reports that this causes crashes on the mailing list -
I am pretty sure that those cases would always be followed by the solver
crashing but to be safe lets check the SVD calculation some more.
Fixes #1266.

Catch all errors for the SVD calculation in FischerGuess.

---

ibtk/src/solvers/impls/CCPoissonPETScLevelSolver.cpp
ibtk/src/solvers/impls/PETScLevelSolver.cpp
ibtk/src/solvers/impls/SCPoissonPETScLevelSolver.cpp
ibtk/src/solvers/impls/VCSCViscousPETScLevelSolver.cpp
src/navier_stokes/StaggeredStokesPETScLevelSolver.cpp

These are used by the base class only. I think they were added by iwyu.

Remove some unused includes.

---

tests/IB/explicit_ex0.cpp
tests/IB/explicit_ex1.cpp
tests/IB/ib_body_force.cpp
tests/IB/ib_body_force_kirchhoff.cpp

Silence some warnings if Silo isn't present.

---

attest
tests/attest.conf.in

Attest cleanup

---

src/IB/IBBeamForceSpecFactory.cpp
src/IB/IBFEInstrumentPanel.cpp
src/IB/IBRedundantInitializer.cpp
src/IB/IBStandardInitializer.cpp
src/utilities/RNG.cpp

Use std::vector::data().

---

examples/IBLevelSet/ex1/SetFluidSolidDensity.cpp
examples/IBLevelSet/ex1/SetFluidSolidDensity.h
examples/IBLevelSet/ex1/SetFluidSolidViscosity.cpp
examples/IBLevelSet/ex1/SetFluidSolidViscosity.h
ibtk/src/lagrangian/LSiloDataWriter.cpp
src/IB/IBInstrumentPanel.cpp
src/utilities/RNG.cpp
tests/ConstraintIB/oscillating_rigid_cylinder.cpp
tests/IBTK/child_integrators.cpp
tests/level_set/fe_surface_distance.cpp

A small number of fixes for the release.

Release 0.9 cleanups

---

cmake/IBAMRConfig.cmake.in

Remove a debugging message.

---

ibtk/contrib/boost/boost/predef/hardware/simd.h

Backport a boost fix.

---

Makefile.am
Makefile.in
configure
configure.ac
tests/CMakeLists.txt
tests/IBTK/Makefile.am
tests/IBTK/Makefile.in
tests/IBTK/version_macros.cpp
tests/IBTK/version_macros.output

Ibamr 0.9 version fix

---

ibtk/src/utilities/HierarchyIntegrator.cpp

Fixes #1346.
In general, inheriting classes (like IBHierarchyIntegrator or INSHierarchyIntegrator) do not reimplement these functions (they implement specialized versions, e.g., applyGradientDetectorSpecialized) so we get good measurements from these for the whole simulation.

Add timers to major HierarchyIntegrator functions.

---

src/IB/DirectMobilitySolver.cpp

First part of #1215 - we can replace everything we use LAPACK for with Eigen, our preferred dense linear algebra library.
One odd thing I noticed is that the mobility matrix isn't actually symmetric, though it is pretty close (off-diagonals are orders of magnitude smaller than diagonal entries). We could definitely switch to an SVD solver here instead, but I only changed the minimum necessary to get things working with Eigen.
@amneetb no rush, but I think you should review this one. We do have some tests that use the SVD-based solver and they pass (and the computed torques and drags are the same to 8+ digits).
or …

Use Eigen, not LAPACK, for eigenvalues.

---

ibtk/include/ibtk/CCPoissonHypreLevelSolver.h
ibtk/include/ibtk/PETScKrylovLinearSolver.h
ibtk/include/ibtk/PETScNewtonKrylovSolver.h
ibtk/include/ibtk/SCPoissonHypreLevelSolver.h
ibtk/include/ibtk/solver_utilities.h
ibtk/lib/Makefile.am
ibtk/lib/Makefile.in
ibtk/src/CMakeLists.txt
ibtk/src/solvers/impls/CCPoissonHypreLevelSolver.cpp
ibtk/src/solvers/impls/PETScKrylovLinearSolver.cpp
ibtk/src/solvers/impls/PETScNewtonKrylovSolver.cpp
ibtk/src/solvers/impls/SCPoissonHypreLevelSolver.cpp
ibtk/src/solvers/solver_utilities.cpp
include/ibamr/CIBSaddlePointSolver.h
include/ibamr/KrylovFreeBodyMobilitySolver.h
include/ibamr/KrylovMobilitySolver.h
src/IB/CIBSaddlePointSolver.cpp
src/IB/KrylovFreeBodyMobilitySolver.cpp
src/IB/KrylovMobilitySolver.cpp

I'm reading through a lot of the solver code. This cleans up some of the code by moving some private member functions to external functions.

Clean up solvers.

---

ibtk/src/solvers/solver_utilities.cpp

add #include <memory> to ibtk solver_utilities

---

include/ibamr/CFINSForcing.h
include/ibamr/IBFESurfaceMethod.h
include/ibamr/INSHierarchyIntegrator.h
src/IB/IBFESurfaceMethod.cpp
src/complex_fluids/CFINSForcing.cpp
src/navier_stokes/INSCollocatedHierarchyIntegrator.cpp
src/navier_stokes/INSHierarchyIntegrator.cpp
src/navier_stokes/INSStaggeredHierarchyIntegrator.cpp
src/navier_stokes/INSVCStaggeredConservativeHierarchyIntegrator.cpp
src/navier_stokes/INSVCStaggeredHierarchyIntegrator.cpp
src/navier_stokes/INSVCStaggeredNonConservativeHierarchyIntegrator.cpp

Remove some more raw pointers.

---

ibtk/include/ibtk/private/IndexUtilities-inl.h
ibtk/src/lagrangian/LDataManager.cpp
src/IB/IBFESurfaceMethod.cpp
src/IB/IBRedundantInitializer.cpp
src/IB/IMPMethod.cpp

We can use std::round() here instead.

Remove calls to boost::math::round().

---

doc/news/changes/minor/20210903DavidWells
src/IB/DirectMobilitySolver.cpp
tests/CIB/cib_double_shell.cholesky.input
tests/CIB/cib_double_shell.cholesky.output
tests/CIB/cib_double_shell.cpp
tests/CIB/cib_double_shell.lu.input
tests/CIB/cib_double_shell.lu.output

Fixes #1215.
More progress on #1215: it is pretty easy to use Eigen's own solvers instead.
I added a new test that verifies that we get the same results (up to the usual absolute and relative numerical tolerances) for the Cholesky option in `DirectMobilitySolver`.
Edit: add fix tag.

Use Eigen, not LAPACK, for the Cholesky and PLU decompositions.

---

doc/release-tasks.md
src/IB/DirectMobilitySolver.cpp

Same problem as #1356 - I forgot to fix it in #1353 (which was just merged).

Fix eigen index again

---

ibtk/include/ibtk/private/IBTK_MPI-inl.h

Part of #1371 - this check makes the original failure much easier to understand.

add another check to IBTK_MPI.

---

examples/IBFE/explicit/ex8/example.cpp
examples/IBLevelSet/ex2/FlowGravityForcing.h
examples/IBLevelSet/ex2/SetFluidGasSolidDensity.cpp
examples/IBLevelSet/ex2/SetFluidGasSolidDensity.h
examples/IBLevelSet/ex2/SetFluidGasSolidViscosity.cpp
examples/IBLevelSet/ex2/SetFluidGasSolidViscosity.h
examples/complex_fluids/ex2/example.cpp
ibtk/src/lagrangian/BoxPartitioner.cpp
ibtk/src/lagrangian/LEInteractor.cpp

A bunch of little stuff for the release.

Misc fixes

---

doc/news/changes/0.9.0-vs-0.10.0.html
doc/news/changes/incompatibilities/20211215DavidWells
doc/news/changes/major/202117KolahdouzWells
doc/news/changes/minor/20210903DavidWells
doc/news/changes/minor/20211001DavidWells
doc/news/changes/minor/20211018DavidWells
doc/news/changes/minor/20211022DavidWells
doc/news/changes/minor/20211215AmneetBhalla
doc/news/changes/minor/20211215DavidWells
doc/news/changes/minor/20211223AaronBarrett

It's just a documentation change so the normal checklist does not apply.

Collate changelog entries.

---

doc/release-tasks.md

We have a script to do this now.
This is just internal documentation so the checklist isn't relevant.

Update the release tasks.

---

CMakeLists.txt
cmake/IBAMRConfig.cmake.in
doc/cmake.md

Port #1397 and #1398 to the release branch.

Ibamr 0.10 cmake

---

CMakeLists.txt

Same as #1400 (and #1401) but for the release branch.

Work around an rpath problem on macOS.

---

attest

attest: Clean up the expect_error() function.

---

doc/release-tasks.md

Explicitly remind us to check example compilation.

---

include/ibamr/IBStrategy.h

The default implementation does something here.

Fix documentation in IBStrategy.

---

.github/workflows/push-pull.yml

If you look at the log files from the last PR you can see that sccache never gets used. I'm trying to fix that now.

Fix sccache population

---

tests/CIB/cib_plate.small.mpirun=2.input
tests/CIB/cib_plate.small.mpirun=2.output
tests/CMakeLists.txt
tests/IB/explicit_ex0.quartersquare2.mpirun=4.input
tests/IB/explicit_ex0.quartersquare2.mpirun=4.output

Another minor build system patch.
I prefer to use capital letters for all built ins so that they stick out. Whether or not that is a good choice is debatable (I think its deprecated behavior) but no matter the style we should be consistent.

Cleanup test regex

---

.github/cmake/configure_common.cmake
.github/workflows/push-pull.yml
CMakeLists.txt
ibtk/contrib/boost/boost/math/quadrature/gauss.hpp
ibtk/contrib/boost/boost/math/quadrature/gauss_kronrod.hpp
ibtk/contrib/muparser/src/muParserBase.cpp
src/IB/IBRedundantInitializer.cpp
tests/IBTK/ldata_01.cpp

Another CI patch: error out if there are warnings. Lets see what happens.

CI: error out on warnings.

---

src/IB/FEMechanicsBase.cpp

Add a timer for FEMechanicsBase::assembleInteriorForceDensityRHS().

---

ibtk/include/ibtk/libmesh_utilities.h
src/IB/FEMechanicsBase.cpp
src/IB/IBFEMethod.cpp
src/IB/IBMethod.cpp
src/IB/IBStandardForceGen.cpp
src/IB/IBStandardInitializer.cpp
src/IB/IBStandardSourceGen.cpp
src/IB/IMPInitializer.cpp
src/adv_diff/AdvDiffHierarchyIntegrator.cpp

Gcc 12 warnings

---

doc/news/changes/minor/20220411DavidWells
ibtk/include/ibtk/FEMapping.h
ibtk/src/lagrangian/FEMapping.cpp
src/IB/FEMechanicsBase.cpp
tests/fe_mechanics/fe_mechanics_ex0.cpp
tests/fe_mechanics/fe_mechanics_ex0_2d.mpirun=4.output
tests/fe_mechanics/fe_mechanics_ex0_2d.output
tests/fe_mechanics/fe_mechanics_ex0_3d.mpirun=4.output
tests/fe_mechanics/fe_mechanics_ex0_3d.output

Check element jacobians

---

ibtk/configure
ibtk/configure.ac
ibtk/lib/Makefile.am
ibtk/lib/Makefile.in
ibtk/src/CMakeLists.txt
ibtk/src/math/fortran/interp2d.f.m4
ibtk/src/math/fortran/interp3d.f.m4
ibtk/src/math/fortran/vclaplace2d.f.m4
ibtk/src/math/fortran/vclaplace3d.f.m4
ibtk/src/solvers/impls/fortran/patchsmoothers2d.f.m4
ibtk/src/solvers/impls/fortran/patchsmoothers3d.f.m4
ibtk/src/utilities/fortran/Makefile.am
ibtk/src/utilities/fortran/Makefile.in
ibtk/src/utilities/fortran/averaging.f.m4
src/navier_stokes/INSVCStaggeredPressureBcCoef.cpp

Hi @drwells, 
I have fixed the harmonic averaging for the corner case of arguments with zero value. This avoids the division by zero. I have also moved the arithmetic and harmonic averaging routines into one Fortran module to do function overloading. Please take a look.

Fix harmonic averaging for the corner case of arguments with zero value

---

src/IB/IIMethod.cpp

From a discussion on slack today - we might want to measure performance here so add timers.

Add timers to IIMMethod.

---

ibtk/src/lagrangian/FEDataInterpolation.cpp
ibtk/src/lagrangian/FEMapping.cpp

Fixes #697. IBAMR compiles just fine with intel but we will need to patch some more things to make SAMRAI happy.

Fix some minor intel warnings.

---

ibtk/include/ibtk/SecondaryHierarchy.h
ibtk/src/lagrangian/LEInteractor.cpp
ibtk/src/utilities/SnapshotCache.cpp
tests/IBTK/ldata_01.cpp
tests/IBTK/version_macros.cpp

A few things are just clang-format version churn - I skipped them.

Run clang-format on everything.

---

doc/news/changes/0.10.0-vs-0.11.0.html
doc/news/changes/incompatibilities/20200426AaronBarrett
doc/news/changes/incompatibilities/20220317DavidWells
doc/news/changes/major/20220516ColeGruninger
doc/news/changes/major/20220629AminKolahdouz
doc/news/changes/minor/20220121DavidWells
doc/news/changes/minor/20220208KaustubhAmneet
doc/news/changes/minor/20220218AaronBarrett
doc/news/changes/minor/20220221DavidWells
doc/news/changes/minor/20220307DavidWells
doc/news/changes/minor/20220308AaronBarrett
doc/news/changes/minor/20220411DavidWells
doc/news/changes/minor/20220428DavidWells
doc/news/changes/minor/20220526AaronBarrett
doc/news/changes/minor/20220707AaronBarrettColeGruninger

Collate the changelog entries.

Collage changelog entries.

---

ibtk/src/solvers/impls/PETScKrylovLinearSolver.cpp
ibtk/src/solvers/impls/PETScLevelSolver.cpp
ibtk/src/solvers/impls/PETScMFFDJacobianOperator.cpp
ibtk/src/solvers/impls/PETScNewtonKrylovSolver.cpp
ibtk/src/solvers/wrappers/PETScSAMRAIVectorReal.cpp
src/IB/CIBSaddlePointSolver.cpp
src/IB/KrylovFreeBodyMobilitySolver.cpp
src/IB/KrylovMobilitySolver.cpp

This is necessary for compatibility with PETSc in debug mode.

Add PetscFunctionBeginUser where appropriate.

---

ibtk/src/lagrangian/FEProjector.cpp

Allow for the 1st order monomial w/o lumped mass matrix as a preconditioner

---

examples/IIM/ex2/example.cpp
examples/IIM/ex3/example.cpp
examples/IIM/ex4/example.cpp
examples/IIM/ex5/example.cpp
examples/IIM/ex7/example.cpp
examples/IIM/ex8/example.cpp

switch uses of libMesh::UniquePtr to std::unique_ptr

---

src/IB/IBFEInstrumentPanel.cpp
tests/IBFE/instrument_panel_01.cpp
tests/IBFE/instrument_panel_01_3d.BSPLINE_3.input
tests/IBFE/instrument_panel_01_3d.BSPLINE_3.output
tests/IBFE/instrument_panel_01_3d.mpirun=8.BSPLINE_3.input
tests/IBFE/instrument_panel_01_3d.mpirun=8.BSPLINE_3.output
tests/IBFE/instrument_panel_01_3d.mpirun=8.output
tests/IBFE/instrument_panel_01_3d.output

This adds checks for the meter mesh velocity correction.

enhance IBFEInstrumentPanel test coverage

---

include/ibamr/IBFEInstrumentPanel.h
src/IB/IBFEInstrumentPanel.cpp
tests/IBFE/instrument_panel_01.cpp
tests/IBFE/instrument_panel_01_3d.BSPLINE_3.input
tests/IBFE/instrument_panel_01_3d.input
tests/IBFE/instrument_panel_01_3d.mpirun=8.BSPLINE_3.input
tests/IBFE/instrument_panel_01_3d.mpirun=8.input
tests/IBFE/instrument_panel_01_3d.pressure.input
tests/IBFE/instrument_panel_01_3d.pressure.mpirun=4.input
tests/IBFE/instrument_panel_01_3d.pressure.mpirun=4.output
tests/IBFE/instrument_panel_01_3d.pressure.mpirun=8.input
tests/IBFE/instrument_panel_01_3d.pressure.mpirun=8.output
tests/IBFE/instrument_panel_01_3d.pressure.output

add a central pressure tap to IBFE instrument panel

---

doc/news/changes/minor/20221102GriffithPuelz
doc/news/changes/minor/20221102GriffithWells
src/IB/IBFEInstrumentPanel.cpp
tests/IBFE/instrument_panel_01.cpp
tests/IBFE/instrument_panel_01_3d.BSPLINE_3.output
tests/IBFE/instrument_panel_01_3d.mpirun=8.BSPLINE_3.output
tests/IBFE/instrument_panel_01_3d.mpirun=8.output
tests/IBFE/instrument_panel_01_3d.output

Similar to #1508 but with what I think is a simpler algorithm.

update algorithm to order perimeter nodes for the meter meshes

---

tests/IBFE/instrument_panel_01.cpp
tests/IBFE/instrument_panel_01_3d.skip_nodes.input
tests/IBFE/instrument_panel_01_3d.skip_nodes.mpirun=4.input
tests/IBFE/instrument_panel_01_3d.skip_nodes.mpirun=4.output
tests/IBFE/instrument_panel_01_3d.skip_nodes.output

The node reordering code handles this correctly now.

IBFEInstrumentPanel: add tests with missing nodes.

---

include/ibamr/INSStaggeredHierarchyIntegrator.h
src/navier_stokes/INSStaggeredHierarchyIntegrator.cpp

these quantities should be computed instead using the new averaging infrastructure.

remove broken code for computing flow statistics

---

doc/news/changes/minor/20221115Griffith
examples/fe_mechanics/ex0/example.cpp
include/ibamr/FEMechanicsBase.h
include/ibamr/FEMechanicsExplicitIntegrator.h
src/IB/FEMechanicsExplicitIntegrator.cpp
tests/fe_mechanics/fe_mechanics_ex0.cpp
tests/fe_mechanics/fe_mechanics_ex0_2d.SSPRK33.input
tests/fe_mechanics/fe_mechanics_ex0_2d.SSPRK33.output
tests/fe_mechanics/fe_mechanics_ex0_2d.SSPRK34.input
tests/fe_mechanics/fe_mechanics_ex0_2d.SSPRK34.output

add SSP RK3 time stepping to the explicit FEM solver

---

doc/news/changes/minor/20221117Griffith
include/ibamr/FEMechanicsExplicitIntegrator.h
src/IB/FEMechanicsExplicitIntegrator.cpp
tests/fe_mechanics/fe_mechanics_ex0_2d.damping.input
tests/fe_mechanics/fe_mechanics_ex0_2d.damping.output

add real support for damping to explicit FE mechanics solver

---

examples/IIM/ex2/example.cpp
examples/IIM/ex3/example.cpp
examples/IIM/ex4/example.cpp
examples/IIM/ex5/example.cpp
examples/IIM/ex6/example.cpp
examples/IIM/ex7/example.cpp
examples/IIM/ex8/example.cpp
examples/IIM/ex9/example.cpp

More release prep - some of the IIM examples don't work with the development version of libMesh due to changes in their API (see also #1443)

IIM: fix const correctness with the latest version of libMesh.

---

CMakeLists.txt

This fixes some obscure problems which I ran into on my mac. Lets see what the CI thinks.

CMake: clean up link order.

---

examples/IBFE/explicit/ex8/example.cpp
examples/IIM/ex3/example.cpp
examples/IIM/ex4/example.cpp
examples/IIM/ex5/example.cpp
examples/IIM/ex6/example.cpp
examples/IIM/ex7/example.cpp
examples/IMP/explicit/ex0/main.cpp

Do not recompute libMesh end interators.

---

ibtk/src/lagrangian/LDataManager.cpp
src/IB/IIMethod.cpp
src/IB/WallForceEvaluator.cpp
src/navier_stokes/INSCollocatedVelocityBcCoef.cpp

More minor stuff for the release.

Use hier::Index everywhere to disambiguate from Eigen::Index.

---

CMakeLists.txt
doc/news/changes/0.12.0-vs-0.12.1.html

[0.12] Fix the link order again.

---

src/IB/IBStrategy.cpp

Actually give some useful advice on how to fix the problem @cpuelz asked about over the weekend.

Improve an error message.

---

src/IB/IBPDForceGen.cpp

Fix regridding with 3D

---

doc/news/changes/minor/20230411DavidWells
ibtk/src/math/SAMRAIGhostDataAccumulator.cpp

Add timers for SAMRAIGhostDataAccumulator.

---

src/IB/FEMechanicsExplicitIntegrator.cpp

I noticed this when looking at something with @jabrown893.

Add timers to FEMechanicsExplicitIntegrator.

---

src/IB/IBExplicitHierarchyIntegrator.cpp
tests/IBFE/explicit_ex4.cpp
tests/IBFE/explicit_ex4_2d.vanishingmarkers.mpirun=2.input
tests/IBFE/explicit_ex4_2d.vanishingmarkers.mpirun=2.output

We can now unset markers and then set them up again later.

Fix some more marker bugs.

---

README.md

Credit goes to Benjamin Edwards for pointing out that the visit link is dead - I checked every link and updated the remaining dead ones.

Fix a bunch of dead links.

---

CMakeLists.txt

The checklist is irrelevant because I just changed the build script.

put mpi link in correct place in CMakeLists.txt

---

ibtk/include/ibtk/SAMRAIScopedVectorDuplicate.h

Fix missing include in SAMRAIScopedVectorDuplicate.

---

doc/news/changes/incompatibilities/20230524DavidWells

Followup to a comment Aaron made elsewhere.

Document the (minor) solver incompatibility.

---

ibtk/include/ibtk/LMesh.h
ibtk/src/lagrangian/LMesh.cpp
ibtk/src/utilities/box_utilities.cpp

Fix some clang-15 warnings.

---

CMakeLists.txt
ibtk/config/config.h.tmp
ibtk/include/ibtk/config.h.in
ibtk/include/ibtk/libmesh_utilities.h
ibtk/src/lagrangian/FEDataManager.cpp
ibtk/src/lagrangian/FEValues.cpp

GCC 13 warning fixes

---

doc/news/changes/minor/20230413BoyceGriffith
include/ibamr/AdvDiffCUIConvectiveOperator.h
include/ibamr/AdvDiffCenteredConvectiveOperator.h
include/ibamr/AdvDiffPPMConvectiveOperator.h
include/ibamr/CellConvectiveOperator.h
lib/Makefile.am
lib/Makefile.in
src/CMakeLists.txt
src/adv_diff/AdvDiffCUIConvectiveOperator.cpp
src/adv_diff/AdvDiffCenteredConvectiveOperator.cpp
src/adv_diff/AdvDiffPPMConvectiveOperator.cpp
src/utilities/CellConvectiveOperator.cpp

One extra check: this needs to restore support for `SKEW_SYMMETRIC` differencing:

update convective operators for the advection-diffusion solver

---

examples/complex_fluids/ex0/example.cpp
examples/complex_fluids/ex0/input2d
examples/complex_fluids/ex1/example.cpp
examples/complex_fluids/ex1/input2d
examples/complex_fluids/ex2/example.cpp
examples/complex_fluids/ex2/input2d
examples/complex_fluids/ex3/example.cpp
examples/complex_fluids/ex3/input2d
examples/complex_fluids/ex4/example.cpp
examples/complex_fluids/ex4/input2d

Related to #1632. This came up on the listserv. `complex_fluids/ex4` needs a larger penalty parameter. I updated the example to bring it in line with the write-up. I also went ahead and updated some comments and cleaned the input files for the rest of the complex fluid examples.

Fix complex_fluids/ex4.

---

include/ibamr/MarangoniSurfaceTensionForceFunction.h
include/ibamr/SurfaceTensionForceFunction.h
lib/Makefile.am
lib/Makefile.in
src/CMakeLists.txt
src/navier_stokes/MarangoniSurfaceTensionForceFunction.cpp
src/navier_stokes/SurfaceTensionForceFunction.cpp
src/navier_stokes/fortran/navier_stokes_surface_tension_forcing2d.f.m4
src/navier_stokes/fortran/navier_stokes_surface_tension_forcing3d.f.m4

Phase change patch 2: variable coefficient and Marangoni surface tension

---

doc/news/changes/minor/20230911Ramakrishnan
examples/IBLevelSet/ex0/input2d
examples/IBLevelSet/ex1/Makefile.am
examples/IBLevelSet/ex1/Makefile.in
examples/IBLevelSet/ex1/input2d_dynamic_mesh
examples/IBLevelSet/ex1/input2d_static_mesh
examples/IBLevelSet/ex2/input2d
examples/IBLevelSet/ex3/input2d
examples/IBLevelSet/ex4/input2d
examples/IBLevelSet/ex5/input2d
examples/adv_diff/ex3/input2d
examples/adv_diff/ex4/input2d
examples/adv_diff/ex5/input2d
examples/adv_diff/ex6/input2d
examples/adv_diff/ex6/input3d
examples/adv_diff/ex7/input2d
include/ibamr/BrinkmanPenalizationRigidBodyDynamics.h
include/ibamr/BrinkmanPenalizationStrategy.h
include/ibamr/MarangoniSurfaceTensionForceFunction.h
src/IB/BrinkmanPenalizationRigidBodyDynamics.cpp
src/IB/BrinkmanPenalizationStrategy.cpp
src/navier_stokes/MarangoniSurfaceTensionForceFunction.cpp
tests/adv_diff/bp_adv_diff_01_2d.input
tests/adv_diff/bp_adv_diff_02_2d.mpirun=8.input
tests/wave_tank/nwt_cylinder.mpirun=8.input

Changes to BrinkmanPenalization class and associated changes in the input files. Very trivial change to a default value in Marangoni surface tension header file.

Phase change patch 3: Changes to BrinkmanPenalization class and associated changes in the input files

---

include/ibamr/AdvDiffConservativeMassScalarTransportRKIntegrator.h
include/ibamr/MarangoniSurfaceTensionForceFunction.h
lib/Makefile.am
lib/Makefile.in
src/CMakeLists.txt
src/adv_diff/AdvDiffConservativeMassScalarTransportRKIntegrator.cpp

Phase change patch 4: Adding cell centered mass integrator using RK1/2 schemes to find the convective flux related to a transport quantity

---

.github/workflows/push-master.yml
generateDocumentationAndDeploy.sh

Part of the ongoing project to improve our documentation - lets get doxygen building again.
This PR just copies and pastes the travis build steps into a GitHub action. If that much works then we can start cleaning this up.

Doxygen resurrection

---

ibtk/include/ibtk/CartCellDoubleQuadraticCFInterpolation.h
ibtk/include/ibtk/CartSideDoubleQuadraticCFInterpolation.h
tests/CMakeLists.txt
tests/IBTK/cf_interface.cpp
tests/IBTK/cf_interface_2d.cell.input
tests/IBTK/cf_interface_2d.side.input
tests/IBTK/cf_interface_3d.cell.input
tests/IBTK/cf_interface_3d.side.input

This has confused me several times now, so I'll fix it before I forget again. This adds a test for the coarse fine interpolation operators. This also improves the documentation, complete with ascii art.

Document and test the coarse fine interpolation.

---

doc/news/changes/minor/20231127Ramakrishnan
examples/adv_diff/ex8/CMakeLists.txt
examples/adv_diff/ex8/Makefile.am
examples/adv_diff/ex8/Makefile.in
examples/adv_diff/ex8/TagLSRefinementCells.cpp
examples/adv_diff/ex8/TagLSRefinementCells.h
examples/adv_diff/ex8/example.cpp
examples/adv_diff/ex8/input2d.amr
examples/adv_diff/ex8/write_ascii.cpp
src/IB/BrinkmanAdvDiffBcHelper.cpp
tests/CMakeLists.txt
tests/adv_diff/LevelSetInitialCondition1D.cpp
tests/adv_diff/LevelSetInitialCondition1D.h
tests/adv_diff/Makefile.am
tests/adv_diff/Makefile.in
tests/adv_diff/bp_adv_diff_zero_flux.cpp
tests/adv_diff/bp_adv_diff_zero_flux_2d.input
tests/adv_diff/bp_adv_diff_zero_flux_2d.output

…_diff/ex8
I removed a bug related to homogeneous boundary conditions in ```BrinkmanAdvDiffBcHelper``` class and also made changes related to AMR in the examples/adv_diff/ex8. Please take a look and let me know your suggestions.

Remove bug related to homogeneous boundary conditions and Add AMR to examples/adv_diff_ex8

---

ibtk/include/ibtk/IBTK_MPI.h
ibtk/include/ibtk/private/IBTK_MPI-inl.h
ibtk/src/utilities/IBTK_MPI.cpp

Fixes #1656 as well as some other minor issues.

Various mpi bugs

---

ibtk/config/config.h.tmp

avoid compiling boost code that is incompatible with C++17

---

tests/adv_diff/adv_diff_regridding.cpp

There should only be one thing in this array.

Fix an invalid memory reference.

---

ibtk/include/ibtk/config.h.in

Fix a new GCC warning.

---

CMakeLists.txt

This doesn't work with the test suite and is a bad idea anyway.

Prevent in-source builds.

---

doc/news/changes/minor/20240104DavidWells
examples/IBFE/explicit/ex4/example.cpp
include/ibamr/IBExplicitHierarchyIntegrator.h
src/IB/IBExplicitHierarchyIntegrator.cpp
tests/IBFE/explicit_ex4.cpp
tests/IBFE/explicit_ex4_2d.markers.regrid.mpirun=2.restart=70.input
tests/IBFE/explicit_ex4_2d.markers.regrid.mpirun=2.restart=70.output

Marker restart bug

---

ibtk/src/utilities/IBTKInit.cpp
ibtk/src/utilities/IBTK_MPI.cpp

These version checks don't make sense any more.

Make things work with IBSAMRAI2 version 2024.

---

include/ibamr/CFINSForcing.h
src/complex_fluids/CFINSForcing.cpp
tests/complex_fluids/cf_forcing_op_01.cpp
tests/complex_fluids/cf_forcing_op_01_2d.draw.input
tests/complex_fluids/cf_forcing_op_01_2d.draw.output
tests/complex_fluids/cf_forcing_op_01_3d.draw.input
tests/complex_fluids/cf_forcing_op_01_3d.draw.output

This is a follow up to #1672. I forgot to call the function that sets up the output of the conformation tensor. I've also added a test that this variable gets set correctly.

Fix drawing of conformation tensor.

---

doc/news/changes/minor/20240301AaronBarrett
ibtk/src/boundary/physical_boundary/StaggeredPhysicalBoundaryHelper.cpp
tests/CMakeLists.txt
tests/physical_boundary/staggered_helper.cpp
tests/physical_boundary/staggered_helper_2d.input
tests/physical_boundary/staggered_helper_2d.output
tests/physical_boundary/staggered_helper_3d.input
tests/physical_boundary/staggered_helper_3d.output

Fixes the masking function of `StaggeredPhysicalBoundaryHelper` for Dirichlet boundaries.

Fix masking function of StaggeredPhysicalBoundaryHelper.

---

scripts/formatting/compile-clang-format
scripts/formatting/download-clang-format
scripts/formatting/indent_common.sh

Mostly fixes to make things work on macs.

Clang format scripts

---

Makefile.am
Makefile.in

More infrastructure stuff - see https://github.com/IBAMR/IBAMR/pull/1687#issuecomment-2030104766.

Add autotools commands for 'make indent' and 'make indent-all'.

---

.github/workflows/push-pull.yml

We've exhausted our free CI hours partially because some of the caching isn't right. I'm investigating.

More ci cleanup

---

include/ibamr/StaggeredStokesBlockPreconditioner.h
tests/IBTK/curl_01.cpp
tests/IBTK/snapshot_cache_01.cpp
tests/adv_diff/SetFluidProperties.cpp
tests/complex_fluids/cf_four_roll_mill.cpp

A bunch of small things I found with GCC 14.

Fix some minor warnings.

---

.github/cmake/configure_archlinux.cmake
.github/cmake/configure_centos7.cmake
.github/cmake/configure_fedora33.cmake
.github/cmake/configure_fedora33_no_libmesh.cmake

Set up the CI to error-out on Fortran warnings.

---

CMakeLists.txt
src/IB/IIMethod.cpp

We use std::round() everywhere else.

Remove boost::math::iround().

---

include/ibamr/AdvDiffSemiImplicitHierarchyIntegrator.h

include ConvectiveOperator.h in AdvDiffSemiImplicitHierarchyIntegrator

---

examples/IBLevelSet/ex1/example.cpp
examples/multiphase_flow/ex10/example.cpp
examples/multiphase_flow/ex10/input2d
examples/multiphase_flow/ex13/example.cpp
examples/multiphase_flow/ex13/input3d
examples/multiphase_flow/ex9/example.cpp
examples/multiphase_flow/ex9/input2d.flow
examples/multiphase_flow/ex9/input2d.full
examples/wave_tank/ex1/LSLocateGasInterface.cpp
examples/wave_tank/ex1/input2d

Corrections in multiphase ex9 and ex10 and IBLevelSet ex1

---

src/IB/IBFEInstrumentPanel.cpp

include constructor arguments

---

.github/workflows/push-pull.yml

I updated all the actions - I think they are all backwards-compatible. If not I'll patch things.
CI change - normal checklist doesn't apply.

Update CI actions.

---

.github/workflows/push-pull.yml

Once this is working I'll start cleaning up the older runners.

Add a new CI runner with updated dependencies.

---

Makefile.in
examples/IBLevelSet/ex6/Makefile.in
ibtk/Makefile.in

I'll be frank - dealing with two build systems is not a good use of our time anymore. We should either automate this kind of check or delete autotools.

Fix some out-of-date autotools files.

---

.github/workflows/push-pull.yml

Inspired by a recent deal.II commit. If this works I'll keep iterating to remove the rest of the copy and paste code in future PRs.
This is a CI change so the normal checklist doesn't apply.

CI: use a matrix.

---

.github/workflows/push-pull.yml

Follow-up to #1788: we can use the matrix function to make all three cmake-based runners use one template.

CI: combine two more runners.

---

include/ibamr/INSStaggeredHierarchyIntegrator.h
src/navier_stokes/INSStaggeredHierarchyIntegrator.cpp

avoid some synchs

---

ibtk/include/ibtk/CCLaplaceOperator.h
ibtk/include/ibtk/SCLaplaceOperator.h
ibtk/src/solvers/impls/CCLaplaceOperator.cpp
ibtk/src/solvers/impls/SCLaplaceOperator.cpp
ibtk/src/solvers/impls/VCSCViscousOperator.cpp
include/ibamr/StaggeredStokesOperator.h
src/IB/CIBStaggeredStokesOperator.cpp
src/navier_stokes/INSStaggeredHierarchyIntegrator.cpp
src/navier_stokes/StaggeredStokesOperator.cpp
src/navier_stokes/VCStaggeredStokesOperator.cpp

avoid some copies

---

.github/workflows/push-master.yml
.github/workflows/push-pull.yml

Fix CI caching

---

src/navier_stokes/INSStaggeredHierarchyIntegrator.cpp
tests/navier_stokes/navier_stokes_01_2d.input
tests/navier_stokes/navier_stokes_01_2d.output

fix EE viz output in INSStaggeredHierarchyIntegrator

---

Makefile.in
doc/news/changes/minor/20250424AaronBarrett
ibtk/Makefile.in
include/ibamr/CFUpperConvectiveOperator.h
src/complex_fluids/CFUpperConvectiveOperator.cpp
src/complex_fluids/fortran/upper_convective_op2d.f.m4
src/complex_fluids/fortran/upper_convective_op3d.f.m4
tests/CMakeLists.txt
tests/complex_fluids/Makefile.am
tests/complex_fluids/Makefile.in
tests/complex_fluids/cf_ucd.cpp
tests/complex_fluids/cf_ucd_2d.input
tests/complex_fluids/cf_ucd_2d.output
tests/complex_fluids/cf_ucd_3d.input
tests/complex_fluids/cf_ucd_3d.output

Fixed upper convected derivative in cases of non divergence-free velocity fields.

---

examples/DLM/ex0/example.cpp

This, combined with the class-specific restart file names patch, fixes this example.

Fix restarts with the DLM example.

---

.github/workflows/push-pull.yml
ibtk/include/ibtk/private/LDataManager-inl.h
include/ibamr/LevelSetUtilities.h
include/ibamr/SurfaceTensionForceFunction.h
include/ibamr/private/IBInstrumentationSpec-inl.h

Fixes #1572.
~I need to add one more check but let me first ensure the first two are working.~ I added the missing check and everything looks good.

CI: add some simple header checks.

---

.github/workflows/push-master.yml
.github/workflows/push-pull.yml

This is just for the CI so the normal checklist doesn't apply. This commit shouldn't go on the release branch (i.e., we should merge it after #1841 and #1842 and we branch)

CI: update the docker containers.
